/**
 * @file eveurope_charger.c
 *
 * @brief This source file was generated by cantools version 41.3.1 Sun May 10 19:58:41 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "eveurope_charger.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int eveurope_charger_bms_charging_request_pack(
    uint8_t *dst_p,
    const struct eveurope_charger_bms_charging_request_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->max_charging_voltage, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->max_charging_voltage, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->max_charging_current, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->max_charging_current, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->control, 0u, 0xffu);

    return (8);
}

int eveurope_charger_bms_charging_request_unpack(
    struct eveurope_charger_bms_charging_request_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->max_charging_voltage = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->max_charging_voltage |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->max_charging_current = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->max_charging_current |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->control = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

int eveurope_charger_bms_charging_request_init(struct eveurope_charger_bms_charging_request_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct eveurope_charger_bms_charging_request_t));

    return 0;
}

uint16_t eveurope_charger_bms_charging_request_max_charging_voltage_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double eveurope_charger_bms_charging_request_max_charging_voltage_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool eveurope_charger_bms_charging_request_max_charging_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool eveurope_charger_bms_charging_request_max_charging_voltage_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 6553.5));
}

uint16_t eveurope_charger_bms_charging_request_max_charging_current_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double eveurope_charger_bms_charging_request_max_charging_current_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool eveurope_charger_bms_charging_request_max_charging_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool eveurope_charger_bms_charging_request_max_charging_current_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 6553.5));
}

uint8_t eveurope_charger_bms_charging_request_control_encode(double value)
{
    return (uint8_t)(value);
}

double eveurope_charger_bms_charging_request_control_decode(uint8_t value)
{
    return ((double)value);
}

bool eveurope_charger_bms_charging_request_control_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool eveurope_charger_bms_charging_request_control_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int eveurope_charger_charger_status_pack(
    uint8_t *dst_p,
    const struct eveurope_charger_charger_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->output_voltage, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->output_voltage, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->output_current, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->output_current, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->hw_failure, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->temp_otp, 1u, 0x02u);
    dst_p[4] |= pack_left_shift_u8(src_p->input_voltage_fault, 2u, 0x04u);
    dst_p[4] |= pack_left_shift_u8(src_p->starting_state_fault, 3u, 0x08u);
    dst_p[4] |= pack_left_shift_u8(src_p->comm_timeout, 4u, 0x10u);
    dst_p[5] |= pack_left_shift_u8(src_p->charger_temperature, 0u, 0xffu);

    return (8);
}

int eveurope_charger_charger_status_unpack(
    struct eveurope_charger_charger_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->output_voltage = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->output_voltage |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->output_current = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->output_current |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->hw_failure = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->temp_otp = unpack_right_shift_u8(src_p[4], 1u, 0x02u);
    dst_p->input_voltage_fault = unpack_right_shift_u8(src_p[4], 2u, 0x04u);
    dst_p->starting_state_fault = unpack_right_shift_u8(src_p[4], 3u, 0x08u);
    dst_p->comm_timeout = unpack_right_shift_u8(src_p[4], 4u, 0x10u);
    dst_p->charger_temperature = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

int eveurope_charger_charger_status_init(struct eveurope_charger_charger_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct eveurope_charger_charger_status_t));

    return 0;
}

uint16_t eveurope_charger_charger_status_output_voltage_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double eveurope_charger_charger_status_output_voltage_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool eveurope_charger_charger_status_output_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool eveurope_charger_charger_status_output_voltage_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 6553.5));
}

uint16_t eveurope_charger_charger_status_output_current_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double eveurope_charger_charger_status_output_current_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool eveurope_charger_charger_status_output_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool eveurope_charger_charger_status_output_current_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 6553.5));
}

uint8_t eveurope_charger_charger_status_hw_failure_encode(double value)
{
    return (uint8_t)(value);
}

double eveurope_charger_charger_status_hw_failure_decode(uint8_t value)
{
    return ((double)value);
}

bool eveurope_charger_charger_status_hw_failure_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool eveurope_charger_charger_status_hw_failure_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t eveurope_charger_charger_status_temp_otp_encode(double value)
{
    return (uint8_t)(value);
}

double eveurope_charger_charger_status_temp_otp_decode(uint8_t value)
{
    return ((double)value);
}

bool eveurope_charger_charger_status_temp_otp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool eveurope_charger_charger_status_temp_otp_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t eveurope_charger_charger_status_input_voltage_fault_encode(double value)
{
    return (uint8_t)(value);
}

double eveurope_charger_charger_status_input_voltage_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool eveurope_charger_charger_status_input_voltage_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool eveurope_charger_charger_status_input_voltage_fault_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t eveurope_charger_charger_status_starting_state_fault_encode(double value)
{
    return (uint8_t)(value);
}

double eveurope_charger_charger_status_starting_state_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool eveurope_charger_charger_status_starting_state_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool eveurope_charger_charger_status_starting_state_fault_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t eveurope_charger_charger_status_comm_timeout_encode(double value)
{
    return (uint8_t)(value);
}

double eveurope_charger_charger_status_comm_timeout_decode(uint8_t value)
{
    return ((double)value);
}

bool eveurope_charger_charger_status_comm_timeout_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool eveurope_charger_charger_status_comm_timeout_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t eveurope_charger_charger_status_charger_temperature_encode(double value)
{
    return (uint8_t)(value - -40.0);
}

double eveurope_charger_charger_status_charger_temperature_decode(uint8_t value)
{
    return ((double)value + -40.0);
}

bool eveurope_charger_charger_status_charger_temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool eveurope_charger_charger_status_charger_temperature_is_in_phys_range(double value)
{
    return ((value >= -40.0) && (value <= 215.0));
}

int eveurope_charger_bms_charging_request_p998_pack(
    uint8_t *dst_p,
    const struct eveurope_charger_bms_charging_request_p998_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->max_charging_voltage, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->max_charging_voltage, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->max_charging_current, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->max_charging_current, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->control, 0u, 0xffu);

    return (8);
}

int eveurope_charger_bms_charging_request_p998_unpack(
    struct eveurope_charger_bms_charging_request_p998_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->max_charging_voltage = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->max_charging_voltage |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->max_charging_current = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->max_charging_current |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->control = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

int eveurope_charger_bms_charging_request_p998_init(struct eveurope_charger_bms_charging_request_p998_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct eveurope_charger_bms_charging_request_p998_t));

    return 0;
}

uint16_t eveurope_charger_bms_charging_request_p998_max_charging_voltage_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double eveurope_charger_bms_charging_request_p998_max_charging_voltage_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool eveurope_charger_bms_charging_request_p998_max_charging_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool eveurope_charger_bms_charging_request_p998_max_charging_voltage_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 6553.5));
}

uint16_t eveurope_charger_bms_charging_request_p998_max_charging_current_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double eveurope_charger_bms_charging_request_p998_max_charging_current_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool eveurope_charger_bms_charging_request_p998_max_charging_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool eveurope_charger_bms_charging_request_p998_max_charging_current_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 6553.5));
}

uint8_t eveurope_charger_bms_charging_request_p998_control_encode(double value)
{
    return (uint8_t)(value);
}

double eveurope_charger_bms_charging_request_p998_control_decode(uint8_t value)
{
    return ((double)value);
}

bool eveurope_charger_bms_charging_request_p998_control_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool eveurope_charger_bms_charging_request_p998_control_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int eveurope_charger_charger_status_p998_pack(
    uint8_t *dst_p,
    const struct eveurope_charger_charger_status_p998_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->output_voltage, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->output_voltage, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->output_current, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->output_current, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->hw_failure, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->temp_otp, 1u, 0x02u);
    dst_p[4] |= pack_left_shift_u8(src_p->input_voltage_fault, 2u, 0x04u);
    dst_p[4] |= pack_left_shift_u8(src_p->starting_state_fault, 3u, 0x08u);
    dst_p[4] |= pack_left_shift_u8(src_p->comm_timeout, 4u, 0x10u);
    dst_p[5] |= pack_left_shift_u8(src_p->charger_temperature, 0u, 0xffu);

    return (8);
}

int eveurope_charger_charger_status_p998_unpack(
    struct eveurope_charger_charger_status_p998_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->output_voltage = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->output_voltage |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->output_current = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->output_current |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->hw_failure = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->temp_otp = unpack_right_shift_u8(src_p[4], 1u, 0x02u);
    dst_p->input_voltage_fault = unpack_right_shift_u8(src_p[4], 2u, 0x04u);
    dst_p->starting_state_fault = unpack_right_shift_u8(src_p[4], 3u, 0x08u);
    dst_p->comm_timeout = unpack_right_shift_u8(src_p[4], 4u, 0x10u);
    dst_p->charger_temperature = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

int eveurope_charger_charger_status_p998_init(struct eveurope_charger_charger_status_p998_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct eveurope_charger_charger_status_p998_t));

    return 0;
}

uint16_t eveurope_charger_charger_status_p998_output_voltage_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double eveurope_charger_charger_status_p998_output_voltage_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool eveurope_charger_charger_status_p998_output_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool eveurope_charger_charger_status_p998_output_voltage_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 6553.5));
}

uint16_t eveurope_charger_charger_status_p998_output_current_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double eveurope_charger_charger_status_p998_output_current_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool eveurope_charger_charger_status_p998_output_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool eveurope_charger_charger_status_p998_output_current_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 6553.5));
}

uint8_t eveurope_charger_charger_status_p998_hw_failure_encode(double value)
{
    return (uint8_t)(value);
}

double eveurope_charger_charger_status_p998_hw_failure_decode(uint8_t value)
{
    return ((double)value);
}

bool eveurope_charger_charger_status_p998_hw_failure_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool eveurope_charger_charger_status_p998_hw_failure_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t eveurope_charger_charger_status_p998_temp_otp_encode(double value)
{
    return (uint8_t)(value);
}

double eveurope_charger_charger_status_p998_temp_otp_decode(uint8_t value)
{
    return ((double)value);
}

bool eveurope_charger_charger_status_p998_temp_otp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool eveurope_charger_charger_status_p998_temp_otp_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t eveurope_charger_charger_status_p998_input_voltage_fault_encode(double value)
{
    return (uint8_t)(value);
}

double eveurope_charger_charger_status_p998_input_voltage_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool eveurope_charger_charger_status_p998_input_voltage_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool eveurope_charger_charger_status_p998_input_voltage_fault_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t eveurope_charger_charger_status_p998_starting_state_fault_encode(double value)
{
    return (uint8_t)(value);
}

double eveurope_charger_charger_status_p998_starting_state_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool eveurope_charger_charger_status_p998_starting_state_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool eveurope_charger_charger_status_p998_starting_state_fault_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t eveurope_charger_charger_status_p998_comm_timeout_encode(double value)
{
    return (uint8_t)(value);
}

double eveurope_charger_charger_status_p998_comm_timeout_decode(uint8_t value)
{
    return ((double)value);
}

bool eveurope_charger_charger_status_p998_comm_timeout_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool eveurope_charger_charger_status_p998_comm_timeout_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t eveurope_charger_charger_status_p998_charger_temperature_encode(double value)
{
    return (uint8_t)(value - -40.0);
}

double eveurope_charger_charger_status_p998_charger_temperature_decode(uint8_t value)
{
    return ((double)value + -40.0);
}

bool eveurope_charger_charger_status_p998_charger_temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool eveurope_charger_charger_status_p998_charger_temperature_is_in_phys_range(double value)
{
    return ((value >= -40.0) && (value <= 215.0));
}

int eveurope_charger_bms_charging_request_p1000_pack(
    uint8_t *dst_p,
    const struct eveurope_charger_bms_charging_request_p1000_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->max_charging_voltage, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->max_charging_voltage, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->max_charging_current, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->max_charging_current, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->control, 0u, 0xffu);

    return (8);
}

int eveurope_charger_bms_charging_request_p1000_unpack(
    struct eveurope_charger_bms_charging_request_p1000_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->max_charging_voltage = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->max_charging_voltage |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->max_charging_current = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->max_charging_current |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->control = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

int eveurope_charger_bms_charging_request_p1000_init(struct eveurope_charger_bms_charging_request_p1000_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct eveurope_charger_bms_charging_request_p1000_t));

    return 0;
}

uint16_t eveurope_charger_bms_charging_request_p1000_max_charging_voltage_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double eveurope_charger_bms_charging_request_p1000_max_charging_voltage_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool eveurope_charger_bms_charging_request_p1000_max_charging_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool eveurope_charger_bms_charging_request_p1000_max_charging_voltage_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 6553.5));
}

uint16_t eveurope_charger_bms_charging_request_p1000_max_charging_current_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double eveurope_charger_bms_charging_request_p1000_max_charging_current_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool eveurope_charger_bms_charging_request_p1000_max_charging_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool eveurope_charger_bms_charging_request_p1000_max_charging_current_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 6553.5));
}

uint8_t eveurope_charger_bms_charging_request_p1000_control_encode(double value)
{
    return (uint8_t)(value);
}

double eveurope_charger_bms_charging_request_p1000_control_decode(uint8_t value)
{
    return ((double)value);
}

bool eveurope_charger_bms_charging_request_p1000_control_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool eveurope_charger_bms_charging_request_p1000_control_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int eveurope_charger_charger_status_p1000_pack(
    uint8_t *dst_p,
    const struct eveurope_charger_charger_status_p1000_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->output_voltage, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->output_voltage, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->output_current, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->output_current, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->hw_failure, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->temp_otp, 1u, 0x02u);
    dst_p[4] |= pack_left_shift_u8(src_p->input_voltage_fault, 2u, 0x04u);
    dst_p[4] |= pack_left_shift_u8(src_p->starting_state_fault, 3u, 0x08u);
    dst_p[4] |= pack_left_shift_u8(src_p->comm_timeout, 4u, 0x10u);
    dst_p[5] |= pack_left_shift_u8(src_p->charger_temperature, 0u, 0xffu);

    return (8);
}

int eveurope_charger_charger_status_p1000_unpack(
    struct eveurope_charger_charger_status_p1000_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->output_voltage = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->output_voltage |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->output_current = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->output_current |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->hw_failure = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->temp_otp = unpack_right_shift_u8(src_p[4], 1u, 0x02u);
    dst_p->input_voltage_fault = unpack_right_shift_u8(src_p[4], 2u, 0x04u);
    dst_p->starting_state_fault = unpack_right_shift_u8(src_p[4], 3u, 0x08u);
    dst_p->comm_timeout = unpack_right_shift_u8(src_p[4], 4u, 0x10u);
    dst_p->charger_temperature = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

int eveurope_charger_charger_status_p1000_init(struct eveurope_charger_charger_status_p1000_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct eveurope_charger_charger_status_p1000_t));

    return 0;
}

uint16_t eveurope_charger_charger_status_p1000_output_voltage_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double eveurope_charger_charger_status_p1000_output_voltage_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool eveurope_charger_charger_status_p1000_output_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool eveurope_charger_charger_status_p1000_output_voltage_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 6553.5));
}

uint16_t eveurope_charger_charger_status_p1000_output_current_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double eveurope_charger_charger_status_p1000_output_current_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool eveurope_charger_charger_status_p1000_output_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool eveurope_charger_charger_status_p1000_output_current_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 6553.5));
}

uint8_t eveurope_charger_charger_status_p1000_hw_failure_encode(double value)
{
    return (uint8_t)(value);
}

double eveurope_charger_charger_status_p1000_hw_failure_decode(uint8_t value)
{
    return ((double)value);
}

bool eveurope_charger_charger_status_p1000_hw_failure_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool eveurope_charger_charger_status_p1000_hw_failure_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t eveurope_charger_charger_status_p1000_temp_otp_encode(double value)
{
    return (uint8_t)(value);
}

double eveurope_charger_charger_status_p1000_temp_otp_decode(uint8_t value)
{
    return ((double)value);
}

bool eveurope_charger_charger_status_p1000_temp_otp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool eveurope_charger_charger_status_p1000_temp_otp_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t eveurope_charger_charger_status_p1000_input_voltage_fault_encode(double value)
{
    return (uint8_t)(value);
}

double eveurope_charger_charger_status_p1000_input_voltage_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool eveurope_charger_charger_status_p1000_input_voltage_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool eveurope_charger_charger_status_p1000_input_voltage_fault_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t eveurope_charger_charger_status_p1000_starting_state_fault_encode(double value)
{
    return (uint8_t)(value);
}

double eveurope_charger_charger_status_p1000_starting_state_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool eveurope_charger_charger_status_p1000_starting_state_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool eveurope_charger_charger_status_p1000_starting_state_fault_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t eveurope_charger_charger_status_p1000_comm_timeout_encode(double value)
{
    return (uint8_t)(value);
}

double eveurope_charger_charger_status_p1000_comm_timeout_decode(uint8_t value)
{
    return ((double)value);
}

bool eveurope_charger_charger_status_p1000_comm_timeout_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool eveurope_charger_charger_status_p1000_comm_timeout_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t eveurope_charger_charger_status_p1000_charger_temperature_encode(double value)
{
    return (uint8_t)(value - -40.0);
}

double eveurope_charger_charger_status_p1000_charger_temperature_decode(uint8_t value)
{
    return ((double)value + -40.0);
}

bool eveurope_charger_charger_status_p1000_charger_temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool eveurope_charger_charger_status_p1000_charger_temperature_is_in_phys_range(double value)
{
    return ((value >= -40.0) && (value <= 215.0));
}
