/**
 * @file eveurope_charger.h
 *
 * @brief This header file was generated by cantools version 41.3.1 Sun May 10 19:58:41 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef EVEUROPE_CHARGER_H
#define EVEUROPE_CHARGER_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_FRAME_ID (0x1806e8f4u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_FRAME_ID (0x18ff50e8u)
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_P998_FRAME_ID (0x1806e7f4u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_FRAME_ID (0x18ff50e7u)
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_P1000_FRAME_ID (0x1806e5f4u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_FRAME_ID (0x18ff50e5u)

/* Frame lengths in bytes. */
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_LENGTH (8u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_LENGTH (8u)
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_P998_LENGTH (8u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_LENGTH (8u)
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_P1000_LENGTH (8u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_LENGTH (8u)

/* Extended or standard frame types. */
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_IS_EXTENDED (1)
#define EVEUROPE_CHARGER_CHARGER_STATUS_IS_EXTENDED (1)
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_P998_IS_EXTENDED (1)
#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_IS_EXTENDED (1)
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_P1000_IS_EXTENDED (1)
#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_IS_EXTENDED (1)

/* Frame cycle times in milliseconds. */
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_CYCLE_TIME_MS (1000u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_CYCLE_TIME_MS (1000u)
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_P998_CYCLE_TIME_MS (1000u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_CYCLE_TIME_MS (1000u)
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_P1000_CYCLE_TIME_MS (1000u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_CYCLE_TIME_MS (1000u)

/* Signal choices. */
#define EVEUROPE_CHARGER_CHARGER_STATUS_HW_FAILURE_NORMAL_CHOICE (0u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_HW_FAILURE_HARDWARE_FAILURE_CHOICE (1u)

#define EVEUROPE_CHARGER_CHARGER_STATUS_TEMP_OTP_NORMAL_CHOICE (0u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_TEMP_OTP_OVER_TEMPERATURE_PROTECTION_CHOICE (1u)

#define EVEUROPE_CHARGER_CHARGER_STATUS_INPUT_VOLTAGE_FAULT_NORMAL_INPUT_VOLTAGE_CHOICE (0u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_INPUT_VOLTAGE_FAULT_INCORRECT_INPUT_VOLTAGE_CHARGER_STOP_CHOICE (1u)

#define EVEUROPE_CHARGER_CHARGER_STATUS_STARTING_STATE_FAULT_NORMAL_BATTERY_CONNECTED_CHOICE (0u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_STARTING_STATE_FAULT_BATTERY_DISCONNECTING_OR_REVERSE_CHOICE (1u)

#define EVEUROPE_CHARGER_CHARGER_STATUS_COMM_TIMEOUT_NORMAL_COMMUNICATION_CHOICE (0u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_COMM_TIMEOUT_RECEIVING_TIMEOUT_CHOICE (1u)

#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_HW_FAILURE_NORMAL_CHOICE (0u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_HW_FAILURE_HARDWARE_FAILURE_CHOICE (1u)

#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_TEMP_OTP_NORMAL_CHOICE (0u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_TEMP_OTP_OVER_TEMPERATURE_PROTECTION_CHOICE (1u)

#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_INPUT_VOLTAGE_FAULT_NORMAL_INPUT_VOLTAGE_CHOICE (0u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_INPUT_VOLTAGE_FAULT_INCORRECT_INPUT_VOLTAGE_CHARGER_STOP_CHOICE (1u)

#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_STARTING_STATE_FAULT_NORMAL_BATTERY_CONNECTED_CHOICE (0u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_STARTING_STATE_FAULT_BATTERY_DISCONNECTING_OR_REVERSE_CHOICE (1u)

#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_COMM_TIMEOUT_NORMAL_COMMUNICATION_CHOICE (0u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_COMM_TIMEOUT_RECEIVING_TIMEOUT_CHOICE (1u)

#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_HW_FAILURE_NORMAL_CHOICE (0u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_HW_FAILURE_HARDWARE_FAILURE_CHOICE (1u)

#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_TEMP_OTP_NORMAL_CHOICE (0u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_TEMP_OTP_OVER_TEMPERATURE_PROTECTION_CHOICE (1u)

#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_INPUT_VOLTAGE_FAULT_NORMAL_INPUT_VOLTAGE_CHOICE (0u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_INPUT_VOLTAGE_FAULT_INCORRECT_INPUT_VOLTAGE_CHARGER_STOP_CHOICE (1u)

#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_STARTING_STATE_FAULT_NORMAL_BATTERY_CONNECTED_CHOICE (0u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_STARTING_STATE_FAULT_BATTERY_DISCONNECTING_OR_REVERSE_CHOICE (1u)

#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_COMM_TIMEOUT_NORMAL_COMMUNICATION_CHOICE (0u)
#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_COMM_TIMEOUT_RECEIVING_TIMEOUT_CHOICE (1u)

/* Frame Names. */
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_NAME "BMS_ChargingRequest"
#define EVEUROPE_CHARGER_CHARGER_STATUS_NAME "Charger_Status"
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_P998_NAME "BMS_ChargingRequest_P998"
#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_NAME "Charger_Status_P998"
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_P1000_NAME "BMS_ChargingRequest_P1000"
#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_NAME "Charger_Status_P1000"

/* Signal Names. */
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_MAX_CHARGING_VOLTAGE_NAME "Max_Charging_Voltage"
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_MAX_CHARGING_CURRENT_NAME "Max_Charging_Current"
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_CONTROL_NAME "Control"
#define EVEUROPE_CHARGER_CHARGER_STATUS_OUTPUT_VOLTAGE_NAME "Output_Voltage"
#define EVEUROPE_CHARGER_CHARGER_STATUS_OUTPUT_CURRENT_NAME "Output_Current"
#define EVEUROPE_CHARGER_CHARGER_STATUS_HW_FAILURE_NAME "HW_Failure"
#define EVEUROPE_CHARGER_CHARGER_STATUS_TEMP_OTP_NAME "Temp_OTP"
#define EVEUROPE_CHARGER_CHARGER_STATUS_INPUT_VOLTAGE_FAULT_NAME "Input_Voltage_Fault"
#define EVEUROPE_CHARGER_CHARGER_STATUS_STARTING_STATE_FAULT_NAME "Starting_State_Fault"
#define EVEUROPE_CHARGER_CHARGER_STATUS_COMM_TIMEOUT_NAME "Comm_Timeout"
#define EVEUROPE_CHARGER_CHARGER_STATUS_CHARGER_TEMPERATURE_NAME "Charger_Temperature"
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_P998_MAX_CHARGING_VOLTAGE_NAME "Max_Charging_Voltage"
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_P998_MAX_CHARGING_CURRENT_NAME "Max_Charging_Current"
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_P998_CONTROL_NAME "Control"
#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_OUTPUT_VOLTAGE_NAME "Output_Voltage"
#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_OUTPUT_CURRENT_NAME "Output_Current"
#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_HW_FAILURE_NAME "HW_Failure"
#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_TEMP_OTP_NAME "Temp_OTP"
#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_INPUT_VOLTAGE_FAULT_NAME "Input_Voltage_Fault"
#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_STARTING_STATE_FAULT_NAME "Starting_State_Fault"
#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_COMM_TIMEOUT_NAME "Comm_Timeout"
#define EVEUROPE_CHARGER_CHARGER_STATUS_P998_CHARGER_TEMPERATURE_NAME "Charger_Temperature"
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_P1000_MAX_CHARGING_VOLTAGE_NAME "Max_Charging_Voltage"
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_P1000_MAX_CHARGING_CURRENT_NAME "Max_Charging_Current"
#define EVEUROPE_CHARGER_BMS_CHARGING_REQUEST_P1000_CONTROL_NAME "Control"
#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_OUTPUT_VOLTAGE_NAME "Output_Voltage"
#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_OUTPUT_CURRENT_NAME "Output_Current"
#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_HW_FAILURE_NAME "HW_Failure"
#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_TEMP_OTP_NAME "Temp_OTP"
#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_INPUT_VOLTAGE_FAULT_NAME "Input_Voltage_Fault"
#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_STARTING_STATE_FAULT_NAME "Starting_State_Fault"
#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_COMM_TIMEOUT_NAME "Comm_Timeout"
#define EVEUROPE_CHARGER_CHARGER_STATUS_P1000_CHARGER_TEMPERATURE_NAME "Charger_Temperature"

/**
 * Signals in message BMS_ChargingRequest.
 *
 * BMS to Charger: charging setpoints. CAN ID 0x1806E8F4 (Protocol 997/1197). Cycle 1000ms.
 *
 * All signal values are as on the CAN bus.
 */
struct eveurope_charger_bms_charging_request_t {
    /**
     * Max allowable charging terminal voltage. Resolution 0.1V/bit. e.g. Vset=3201 -> 320.1V
     *
     * Range: 0..65535 (0..6553.5 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t max_charging_voltage;

    /**
     * Max allowable charging current. Resolution 0.1A/bit. e.g. Iset=582 -> 58.2A
     *
     * Range: 0..65535 (0..6553.5 A)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t max_charging_current;

    /**
     * 0: Starting to charge 1 (Battery protection, charger close output)
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t control;
};

/**
 * Signals in message Charger_Status.
 *
 * Charger to BMS: actual output status. CAN ID 0x18FF50E8 (Protocol 997/1197). Cycle 1000ms.
 *
 * All signal values are as on the CAN bus.
 */
struct eveurope_charger_charger_status_t {
    /**
     * Actual charger output voltage. Resolution 0.1V/bit. e.g. Vout=3201 -> 320.1V
     *
     * Range: 0..65535 (0..6553.5 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t output_voltage;

    /**
     * Actual charger output current. Resolution 0.1A/bit. e.g. Iout=582 -> 58.2A. Highest byte mark: 0=Charging, 1=Discharging
     *
     * Range: 0..65535 (0..6553.5 A)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t output_current;

    /**
     * Bit0 STATUS: Hardware failure flag
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t hw_failure;

    /**
     * Bit1 STATUS: Temperature of charger flag
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t temp_otp;

    /**
     * Bit2 STATUS: Input voltage flag
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t input_voltage_fault;

    /**
     * Bit3 STATUS: Starting state (battery connection)
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t starting_state_fault;

    /**
     * Bit4 STATUS: Communication timeout flag
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t comm_timeout;

    /**
     * Charger internal temperature. Offset -40 degC.
     *
     * Range: 0..255 (-40..215 degC)
     * Scale: 1
     * Offset: -40
     */
    uint8_t charger_temperature;
};

/**
 * Signals in message BMS_ChargingRequest_P998.
 *
 * BMS to Charger: charging setpoints. CAN ID 0x1806E7F4 (Protocol 998/1198). Cycle 1000ms.
 *
 * All signal values are as on the CAN bus.
 */
struct eveurope_charger_bms_charging_request_p998_t {
    /**
     * Range: 0..65535 (0..6553.5 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t max_charging_voltage;

    /**
     * Range: 0..65535 (0..6553.5 A)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t max_charging_current;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t control;
};

/**
 * Signals in message Charger_Status_P998.
 *
 * Charger to BMS: actual output status. CAN ID 0x18FF50E7 (Protocol 998/1198). Cycle 1000ms.
 *
 * All signal values are as on the CAN bus.
 */
struct eveurope_charger_charger_status_p998_t {
    /**
     * Range: 0..65535 (0..6553.5 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t output_voltage;

    /**
     * Range: 0..65535 (0..6553.5 A)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t output_current;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t hw_failure;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t temp_otp;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t input_voltage_fault;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t starting_state_fault;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t comm_timeout;

    /**
     * Range: 0..255 (-40..215 degC)
     * Scale: 1
     * Offset: -40
     */
    uint8_t charger_temperature;
};

/**
 * Signals in message BMS_ChargingRequest_P1000.
 *
 * BMS to Charger: charging setpoints. CAN ID 0x1806E5F4 (Protocol 1000/1200). Cycle 1000ms.
 *
 * All signal values are as on the CAN bus.
 */
struct eveurope_charger_bms_charging_request_p1000_t {
    /**
     * Range: 0..65535 (0..6553.5 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t max_charging_voltage;

    /**
     * Range: 0..65535 (0..6553.5 A)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t max_charging_current;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t control;
};

/**
 * Signals in message Charger_Status_P1000.
 *
 * Charger to BMS: actual output status. CAN ID 0x18FF50E5 (Protocol 1000/1200). Cycle 1000ms.
 *
 * All signal values are as on the CAN bus.
 */
struct eveurope_charger_charger_status_p1000_t {
    /**
     * Range: 0..65535 (0..6553.5 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t output_voltage;

    /**
     * Range: 0..65535 (0..6553.5 A)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t output_current;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t hw_failure;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t temp_otp;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t input_voltage_fault;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t starting_state_fault;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t comm_timeout;

    /**
     * Range: 0..255 (-40..215 degC)
     * Scale: 1
     * Offset: -40
     */
    uint8_t charger_temperature;
};

/**
 * Pack message BMS_ChargingRequest.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int eveurope_charger_bms_charging_request_pack(
    uint8_t *dst_p,
    const struct eveurope_charger_bms_charging_request_t *src_p,
    size_t size);

/**
 * Unpack message BMS_ChargingRequest.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int eveurope_charger_bms_charging_request_unpack(
    struct eveurope_charger_bms_charging_request_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMS_ChargingRequest.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int eveurope_charger_bms_charging_request_init(struct eveurope_charger_bms_charging_request_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t eveurope_charger_bms_charging_request_max_charging_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_bms_charging_request_max_charging_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_bms_charging_request_max_charging_voltage_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_bms_charging_request_max_charging_voltage_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t eveurope_charger_bms_charging_request_max_charging_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_bms_charging_request_max_charging_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_bms_charging_request_max_charging_current_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_bms_charging_request_max_charging_current_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_bms_charging_request_control_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_bms_charging_request_control_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_bms_charging_request_control_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_bms_charging_request_control_is_in_phys_range(double value);

/**
 * Pack message Charger_Status.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int eveurope_charger_charger_status_pack(
    uint8_t *dst_p,
    const struct eveurope_charger_charger_status_t *src_p,
    size_t size);

/**
 * Unpack message Charger_Status.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int eveurope_charger_charger_status_unpack(
    struct eveurope_charger_charger_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Charger_Status.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int eveurope_charger_charger_status_init(struct eveurope_charger_charger_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t eveurope_charger_charger_status_output_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_output_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_output_voltage_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_output_voltage_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t eveurope_charger_charger_status_output_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_output_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_output_current_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_output_current_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_charger_status_hw_failure_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_hw_failure_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_hw_failure_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_hw_failure_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_charger_status_temp_otp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_temp_otp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_temp_otp_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_temp_otp_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_charger_status_input_voltage_fault_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_input_voltage_fault_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_input_voltage_fault_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_input_voltage_fault_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_charger_status_starting_state_fault_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_starting_state_fault_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_starting_state_fault_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_starting_state_fault_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_charger_status_comm_timeout_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_comm_timeout_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_comm_timeout_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_comm_timeout_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_charger_status_charger_temperature_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_charger_temperature_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_charger_temperature_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_charger_temperature_is_in_phys_range(double value);

/**
 * Pack message BMS_ChargingRequest_P998.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int eveurope_charger_bms_charging_request_p998_pack(
    uint8_t *dst_p,
    const struct eveurope_charger_bms_charging_request_p998_t *src_p,
    size_t size);

/**
 * Unpack message BMS_ChargingRequest_P998.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int eveurope_charger_bms_charging_request_p998_unpack(
    struct eveurope_charger_bms_charging_request_p998_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMS_ChargingRequest_P998.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int eveurope_charger_bms_charging_request_p998_init(struct eveurope_charger_bms_charging_request_p998_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t eveurope_charger_bms_charging_request_p998_max_charging_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_bms_charging_request_p998_max_charging_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_bms_charging_request_p998_max_charging_voltage_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_bms_charging_request_p998_max_charging_voltage_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t eveurope_charger_bms_charging_request_p998_max_charging_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_bms_charging_request_p998_max_charging_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_bms_charging_request_p998_max_charging_current_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_bms_charging_request_p998_max_charging_current_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_bms_charging_request_p998_control_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_bms_charging_request_p998_control_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_bms_charging_request_p998_control_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_bms_charging_request_p998_control_is_in_phys_range(double value);

/**
 * Pack message Charger_Status_P998.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int eveurope_charger_charger_status_p998_pack(
    uint8_t *dst_p,
    const struct eveurope_charger_charger_status_p998_t *src_p,
    size_t size);

/**
 * Unpack message Charger_Status_P998.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int eveurope_charger_charger_status_p998_unpack(
    struct eveurope_charger_charger_status_p998_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Charger_Status_P998.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int eveurope_charger_charger_status_p998_init(struct eveurope_charger_charger_status_p998_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t eveurope_charger_charger_status_p998_output_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_p998_output_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p998_output_voltage_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p998_output_voltage_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t eveurope_charger_charger_status_p998_output_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_p998_output_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p998_output_current_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p998_output_current_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_charger_status_p998_hw_failure_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_p998_hw_failure_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p998_hw_failure_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p998_hw_failure_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_charger_status_p998_temp_otp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_p998_temp_otp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p998_temp_otp_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p998_temp_otp_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_charger_status_p998_input_voltage_fault_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_p998_input_voltage_fault_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p998_input_voltage_fault_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p998_input_voltage_fault_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_charger_status_p998_starting_state_fault_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_p998_starting_state_fault_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p998_starting_state_fault_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p998_starting_state_fault_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_charger_status_p998_comm_timeout_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_p998_comm_timeout_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p998_comm_timeout_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p998_comm_timeout_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_charger_status_p998_charger_temperature_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_p998_charger_temperature_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p998_charger_temperature_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p998_charger_temperature_is_in_phys_range(double value);

/**
 * Pack message BMS_ChargingRequest_P1000.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int eveurope_charger_bms_charging_request_p1000_pack(
    uint8_t *dst_p,
    const struct eveurope_charger_bms_charging_request_p1000_t *src_p,
    size_t size);

/**
 * Unpack message BMS_ChargingRequest_P1000.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int eveurope_charger_bms_charging_request_p1000_unpack(
    struct eveurope_charger_bms_charging_request_p1000_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMS_ChargingRequest_P1000.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int eveurope_charger_bms_charging_request_p1000_init(struct eveurope_charger_bms_charging_request_p1000_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t eveurope_charger_bms_charging_request_p1000_max_charging_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_bms_charging_request_p1000_max_charging_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_bms_charging_request_p1000_max_charging_voltage_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_bms_charging_request_p1000_max_charging_voltage_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t eveurope_charger_bms_charging_request_p1000_max_charging_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_bms_charging_request_p1000_max_charging_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_bms_charging_request_p1000_max_charging_current_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_bms_charging_request_p1000_max_charging_current_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_bms_charging_request_p1000_control_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_bms_charging_request_p1000_control_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_bms_charging_request_p1000_control_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_bms_charging_request_p1000_control_is_in_phys_range(double value);

/**
 * Pack message Charger_Status_P1000.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int eveurope_charger_charger_status_p1000_pack(
    uint8_t *dst_p,
    const struct eveurope_charger_charger_status_p1000_t *src_p,
    size_t size);

/**
 * Unpack message Charger_Status_P1000.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int eveurope_charger_charger_status_p1000_unpack(
    struct eveurope_charger_charger_status_p1000_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Charger_Status_P1000.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int eveurope_charger_charger_status_p1000_init(struct eveurope_charger_charger_status_p1000_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t eveurope_charger_charger_status_p1000_output_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_p1000_output_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p1000_output_voltage_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p1000_output_voltage_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t eveurope_charger_charger_status_p1000_output_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_p1000_output_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p1000_output_current_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p1000_output_current_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_charger_status_p1000_hw_failure_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_p1000_hw_failure_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p1000_hw_failure_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p1000_hw_failure_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_charger_status_p1000_temp_otp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_p1000_temp_otp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p1000_temp_otp_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p1000_temp_otp_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_charger_status_p1000_input_voltage_fault_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_p1000_input_voltage_fault_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p1000_input_voltage_fault_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p1000_input_voltage_fault_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_charger_status_p1000_starting_state_fault_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_p1000_starting_state_fault_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p1000_starting_state_fault_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p1000_starting_state_fault_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_charger_status_p1000_comm_timeout_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_p1000_comm_timeout_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p1000_comm_timeout_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p1000_comm_timeout_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eveurope_charger_charger_status_p1000_charger_temperature_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eveurope_charger_charger_status_p1000_charger_temperature_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p1000_charger_temperature_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eveurope_charger_charger_status_p1000_charger_temperature_is_in_phys_range(double value);


#ifdef __cplusplus
}
#endif

#endif
