.TH "ad29_cfb_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ad29_cfb_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bms_datatypes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBoc1th\fP:7"
.br
.ti -1c
.RI "uint8_t \fBunused1\fP:1"
.br
.ti -1c
.RI "uint8_t \fBoc2th\fP:7"
.br
.ti -1c
.RI "uint8_t \fBunused2\fP:1"
.br
.ti -1c
.RI "uint8_t \fBoc3th\fP:7"
.br
.ti -1c
.RI "uint8_t \fBunused3\fP:1"
.br
.ti -1c
.RI "uint8_t \fBocdgt\fP:2"
.br
.ti -1c
.RI "uint8_t \fBunused4\fP:1"
.br
.ti -1c
.RI "uint8_t \fBocdp\fP:1"
.br
.ti -1c
.RI "uint8_t \fBunused5\fP:4"
.br
.ti -1c
.RI "uint8_t \fBocod\fP:1"
.br
.ti -1c
.RI "uint8_t \fBoc1gc\fP:1"
.br
.ti -1c
.RI "uint8_t \fBoc2gc\fP:1"
.br
.ti -1c
.RI "uint8_t \fBoc3gc\fP:1"
.br
.ti -1c
.RI "uint8_t \fBocmode\fP:2"
.br
.ti -1c
.RI "uint8_t \fBocax\fP:1"
.br
.ti -1c
.RI "uint8_t \fBocbx\fP:1"
.br
.ti -1c
.RI "uint8_t \fBdiagsel\fP:3"
.br
.ti -1c
.RI "uint8_t \fBgpio2eoc\fP:1"
.br
.ti -1c
.RI "uint8_t \fBgpio1c\fP:1"
.br
.ti -1c
.RI "uint8_t \fBgpio2c\fP:1"
.br
.ti -1c
.RI "uint8_t \fBgpio3c\fP:1"
.br
.ti -1c
.RI "uint8_t \fBgpio4c\fP:1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 62 of file bms_datatypes\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t ad29_cfb_t::diagsel"

.PP
Definition at line 86 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::gpio1c"

.PP
Definition at line 88 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::gpio2c"

.PP
Definition at line 89 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::gpio2eoc"

.PP
Definition at line 87 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::gpio3c"

.PP
Definition at line 90 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::gpio4c"

.PP
Definition at line 91 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::oc1gc"

.PP
Definition at line 79 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::oc1th"

.PP
Definition at line 64 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::oc2gc"

.PP
Definition at line 80 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::oc2th"

.PP
Definition at line 67 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::oc3gc"

.PP
Definition at line 81 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::oc3th"

.PP
Definition at line 70 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::ocax"

.PP
Definition at line 83 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::ocbx"

.PP
Definition at line 84 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::ocdgt"

.PP
Definition at line 73 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::ocdp"

.PP
Definition at line 75 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::ocmode"

.PP
Definition at line 82 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::ocod"

.PP
Definition at line 78 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::unused1"

.PP
Definition at line 65 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::unused2"

.PP
Definition at line 68 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::unused3"

.PP
Definition at line 71 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::unused4"

.PP
Definition at line 74 of file bms_datatypes\&.h\&.
.SS "uint8_t ad29_cfb_t::unused5"

.PP
Definition at line 76 of file bms_datatypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
