.TH "ad68_pwma_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ad68_pwma_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bms_datatypes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBpwm1\fP:4"
.br
.ti -1c
.RI "uint8_t \fBpwm2\fP:4"
.br
.ti -1c
.RI "uint8_t \fBpwm3\fP:4"
.br
.ti -1c
.RI "uint8_t \fBpwm4\fP:4"
.br
.ti -1c
.RI "uint8_t \fBpwm5\fP:4"
.br
.ti -1c
.RI "uint8_t \fBpwm6\fP:4"
.br
.ti -1c
.RI "uint8_t \fBpwm7\fP:4"
.br
.ti -1c
.RI "uint8_t \fBpwm8\fP:4"
.br
.ti -1c
.RI "uint8_t \fBpwm9\fP:4"
.br
.ti -1c
.RI "uint8_t \fBpwm10\fP:4"
.br
.ti -1c
.RI "uint8_t \fBpwm11\fP:4"
.br
.ti -1c
.RI "uint8_t \fBpwm12\fP:4"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 140 of file bms_datatypes\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t ad68_pwma_t::pwm1"

.PP
Definition at line 142 of file bms_datatypes\&.h\&.
.PP
Referenced by bms_setPwm(), bms_startDischarge(), and send_ad68_ui()\&.
.SS "uint8_t ad68_pwma_t::pwm10"

.PP
Definition at line 155 of file bms_datatypes\&.h\&.
.PP
Referenced by bms_setPwm(), and send_ad68_ui()\&.
.SS "uint8_t ad68_pwma_t::pwm11"

.PP
Definition at line 157 of file bms_datatypes\&.h\&.
.PP
Referenced by bms_setPwm(), and send_ad68_ui()\&.
.SS "uint8_t ad68_pwma_t::pwm12"

.PP
Definition at line 158 of file bms_datatypes\&.h\&.
.PP
Referenced by bms_setPwm(), and send_ad68_ui()\&.
.SS "uint8_t ad68_pwma_t::pwm2"

.PP
Definition at line 143 of file bms_datatypes\&.h\&.
.PP
Referenced by bms_setPwm(), and send_ad68_ui()\&.
.SS "uint8_t ad68_pwma_t::pwm3"

.PP
Definition at line 145 of file bms_datatypes\&.h\&.
.PP
Referenced by bms_setPwm(), and send_ad68_ui()\&.
.SS "uint8_t ad68_pwma_t::pwm4"

.PP
Definition at line 146 of file bms_datatypes\&.h\&.
.PP
Referenced by bms_setPwm(), and send_ad68_ui()\&.
.SS "uint8_t ad68_pwma_t::pwm5"

.PP
Definition at line 148 of file bms_datatypes\&.h\&.
.PP
Referenced by bms_setPwm(), and send_ad68_ui()\&.
.SS "uint8_t ad68_pwma_t::pwm6"

.PP
Definition at line 149 of file bms_datatypes\&.h\&.
.PP
Referenced by bms_setPwm(), and send_ad68_ui()\&.
.SS "uint8_t ad68_pwma_t::pwm7"

.PP
Definition at line 151 of file bms_datatypes\&.h\&.
.PP
Referenced by bms_setPwm(), and send_ad68_ui()\&.
.SS "uint8_t ad68_pwma_t::pwm8"

.PP
Definition at line 152 of file bms_datatypes\&.h\&.
.PP
Referenced by bms_setPwm(), and send_ad68_ui()\&.
.SS "uint8_t ad68_pwma_t::pwm9"

.PP
Definition at line 154 of file bms_datatypes\&.h\&.
.PP
Referenced by bms_setPwm(), and send_ad68_ui()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
