.TH "ad68_cfb_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ad68_cfb_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bms_datatypes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBvuv0to7\fP:8"
.br
.ti -1c
.RI "uint8_t \fBvuv8to11\fP:4"
.br
.ti -1c
.RI "uint8_t \fBvov0to3\fP:4"
.br
.ti -1c
.RI "uint8_t \fBvov4to11\fP:8"
.br
.ti -1c
.RI "uint8_t \fBdcto\fP:6"
.br
.ti -1c
.RI "uint8_t \fBdtrng\fP:1"
.br
.ti -1c
.RI "uint8_t \fBdtmen\fP:1"
.br
.ti -1c
.RI "uint16_t \fBdcc\fP:16"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 123 of file bms_datatypes\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ad68_cfb_t::dcc"

.PP
Definition at line 136 of file bms_datatypes\&.h\&.
.PP
Referenced by send_ad68_ui()\&.
.SS "uint8_t ad68_cfb_t::dcto"

.PP
Definition at line 132 of file bms_datatypes\&.h\&.
.PP
Referenced by bms_startDischarge(), and send_ad68_ui()\&.
.SS "uint8_t ad68_cfb_t::dtmen"

.PP
Definition at line 134 of file bms_datatypes\&.h\&.
.PP
Referenced by bms_startDischarge(), and send_ad68_ui()\&.
.SS "uint8_t ad68_cfb_t::dtrng"

.PP
Definition at line 133 of file bms_datatypes\&.h\&.
.PP
Referenced by send_ad68_ui()\&.
.SS "uint8_t ad68_cfb_t::vov0to3"

.PP
Definition at line 128 of file bms_datatypes\&.h\&.
.PP
Referenced by send_ad68_ui()\&.
.SS "uint8_t ad68_cfb_t::vov4to11"

.PP
Definition at line 130 of file bms_datatypes\&.h\&.
.PP
Referenced by send_ad68_ui()\&.
.SS "uint8_t ad68_cfb_t::vuv0to7"

.PP
Definition at line 125 of file bms_datatypes\&.h\&.
.PP
Referenced by send_ad68_ui()\&.
.SS "uint8_t ad68_cfb_t::vuv8to11"

.PP
Definition at line 127 of file bms_datatypes\&.h\&.
.PP
Referenced by send_ad68_ui()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
