.TH "ad68_pwmb_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ad68_pwmb_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bms_datatypes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBpwm13\fP:4"
.br
.ti -1c
.RI "uint8_t \fBpwm14\fP:4"
.br
.ti -1c
.RI "uint8_t \fBpwm15\fP:4"
.br
.ti -1c
.RI "uint8_t \fBpwm16\fP:4"
.br
.ti -1c
.RI "uint32_t \fBrsv\fP:32"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 162 of file bms_datatypes\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t ad68_pwmb_t::pwm13"

.PP
Definition at line 164 of file bms_datatypes\&.h\&.
.PP
Referenced by bms_setPwm(), and send_ad68_ui()\&.
.SS "uint8_t ad68_pwmb_t::pwm14"

.PP
Definition at line 165 of file bms_datatypes\&.h\&.
.PP
Referenced by bms_setPwm(), and send_ad68_ui()\&.
.SS "uint8_t ad68_pwmb_t::pwm15"

.PP
Definition at line 167 of file bms_datatypes\&.h\&.
.PP
Referenced by bms_setPwm(), and send_ad68_ui()\&.
.SS "uint8_t ad68_pwmb_t::pwm16"

.PP
Definition at line 168 of file bms_datatypes\&.h\&.
.PP
Referenced by bms_setPwm(), and send_ad68_ui()\&.
.SS "uint32_t ad68_pwmb_t::rsv"

.PP
Definition at line 170 of file bms_datatypes\&.h\&.
.PP
Referenced by send_ad68_ui()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
