.TH "ad68_cfa_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ad68_cfa_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bms_datatypes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBcth\fP:3"
.br
.ti -1c
.RI "uint8_t \fBunused1\fP:4"
.br
.ti -1c
.RI "uint8_t \fBrefon\fP:1"
.br
.ti -1c
.RI "uint8_t \fBflag_d\fP:8"
.br
.ti -1c
.RI "uint8_t \fBunused2\fP:3"
.br
.ti -1c
.RI "uint8_t \fBowa\fP:3"
.br
.ti -1c
.RI "uint8_t \fBowrng\fP:1"
.br
.ti -1c
.RI "uint8_t \fBsoakon\fP:1"
.br
.ti -1c
.RI "uint8_t \fBgpo1to8\fP:8"
.br
.ti -1c
.RI "uint8_t \fBgpo9to10\fP:2"
.br
.ti -1c
.RI "uint8_t \fBunused3\fP:6"
.br
.ti -1c
.RI "uint8_t \fBfc\fP:3"
.br
.ti -1c
.RI "uint8_t \fBcomm_bk\fP:1"
.br
.ti -1c
.RI "uint8_t \fBmute_st\fP:1"
.br
.ti -1c
.RI "uint8_t \fBsnap_st\fP:1"
.br
.ti -1c
.RI "uint8_t \fBunused4\fP:2"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 96 of file bms_datatypes\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t ad68_cfa_t::comm_bk"

.PP
Definition at line 115 of file bms_datatypes\&.h\&.
.PP
Referenced by send_ad68_ui()\&.
.SS "uint8_t ad68_cfa_t::cth"

.PP
Definition at line 98 of file bms_datatypes\&.h\&.
.PP
Referenced by send_ad68_ui()\&.
.SS "uint8_t ad68_cfa_t::fc"

.PP
Definition at line 114 of file bms_datatypes\&.h\&.
.PP
Referenced by send_ad68_ui()\&.
.SS "uint8_t ad68_cfa_t::flag_d"

.PP
Definition at line 102 of file bms_datatypes\&.h\&.
.PP
Referenced by send_ad68_ui()\&.
.SS "uint8_t ad68_cfa_t::gpo1to8"

.PP
Definition at line 109 of file bms_datatypes\&.h\&.
.PP
Referenced by bms68_setGpo45(), and send_ad68_ui()\&.
.SS "uint8_t ad68_cfa_t::gpo9to10"

.PP
Definition at line 111 of file bms_datatypes\&.h\&.
.PP
Referenced by send_ad68_ui()\&.
.SS "uint8_t ad68_cfa_t::mute_st"

.PP
Definition at line 116 of file bms_datatypes\&.h\&.
.PP
Referenced by send_ad68_ui()\&.
.SS "uint8_t ad68_cfa_t::owa"

.PP
Definition at line 105 of file bms_datatypes\&.h\&.
.PP
Referenced by send_ad68_ui()\&.
.SS "uint8_t ad68_cfa_t::owrng"

.PP
Definition at line 106 of file bms_datatypes\&.h\&.
.PP
Referenced by send_ad68_ui()\&.
.SS "uint8_t ad68_cfa_t::refon"

.PP
Definition at line 100 of file bms_datatypes\&.h\&.
.PP
Referenced by send_ad68_ui()\&.
.SS "uint8_t ad68_cfa_t::snap_st"

.PP
Definition at line 117 of file bms_datatypes\&.h\&.
.PP
Referenced by send_ad68_ui()\&.
.SS "uint8_t ad68_cfa_t::soakon"

.PP
Definition at line 107 of file bms_datatypes\&.h\&.
.PP
Referenced by send_ad68_ui()\&.
.SS "uint8_t ad68_cfa_t::unused1"

.PP
Definition at line 99 of file bms_datatypes\&.h\&.
.SS "uint8_t ad68_cfa_t::unused2"

.PP
Definition at line 104 of file bms_datatypes\&.h\&.
.SS "uint8_t ad68_cfa_t::unused3"

.PP
Definition at line 112 of file bms_datatypes\&.h\&.
.SS "uint8_t ad68_cfa_t::unused4"

.PP
Definition at line 118 of file bms_datatypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
