.TH "ADAX_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADAX_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bms_cmdlist\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBOW\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBRES0\fP: 2"
.br
.ti -1c
.RI "uint8_t \fBX\fP: 5"
.br
.ti -1c
.RI "uint8_t \fBCH\fP: 4"
.br
.ti -1c
.RI "uint8_t \fBRES1\fP: 2"
.br
.ti -1c
.RI "uint8_t \fBCH4\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBPUP\fP: 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 290 of file bms_cmdlist\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t ADAX_t::CH"

.PP
Definition at line 296 of file bms_cmdlist\&.h\&.
.PP
Referenced by bms_getAuxMeasurement()\&.
.SS "uint8_t ADAX_t::CH4"

.PP
Definition at line 298 of file bms_cmdlist\&.h\&.
.PP
Referenced by bms_getAuxMeasurement()\&.
.SS "uint8_t ADAX_t::OW"

.PP
Definition at line 292 of file bms_cmdlist\&.h\&.
.PP
Referenced by bms_getAuxMeasurement()\&.
.SS "uint8_t ADAX_t::PUP"

.PP
Definition at line 299 of file bms_cmdlist\&.h\&.
.PP
Referenced by bms_getAuxMeasurement()\&.
.SS "uint8_t ADAX_t::RES0"

.PP
Definition at line 293 of file bms_cmdlist\&.h\&.
.SS "uint8_t ADAX_t::RES1"

.PP
Definition at line 297 of file bms_cmdlist\&.h\&.
.SS "uint8_t ADAX_t::X"

.PP
Definition at line 294 of file bms_cmdlist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
