.TH "ADCV_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADCV_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bms_cmdlist\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBRD\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBRES2\fP: 2"
.br
.ti -1c
.RI "uint8_t \fBX\fP: 5"
.br
.ti -1c
.RI "uint8_t \fBOW\fP: 2"
.br
.ti -1c
.RI "uint8_t \fBRSTF\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBRES0\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBDCP\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBRES1\fP: 2"
.br
.ti -1c
.RI "uint8_t \fBCONT\fP: 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 246 of file bms_cmdlist\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t ADCV_t::CONT"

.PP
Definition at line 257 of file bms_cmdlist\&.h\&.
.PP
Referenced by bms_startAdcvCont()\&.
.SS "uint8_t ADCV_t::DCP"

.PP
Definition at line 255 of file bms_cmdlist\&.h\&.
.PP
Referenced by bms_startAdcvCont()\&.
.SS "uint8_t ADCV_t::OW"

.PP
Definition at line 252 of file bms_cmdlist\&.h\&.
.PP
Referenced by bms_startAdcvCont()\&.
.SS "uint8_t ADCV_t::RD"

.PP
Definition at line 248 of file bms_cmdlist\&.h\&.
.PP
Referenced by bms_startAdcvCont()\&.
.SS "uint8_t ADCV_t::RES0"

.PP
Definition at line 254 of file bms_cmdlist\&.h\&.
.SS "uint8_t ADCV_t::RES1"

.PP
Definition at line 256 of file bms_cmdlist\&.h\&.
.SS "uint8_t ADCV_t::RES2"

.PP
Definition at line 249 of file bms_cmdlist\&.h\&.
.SS "uint8_t ADCV_t::RSTF"

.PP
Definition at line 253 of file bms_cmdlist\&.h\&.
.PP
Referenced by bms_startAdcvCont()\&.
.SS "uint8_t ADCV_t::X"

.PP
Definition at line 250 of file bms_cmdlist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
