.TH "ADSV_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADSV_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bms_cmdlist\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBRES2\fP: 3"
.br
.ti -1c
.RI "uint8_t \fBX\fP: 5"
.br
.ti -1c
.RI "uint8_t \fBOW\fP: 2"
.br
.ti -1c
.RI "uint8_t \fBRES0\fP: 2"
.br
.ti -1c
.RI "uint8_t \fBDCP\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBRES1\fP: 2"
.br
.ti -1c
.RI "uint8_t \fBCONT\fP: 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 263 of file bms_cmdlist\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t ADSV_t::CONT"

.PP
Definition at line 272 of file bms_cmdlist\&.h\&.
.PP
Referenced by bms_balancingMeasureVoltage(), and bms_openWireCheck()\&.
.SS "uint8_t ADSV_t::DCP"

.PP
Definition at line 270 of file bms_cmdlist\&.h\&.
.PP
Referenced by bms_balancingMeasureVoltage(), and bms_openWireCheck()\&.
.SS "uint8_t ADSV_t::OW"

.PP
Definition at line 268 of file bms_cmdlist\&.h\&.
.PP
Referenced by bms_balancingMeasureVoltage(), and bms_openWireCheck()\&.
.SS "uint8_t ADSV_t::RES0"

.PP
Definition at line 269 of file bms_cmdlist\&.h\&.
.SS "uint8_t ADSV_t::RES1"

.PP
Definition at line 271 of file bms_cmdlist\&.h\&.
.SS "uint8_t ADSV_t::RES2"

.PP
Definition at line 265 of file bms_cmdlist\&.h\&.
.SS "uint8_t ADSV_t::X"

.PP
Definition at line 266 of file bms_cmdlist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
