.TH "ams_slave_12_voltage_id_1_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams_slave_12_voltage_id_1_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBcell_voltage_133\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_134\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_135\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_136\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Slave_12_Voltage_ID_1\&.
.PP
All signal values are as on the CAN bus\&. 
.PP
Definition at line 3921 of file ams\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ams_slave_12_voltage_id_1_t::cell_voltage_133"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 3927 of file ams\&.h\&.
.PP
Referenced by ams_slave_12_voltage_id_1_pack(), ams_slave_12_voltage_id_1_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_12_voltage_id_1_t::cell_voltage_134"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 3934 of file ams\&.h\&.
.PP
Referenced by ams_slave_12_voltage_id_1_pack(), ams_slave_12_voltage_id_1_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_12_voltage_id_1_t::cell_voltage_135"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 3941 of file ams\&.h\&.
.PP
Referenced by ams_slave_12_voltage_id_1_pack(), ams_slave_12_voltage_id_1_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_12_voltage_id_1_t::cell_voltage_136"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 3948 of file ams\&.h\&.
.PP
Referenced by ams_slave_12_voltage_id_1_pack(), ams_slave_12_voltage_id_1_unpack(), and CAN_Send_AD68_Voltages_Module()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
