.TH "ams_start_pre_charge_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams_start_pre_charge_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBprecharge_request\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Start_PreCharge\&.
.PP
All signal values are as on the CAN bus\&. 
.PP
Definition at line 4201 of file ams\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t ams_start_pre_charge_t::precharge_request"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 4207 of file ams\&.h\&.
.PP
Referenced by ams_start_pre_charge_pack(), ams_start_pre_charge_unpack(), and PreCharge_CAN_Rx()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
