.TH "ams_slave_02_temperature_id_2_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams_slave_02_temperature_id_2_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBtemperature_value_17\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_18\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_19\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_20\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Slave_02_Temperature_ID_2\&.
.PP
All signal values are as on the CAN bus\&. 
.PP
Definition at line 1261 of file ams\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ams_slave_02_temperature_id_2_t::temperature_value_17"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1267 of file ams\&.h\&.
.PP
Referenced by ams_slave_02_temperature_id_2_pack(), ams_slave_02_temperature_id_2_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_02_temperature_id_2_t::temperature_value_18"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1274 of file ams\&.h\&.
.PP
Referenced by ams_slave_02_temperature_id_2_pack(), ams_slave_02_temperature_id_2_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_02_temperature_id_2_t::temperature_value_19"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1281 of file ams\&.h\&.
.PP
Referenced by ams_slave_02_temperature_id_2_pack(), ams_slave_02_temperature_id_2_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_02_temperature_id_2_t::temperature_value_20"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1288 of file ams\&.h\&.
.PP
Referenced by ams_slave_02_temperature_id_2_pack(), ams_slave_02_temperature_id_2_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
