.TH "ams_slave_01_msc_id_2_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams_slave_01_msc_id_2_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBmodule_voltage_delta\fP"
.br
.ti -1c
.RI "uint16_t \fBmodule_ic_voltage\fP"
.br
.ti -1c
.RI "uint8_t \fBmodule_open_wire\fP"
.br
.ti -1c
.RI "uint16_t \fBmodule_ic_temperature\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Slave_01_MSC_ID_2\&.
.PP
All signal values are as on the CAN bus\&. 
.PP
Definition at line 1086 of file ams\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ams_slave_01_msc_id_2_t::module_ic_temperature"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1113 of file ams\&.h\&.
.PP
Referenced by ams_slave_01_msc_id_2_pack(), and ams_slave_01_msc_id_2_unpack()\&.
.SS "uint16_t ams_slave_01_msc_id_2_t::module_ic_voltage"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1099 of file ams\&.h\&.
.PP
Referenced by ams_slave_01_msc_id_2_pack(), and ams_slave_01_msc_id_2_unpack()\&.
.SS "uint8_t ams_slave_01_msc_id_2_t::module_open_wire"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1106 of file ams\&.h\&.
.PP
Referenced by ams_slave_01_msc_id_2_pack(), and ams_slave_01_msc_id_2_unpack()\&.
.SS "uint16_t ams_slave_01_msc_id_2_t::module_voltage_delta"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1092 of file ams\&.h\&.
.PP
Referenced by ams_slave_01_msc_id_2_pack(), and ams_slave_01_msc_id_2_unpack()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
