.TH "ams_slave_07_msc_id_1_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams_slave_07_msc_id_1_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBmodule_voltage_sum\fP"
.br
.ti -1c
.RI "uint16_t \fBmodule_voltage_avg\fP"
.br
.ti -1c
.RI "uint16_t \fBmodule_voltage_min\fP"
.br
.ti -1c
.RI "uint16_t \fBmodule_voltage_max\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Slave_07_MSC_ID_1\&.
.PP
All signal values are as on the CAN bus\&. 
.PP
Definition at line 2731 of file ams\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ams_slave_07_msc_id_1_t::module_voltage_avg"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 2744 of file ams\&.h\&.
.PP
Referenced by ams_slave_07_msc_id_1_pack(), and ams_slave_07_msc_id_1_unpack()\&.
.SS "uint16_t ams_slave_07_msc_id_1_t::module_voltage_max"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 2758 of file ams\&.h\&.
.PP
Referenced by ams_slave_07_msc_id_1_pack(), and ams_slave_07_msc_id_1_unpack()\&.
.SS "uint16_t ams_slave_07_msc_id_1_t::module_voltage_min"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 2751 of file ams\&.h\&.
.PP
Referenced by ams_slave_07_msc_id_1_pack(), and ams_slave_07_msc_id_1_unpack()\&.
.SS "uint16_t ams_slave_07_msc_id_1_t::module_voltage_sum"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 2737 of file ams\&.h\&.
.PP
Referenced by ams_slave_07_msc_id_1_pack(), and ams_slave_07_msc_id_1_unpack()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
