.TH "ams_slave_02_voltage_id_3_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams_slave_02_voltage_id_3_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBcell_voltage_21\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_22\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_23\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_24\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Slave_02_Voltage_ID_3\&.
.PP
All signal values are as on the CAN bus\&. 
.PP
Definition at line 1191 of file ams\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ams_slave_02_voltage_id_3_t::cell_voltage_21"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1197 of file ams\&.h\&.
.PP
Referenced by ams_slave_02_voltage_id_3_pack(), ams_slave_02_voltage_id_3_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_02_voltage_id_3_t::cell_voltage_22"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1204 of file ams\&.h\&.
.PP
Referenced by ams_slave_02_voltage_id_3_pack(), ams_slave_02_voltage_id_3_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_02_voltage_id_3_t::cell_voltage_23"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1211 of file ams\&.h\&.
.PP
Referenced by ams_slave_02_voltage_id_3_pack(), ams_slave_02_voltage_id_3_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_02_voltage_id_3_t::cell_voltage_24"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1218 of file ams\&.h\&.
.PP
Referenced by ams_slave_02_voltage_id_3_pack(), ams_slave_02_voltage_id_3_unpack(), and CAN_Send_AD68_Voltages_Module()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
