.TH "ams_slave_04_temperature_id_2_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams_slave_04_temperature_id_2_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBtemperature_value_41\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_42\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_43\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_44\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Slave_04_Temperature_ID_2\&.
.PP
All signal values are as on the CAN bus\&. 
.PP
Definition at line 1821 of file ams\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ams_slave_04_temperature_id_2_t::temperature_value_41"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1827 of file ams\&.h\&.
.PP
Referenced by ams_slave_04_temperature_id_2_pack(), ams_slave_04_temperature_id_2_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_04_temperature_id_2_t::temperature_value_42"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1834 of file ams\&.h\&.
.PP
Referenced by ams_slave_04_temperature_id_2_pack(), ams_slave_04_temperature_id_2_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_04_temperature_id_2_t::temperature_value_43"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1841 of file ams\&.h\&.
.PP
Referenced by ams_slave_04_temperature_id_2_pack(), ams_slave_04_temperature_id_2_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_04_temperature_id_2_t::temperature_value_44"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1848 of file ams\&.h\&.
.PP
Referenced by ams_slave_04_temperature_id_2_pack(), ams_slave_04_temperature_id_2_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
