.TH "ams_slave_05_temperature_id_1_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams_slave_05_temperature_id_1_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBtemperature_value_49\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_50\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_51\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_52\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Slave_05_Temperature_ID_1\&.
.PP
All signal values are as on the CAN bus\&. 
.PP
Definition at line 2066 of file ams\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ams_slave_05_temperature_id_1_t::temperature_value_49"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 2072 of file ams\&.h\&.
.PP
Referenced by ams_slave_05_temperature_id_1_pack(), ams_slave_05_temperature_id_1_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_05_temperature_id_1_t::temperature_value_50"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 2079 of file ams\&.h\&.
.PP
Referenced by ams_slave_05_temperature_id_1_pack(), ams_slave_05_temperature_id_1_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_05_temperature_id_1_t::temperature_value_51"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 2086 of file ams\&.h\&.
.PP
Referenced by ams_slave_05_temperature_id_1_pack(), ams_slave_05_temperature_id_1_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_05_temperature_id_1_t::temperature_value_52"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 2093 of file ams\&.h\&.
.PP
Referenced by ams_slave_05_temperature_id_1_pack(), ams_slave_05_temperature_id_1_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
