.TH "ams_slave_03_temperature_id_2_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams_slave_03_temperature_id_2_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBtemperature_value_29\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_30\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_31\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_32\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Slave_03_Temperature_ID_2\&.
.PP
All signal values are as on the CAN bus\&. 
.PP
Definition at line 1541 of file ams\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ams_slave_03_temperature_id_2_t::temperature_value_29"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1547 of file ams\&.h\&.
.PP
Referenced by ams_slave_03_temperature_id_2_pack(), ams_slave_03_temperature_id_2_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_03_temperature_id_2_t::temperature_value_30"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1554 of file ams\&.h\&.
.PP
Referenced by ams_slave_03_temperature_id_2_pack(), ams_slave_03_temperature_id_2_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_03_temperature_id_2_t::temperature_value_31"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1561 of file ams\&.h\&.
.PP
Referenced by ams_slave_03_temperature_id_2_pack(), ams_slave_03_temperature_id_2_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_03_temperature_id_2_t::temperature_value_32"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1568 of file ams\&.h\&.
.PP
Referenced by ams_slave_03_temperature_id_2_pack(), ams_slave_03_temperature_id_2_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
