.TH "ams_slave_01_voltage_id_2_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams_slave_01_voltage_id_2_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBcell_voltage_5\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_6\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_7\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_8\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Slave_01_Voltage_ID_2\&.
.PP
All signal values are as on the CAN bus\&. 
.PP
Definition at line 876 of file ams\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ams_slave_01_voltage_id_2_t::cell_voltage_5"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 882 of file ams\&.h\&.
.PP
Referenced by ams_slave_01_voltage_id_2_pack(), ams_slave_01_voltage_id_2_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_01_voltage_id_2_t::cell_voltage_6"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 889 of file ams\&.h\&.
.PP
Referenced by ams_slave_01_voltage_id_2_pack(), ams_slave_01_voltage_id_2_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_01_voltage_id_2_t::cell_voltage_7"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 896 of file ams\&.h\&.
.PP
Referenced by ams_slave_01_voltage_id_2_pack(), ams_slave_01_voltage_id_2_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_01_voltage_id_2_t::cell_voltage_8"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 903 of file ams\&.h\&.
.PP
Referenced by ams_slave_01_voltage_id_2_pack(), ams_slave_01_voltage_id_2_unpack(), and CAN_Send_AD68_Voltages_Module()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
