.TH "ams_slave_06_voltage_id_1_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams_slave_06_voltage_id_1_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBcell_voltage_61\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_62\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_63\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_64\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Slave_06_Voltage_ID_1\&.
.PP
All signal values are as on the CAN bus\&. 
.PP
Definition at line 2241 of file ams\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ams_slave_06_voltage_id_1_t::cell_voltage_61"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 2247 of file ams\&.h\&.
.PP
Referenced by ams_slave_06_voltage_id_1_pack(), ams_slave_06_voltage_id_1_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_06_voltage_id_1_t::cell_voltage_62"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 2254 of file ams\&.h\&.
.PP
Referenced by ams_slave_06_voltage_id_1_pack(), ams_slave_06_voltage_id_1_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_06_voltage_id_1_t::cell_voltage_63"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 2261 of file ams\&.h\&.
.PP
Referenced by ams_slave_06_voltage_id_1_pack(), ams_slave_06_voltage_id_1_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_06_voltage_id_1_t::cell_voltage_64"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 2268 of file ams\&.h\&.
.PP
Referenced by ams_slave_06_voltage_id_1_pack(), ams_slave_06_voltage_id_1_unpack(), and CAN_Send_AD68_Voltages_Module()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
