.TH "ams_slave_08_temperature_id_2_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams_slave_08_temperature_id_2_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBtemperature_value_89\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_90\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_91\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_92\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Slave_08_Temperature_ID_2\&.
.PP
All signal values are as on the CAN bus\&. 
.PP
Definition at line 2941 of file ams\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ams_slave_08_temperature_id_2_t::temperature_value_89"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 2947 of file ams\&.h\&.
.PP
Referenced by ams_slave_08_temperature_id_2_pack(), ams_slave_08_temperature_id_2_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_08_temperature_id_2_t::temperature_value_90"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 2954 of file ams\&.h\&.
.PP
Referenced by ams_slave_08_temperature_id_2_pack(), ams_slave_08_temperature_id_2_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_08_temperature_id_2_t::temperature_value_91"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 2961 of file ams\&.h\&.
.PP
Referenced by ams_slave_08_temperature_id_2_pack(), ams_slave_08_temperature_id_2_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_08_temperature_id_2_t::temperature_value_92"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 2968 of file ams\&.h\&.
.PP
Referenced by ams_slave_08_temperature_id_2_pack(), ams_slave_08_temperature_id_2_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
