.TH "ams_slave_04_temperature_id_3_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams_slave_04_temperature_id_3_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBtemperature_value_45\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_46\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_47\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_48\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Slave_04_Temperature_ID_3\&.
.PP
All signal values are as on the CAN bus\&. 
.PP
Definition at line 1856 of file ams\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ams_slave_04_temperature_id_3_t::temperature_value_45"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1862 of file ams\&.h\&.
.PP
Referenced by ams_slave_04_temperature_id_3_pack(), ams_slave_04_temperature_id_3_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_04_temperature_id_3_t::temperature_value_46"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1869 of file ams\&.h\&.
.PP
Referenced by ams_slave_04_temperature_id_3_pack(), ams_slave_04_temperature_id_3_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_04_temperature_id_3_t::temperature_value_47"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1876 of file ams\&.h\&.
.PP
Referenced by ams_slave_04_temperature_id_3_pack(), ams_slave_04_temperature_id_3_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_04_temperature_id_3_t::temperature_value_48"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1883 of file ams\&.h\&.
.PP
Referenced by ams_slave_04_temperature_id_3_pack(), ams_slave_04_temperature_id_3_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
