.TH "ams_slave_10_voltage_id_2_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams_slave_10_voltage_id_2_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBcell_voltage_113\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_114\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_115\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_116\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Slave_10_Voltage_ID_2\&.
.PP
All signal values are as on the CAN bus\&. 
.PP
Definition at line 3396 of file ams\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ams_slave_10_voltage_id_2_t::cell_voltage_113"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 3402 of file ams\&.h\&.
.PP
Referenced by ams_slave_10_voltage_id_2_pack(), ams_slave_10_voltage_id_2_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_10_voltage_id_2_t::cell_voltage_114"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 3409 of file ams\&.h\&.
.PP
Referenced by ams_slave_10_voltage_id_2_pack(), ams_slave_10_voltage_id_2_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_10_voltage_id_2_t::cell_voltage_115"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 3416 of file ams\&.h\&.
.PP
Referenced by ams_slave_10_voltage_id_2_pack(), ams_slave_10_voltage_id_2_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_10_voltage_id_2_t::cell_voltage_116"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 3423 of file ams\&.h\&.
.PP
Referenced by ams_slave_10_voltage_id_2_pack(), ams_slave_10_voltage_id_2_unpack(), and CAN_Send_AD68_Voltages_Module()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
