.TH "ams_slave_02_voltage_id_2_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams_slave_02_voltage_id_2_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBcell_voltage_17\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_18\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_19\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_20\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Slave_02_Voltage_ID_2\&.
.PP
All signal values are as on the CAN bus\&. 
.PP
Definition at line 1156 of file ams\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ams_slave_02_voltage_id_2_t::cell_voltage_17"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1162 of file ams\&.h\&.
.PP
Referenced by ams_slave_02_voltage_id_2_pack(), ams_slave_02_voltage_id_2_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_02_voltage_id_2_t::cell_voltage_18"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1169 of file ams\&.h\&.
.PP
Referenced by ams_slave_02_voltage_id_2_pack(), ams_slave_02_voltage_id_2_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_02_voltage_id_2_t::cell_voltage_19"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1176 of file ams\&.h\&.
.PP
Referenced by ams_slave_02_voltage_id_2_pack(), ams_slave_02_voltage_id_2_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_02_voltage_id_2_t::cell_voltage_20"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1183 of file ams\&.h\&.
.PP
Referenced by ams_slave_02_voltage_id_2_pack(), ams_slave_02_voltage_id_2_unpack(), and CAN_Send_AD68_Voltages_Module()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
