.TH "ams_slave_03_voltage_id_2_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams_slave_03_voltage_id_2_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBcell_voltage_29\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_30\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_31\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_32\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Slave_03_Voltage_ID_2\&.
.PP
All signal values are as on the CAN bus\&. 
.PP
Definition at line 1436 of file ams\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ams_slave_03_voltage_id_2_t::cell_voltage_29"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1442 of file ams\&.h\&.
.PP
Referenced by ams_slave_03_voltage_id_2_pack(), ams_slave_03_voltage_id_2_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_03_voltage_id_2_t::cell_voltage_30"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1449 of file ams\&.h\&.
.PP
Referenced by ams_slave_03_voltage_id_2_pack(), ams_slave_03_voltage_id_2_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_03_voltage_id_2_t::cell_voltage_31"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1456 of file ams\&.h\&.
.PP
Referenced by ams_slave_03_voltage_id_2_pack(), ams_slave_03_voltage_id_2_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_03_voltage_id_2_t::cell_voltage_32"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1463 of file ams\&.h\&.
.PP
Referenced by ams_slave_03_voltage_id_2_pack(), ams_slave_03_voltage_id_2_unpack(), and CAN_Send_AD68_Voltages_Module()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
