.TH "ams_slave_04_voltage_id_1_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams_slave_04_voltage_id_1_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBcell_voltage_37\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_38\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_39\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_40\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Slave_04_Voltage_ID_1\&.
.PP
All signal values are as on the CAN bus\&. 
.PP
Definition at line 1681 of file ams\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ams_slave_04_voltage_id_1_t::cell_voltage_37"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1687 of file ams\&.h\&.
.PP
Referenced by ams_slave_04_voltage_id_1_pack(), ams_slave_04_voltage_id_1_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_04_voltage_id_1_t::cell_voltage_38"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1694 of file ams\&.h\&.
.PP
Referenced by ams_slave_04_voltage_id_1_pack(), ams_slave_04_voltage_id_1_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_04_voltage_id_1_t::cell_voltage_39"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1701 of file ams\&.h\&.
.PP
Referenced by ams_slave_04_voltage_id_1_pack(), ams_slave_04_voltage_id_1_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_04_voltage_id_1_t::cell_voltage_40"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1708 of file ams\&.h\&.
.PP
Referenced by ams_slave_04_voltage_id_1_pack(), ams_slave_04_voltage_id_1_unpack(), and CAN_Send_AD68_Voltages_Module()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
