.TH "ams_slave_02_temperature_id_3_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams_slave_02_temperature_id_3_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBtemperature_value_21\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_22\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_23\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_24\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Slave_02_Temperature_ID_3\&.
.PP
All signal values are as on the CAN bus\&. 
.PP
Definition at line 1296 of file ams\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ams_slave_02_temperature_id_3_t::temperature_value_21"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1302 of file ams\&.h\&.
.PP
Referenced by ams_slave_02_temperature_id_3_pack(), ams_slave_02_temperature_id_3_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_02_temperature_id_3_t::temperature_value_22"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1309 of file ams\&.h\&.
.PP
Referenced by ams_slave_02_temperature_id_3_pack(), ams_slave_02_temperature_id_3_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_02_temperature_id_3_t::temperature_value_23"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1316 of file ams\&.h\&.
.PP
Referenced by ams_slave_02_temperature_id_3_pack(), ams_slave_02_temperature_id_3_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_02_temperature_id_3_t::temperature_value_24"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1323 of file ams\&.h\&.
.PP
Referenced by ams_slave_02_temperature_id_3_pack(), ams_slave_02_temperature_id_3_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
