.TH "ams_slave_04_temperature_id_1_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams_slave_04_temperature_id_1_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBtemperature_value_37\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_38\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_39\fP"
.br
.ti -1c
.RI "uint16_t \fBtemperature_value_40\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Slave_04_Temperature_ID_1\&.
.PP
All signal values are as on the CAN bus\&. 
.PP
Definition at line 1786 of file ams\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ams_slave_04_temperature_id_1_t::temperature_value_37"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1792 of file ams\&.h\&.
.PP
Referenced by ams_slave_04_temperature_id_1_pack(), ams_slave_04_temperature_id_1_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_04_temperature_id_1_t::temperature_value_38"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1799 of file ams\&.h\&.
.PP
Referenced by ams_slave_04_temperature_id_1_pack(), ams_slave_04_temperature_id_1_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_04_temperature_id_1_t::temperature_value_39"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1806 of file ams\&.h\&.
.PP
Referenced by ams_slave_04_temperature_id_1_pack(), ams_slave_04_temperature_id_1_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.
.SS "uint16_t ams_slave_04_temperature_id_1_t::temperature_value_40"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1813 of file ams\&.h\&.
.PP
Referenced by ams_slave_04_temperature_id_1_pack(), ams_slave_04_temperature_id_1_unpack(), and CAN_Send_AD68_Temperatures_Module()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
