.TH "ams_slave_05_voltage_id_1_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams_slave_05_voltage_id_1_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ams\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBcell_voltage_49\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_50\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_51\fP"
.br
.ti -1c
.RI "uint16_t \fBcell_voltage_52\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Signals in message Slave_05_Voltage_ID_1\&.
.PP
All signal values are as on the CAN bus\&. 
.PP
Definition at line 1961 of file ams\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t ams_slave_05_voltage_id_1_t::cell_voltage_49"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1967 of file ams\&.h\&.
.PP
Referenced by ams_slave_05_voltage_id_1_pack(), ams_slave_05_voltage_id_1_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_05_voltage_id_1_t::cell_voltage_50"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1974 of file ams\&.h\&.
.PP
Referenced by ams_slave_05_voltage_id_1_pack(), ams_slave_05_voltage_id_1_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_05_voltage_id_1_t::cell_voltage_51"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1981 of file ams\&.h\&.
.PP
Referenced by ams_slave_05_voltage_id_1_pack(), ams_slave_05_voltage_id_1_unpack(), and CAN_Send_AD68_Voltages_Module()\&.
.SS "uint16_t ams_slave_05_voltage_id_1_t::cell_voltage_52"
Range: - Scale: 1 Offset: 0 
.PP
Definition at line 1988 of file ams\&.h\&.
.PP
Referenced by ams_slave_05_voltage_id_1_pack(), ams_slave_05_voltage_id_1_unpack(), and CAN_Send_AD68_Voltages_Module()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
