.TH "Core/Inc/bms_datatypes.h" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Inc/bms_datatypes.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stdint\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBad29_cfa_t\fP"
.br
.ti -1c
.RI "struct \fBad29_cfb_t\fP"
.br
.ti -1c
.RI "struct \fBad68_cfa_t\fP"
.br
.ti -1c
.RI "struct \fBad68_cfb_t\fP"
.br
.ti -1c
.RI "struct \fBad68_pwma_t\fP"
.br
.ti -1c
.RI "struct \fBad68_pwmb_t\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
