.TH "Core/Inc/bms_cmdlist.h" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Inc/bms_cmdlist.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stdint\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBADCV_t\fP"
.br
.ti -1c
.RI "struct \fBADSV_t\fP"
.br
.ti -1c
.RI "struct \fBADAX2_t\fP"
.br
.ti -1c
.RI "struct \fBADAX_t\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint8_t \fBWRCFGA\fP [2]"
.br
.RI "----------------------- BOTH 2950 AND 6830 ------------------------------- /// "
.ti -1c
.RI "uint8_t \fBWRCFGB\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDCFGA\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDCFGB\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDI\fP [2]"
.br
.RI "----------------------- 2950 ONLY ------------------------------- /// "
.ti -1c
.RI "uint8_t \fBRDVB\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDIVB1\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDV1A\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDV1B\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDV1C\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDV1D\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDV2A\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDV2B\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDV2C\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDV2D\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDV2E\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDOC\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDALLI\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDALLA\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDALLC\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDALLV\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDALLR\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDALLX\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDIACC\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDVBACC\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDIVB1ACC\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDALLB\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDCALL\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDSTAT\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDFLAG\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDFLAGERR\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDASALL\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBWRPWM\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDPWM\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBWRPWM2\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDPWM2\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBCLRI\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBCLRA\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBCLRO\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBCLRC\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBCLRVX\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBCLRFLAG\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBPLADC\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBPLI1\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBPLI2\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBPLV\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBPLX\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBWRCOMM\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDCOMM\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBSTCOMM\fP [13]"
.br
.ti -1c
.RI "uint8_t \fBRDSID\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRSTCC\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBSNAP\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBUNSNAP\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBSRST\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRSTATD\fP [4]"
.br
.ti -1c
.RI "uint8_t \fBRFLAG\fP [4]"
.br
.ti -1c
.RI "uint8_t \fBsRDI\fP [4]"
.br
.ti -1c
.RI "uint8_t \fBsRSTATA\fP [4]"
.br
.ti -1c
.RI "uint8_t \fBsRDVA\fP [4]"
.br
.ti -1c
.RI "uint8_t \fBsRDVB\fP [4]"
.br
.ti -1c
.RI "uint8_t \fBsRDVC\fP [4]"
.br
.ti -1c
.RI "uint8_t \fBsRDVD\fP [4]"
.br
.ti -1c
.RI "uint8_t \fBsRDIAV\fP [4]"
.br
.ti -1c
.RI "uint8_t \fBsRDVBAT\fP [4]"
.br
.ti -1c
.RI "uint8_t \fBsADI1\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBsADX\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBTM_48\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDXA\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDXB\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDXC\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDSTATA\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDSTATB\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDSTATC\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDSTATCERR\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDSTATD\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDSTATE\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDAUXC\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDAUXD\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDRAXC\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDRAXD\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDCVA\fP [2]"
.br
.RI "----------------------- 6830 ONLY ------------------------------- /// "
.ti -1c
.RI "uint8_t \fBRDCVB\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDCVC\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDCVD\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDCVE\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDCVF\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDCVALL\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDACA\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDACB\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDACC\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDACD\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDACE\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDACF\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDACALL\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDSVA\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDSVB\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDSVC\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDSVD\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDSVE\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDSVF\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDSALL\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDCSALL\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDACSALL\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDFCA\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDFCB\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDFCC\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDFCD\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDFCE\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDFCF\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDFCALL\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDAUXA\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDAUXB\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDRAXA\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDRAXB\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBWRPWM1\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBRDPWM1\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBCLRCELL\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBCLRAUX\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBCLRSPIN\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBCLRFC\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBCLOVUV\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBPLAUT\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBPLCADC\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBPLSADC\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBPLAUX1\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBPLAUX2\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBDIAGN\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBMUTE\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBUNMUTE\fP [2]"
.br
.ti -1c
.RI "const \fBADCV_t\fP \fBADCV_default\fP"
.br
.ti -1c
.RI "\fBADCV_t\fP \fBADCV\fP"
.br
.ti -1c
.RI "const \fBADSV_t\fP \fBADSV_default\fP"
.br
.ti -1c
.RI "\fBADSV_t\fP \fBADSV\fP"
.br
.ti -1c
.RI "const \fBADAX2_t\fP \fBADAX2_default\fP"
.br
.ti -1c
.RI "\fBADAX2_t\fP \fBADAX2\fP"
.br
.ti -1c
.RI "const \fBADAX_t\fP \fBADAX_default\fP"
.br
.ti -1c
.RI "\fBADAX_t\fP \fBADAX\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBADAX_t\fP ADAX"

.PP
Definition at line 310 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_getAuxMeasurement()\&.
.SS "\fBADAX2_t\fP ADAX2"

.PP
Definition at line 295 of file bms_cmdlist\&.c\&.
.SS "const \fBADAX2_t\fP ADAX2_default"

.PP
Definition at line 289 of file bms_cmdlist\&.c\&.
.SS "const \fBADAX_t\fP ADAX_default"

.PP
Definition at line 298 of file bms_cmdlist\&.c\&.
.SS "\fBADCV_t\fP ADCV"

.PP
Definition at line 270 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_startAdcvCont()\&.
.SS "const \fBADCV_t\fP ADCV_default"

.PP
Definition at line 256 of file bms_cmdlist\&.c\&.
.SS "\fBADSV_t\fP ADSV"

.PP
Definition at line 285 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_balancingMeasureVoltage(), and bms_openWireCheck()\&.
.SS "const \fBADSV_t\fP ADSV_default"

.PP
Definition at line 273 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLOVUV[2]"

.PP
Definition at line 234 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLRA[2]"

.PP
Definition at line 126 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLRAUX[2]"

.PP
Definition at line 231 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLRC[2]"

.PP
Definition at line 128 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLRCELL[2]"

.PP
Definition at line 230 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLRFC[2]"

.PP
Definition at line 233 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLRFLAG"

.PP
Definition at line 149 of file bms_cmdlist\&.h\&.
.SS "uint8_t CLRI[2]"

.PP
Definition at line 125 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLRO[2]"

.PP
Definition at line 127 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLRSPIN[2]"

.PP
Definition at line 232 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLRVX[2]"

.PP
Definition at line 129 of file bms_cmdlist\&.c\&.
.SS "uint8_t DIAGN[2]"

.PP
Definition at line 244 of file bms_cmdlist\&.c\&.
.SS "uint8_t MUTE[2]"

.PP
Definition at line 247 of file bms_cmdlist\&.c\&.
.SS "uint8_t PLADC"
GPIOs Comm commands 
.PP
Definition at line 152 of file bms_cmdlist\&.h\&.
.SS "uint8_t PLAUT[2]"

.PP
Definition at line 237 of file bms_cmdlist\&.c\&.
.SS "uint8_t PLAUX1[2]"

.PP
Definition at line 240 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_getAuxMeasurement()\&.
.SS "uint8_t PLAUX2[2]"

.PP
Definition at line 241 of file bms_cmdlist\&.c\&.
.SS "uint8_t PLCADC[2]"

.PP
Definition at line 238 of file bms_cmdlist\&.c\&.
.SS "uint8_t PLI1[2]"

.PP
Definition at line 135 of file bms_cmdlist\&.c\&.
.SS "uint8_t PLI2[2]"

.PP
Definition at line 136 of file bms_cmdlist\&.c\&.
.SS "uint8_t PLSADC[2]"

.PP
Definition at line 239 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_balancingMeasureVoltage()\&.
.SS "uint8_t PLV[2]"

.PP
Definition at line 137 of file bms_cmdlist\&.c\&.
.SS "uint8_t PLX[2]"

.PP
Definition at line 138 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDACA[2]"

.PP
Definition at line 185 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readAvgCellVoltage()\&.
.SS "uint8_t RDACALL[2]"

.PP
Definition at line 191 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDACB[2]"

.PP
Definition at line 186 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readAvgCellVoltage()\&.
.SS "uint8_t RDACC[2]"

.PP
Definition at line 187 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readAvgCellVoltage()\&.
.SS "uint8_t RDACD[2]"

.PP
Definition at line 188 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readAvgCellVoltage()\&.
.SS "uint8_t RDACE[2]"

.PP
Definition at line 189 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readAvgCellVoltage()\&.
.SS "uint8_t RDACF[2]"

.PP
Definition at line 190 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readAvgCellVoltage()\&.
.SS "uint8_t RDACSALL[2]"

.PP
Definition at line 204 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDALLA[2]"

.PP
Definition at line 103 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDALLB[2]"

.SS "uint8_t RDALLC[2]"

.PP
Definition at line 106 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDALLI[2]"

.PP
Definition at line 100 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDALLR[2]"

.PP
Definition at line 112 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDALLV[2]"

.PP
Definition at line 109 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDALLX[2]"

.PP
Definition at line 115 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDASALL"
Reserved Read Commands - 2950 
.PP
Definition at line 136 of file bms_cmdlist\&.h\&.
.SS "uint8_t RDAUXA[2]"

.PP
Definition at line 216 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_getAuxVoltage()\&.
.SS "uint8_t RDAUXB[2]"

.PP
Definition at line 217 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_getAuxVoltage()\&.
.SS "uint8_t RDAUXC[2]"

.PP
Definition at line 27 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_getAuxVoltage()\&.
.SS "uint8_t RDAUXD[2]"
Reserved Read Commands - 2950 
.PP
Definition at line 28 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_getAuxVoltage()\&.
.SS "uint8_t RDCALL[2]"

.SS "uint8_t RDCFGA"

.PP
Definition at line 124 of file bms_cmdlist\&.h\&.
.PP
Referenced by bms_readConfigA()\&.
.SS "uint8_t RDCFGB"
Read status registers 
.PP
Definition at line 125 of file bms_cmdlist\&.h\&.
.PP
Referenced by bms_readConfigB()\&.
.SS "uint8_t RDCOMM"
command + dummy data for 72 clock cycles 
.PP
Definition at line 156 of file bms_cmdlist\&.h\&.
.SS "uint8_t RDCSALL[2]"

.PP
Definition at line 203 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDCVA[2]"

.PP
----------------------- 6830 ONLY ------------------------------- /// 
.PP
Definition at line 176 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDCVALL[2]"

.PP
Definition at line 182 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDCVB[2]"

.PP
Definition at line 177 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDCVC[2]"

.PP
Definition at line 178 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDCVD[2]"

.PP
Definition at line 179 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDCVE[2]"

.PP
Definition at line 180 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDCVF[2]"

.PP
Definition at line 181 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDFCA[2]"

.PP
Definition at line 207 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDFCALL[2]"

.PP
Definition at line 213 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDFCB[2]"

.PP
Definition at line 208 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDFCC[2]"

.PP
Definition at line 209 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDFCD[2]"

.PP
Definition at line 210 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDFCE[2]"

.PP
Definition at line 211 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDFCF[2]"

.PP
Definition at line 212 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDFLAG[2]"

.PP
Definition at line 90 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDFLAGERR[2]"

.PP
Definition at line 91 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDI[2]"

.PP
----------------------- 2950 ONLY ------------------------------- /// 
.PP
Definition at line 65 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDIACC[2]"

.PP
Definition at line 68 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDIVB1[2]"

.PP
Definition at line 67 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDIVB1ACC[2]"

.PP
Definition at line 70 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDOC[2]"

.PP
Definition at line 73 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDPWM[2]"

.SS "uint8_t RDPWM1[2]"

.PP
Definition at line 225 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDPWM2"

.PP
Definition at line 218 of file bms_cmdlist\&.h\&.
.SS "uint8_t RDRAXA[2]"

.PP
Definition at line 220 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDRAXB[2]"

.PP
Definition at line 221 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDRAXC[2]"

.PP
Definition at line 32 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDRAXD[2]"

.PP
Definition at line 33 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDSALL[2]"

.PP
Definition at line 200 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDSID"

.PP
Definition at line 161 of file bms_cmdlist\&.h\&.
.PP
Referenced by bms_readSid()\&.
.SS "uint8_t RDSTAT[2]"

.PP
Definition at line 87 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDSTATA[2]"

.PP
Definition at line 15 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_getAuxVoltage()\&.
.SS "uint8_t RDSTATB[2]"

.PP
Definition at line 16 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDSTATC[2]"

.PP
Definition at line 17 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDSTATCERR[2]"

.PP
Definition at line 18 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDSTATD[2]"

.PP
Definition at line 19 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDSTATE[2]"

.PP
Definition at line 20 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDSVA[2]"

.PP
Definition at line 194 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readSVoltage()\&.
.SS "uint8_t RDSVB[2]"

.PP
Definition at line 195 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readSVoltage()\&.
.SS "uint8_t RDSVC[2]"

.PP
Definition at line 196 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readSVoltage()\&.
.SS "uint8_t RDSVD[2]"

.PP
Definition at line 197 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readSVoltage()\&.
.SS "uint8_t RDSVE[2]"

.PP
Definition at line 198 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readSVoltage()\&.
.SS "uint8_t RDSVF[2]"

.PP
Definition at line 199 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readSVoltage()\&.
.SS "uint8_t RDV1A[2]"

.PP
Definition at line 76 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDV1B[2]"

.PP
Definition at line 77 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDV1C[2]"

.PP
Definition at line 78 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDV1D[2]"

.PP
Definition at line 79 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDV2A[2]"

.PP
Definition at line 80 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDV2B[2]"

.PP
Definition at line 81 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDV2C[2]"

.PP
Definition at line 82 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDV2D[2]"

.PP
Definition at line 83 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDV2E[2]"

.PP
Definition at line 84 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDVB[2]"

.PP
Definition at line 66 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readVB()\&.
.SS "uint8_t RDVBACC[2]"

.PP
Definition at line 69 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDXA[2]"

.PP
Definition at line 94 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDXB[2]"

.PP
Definition at line 95 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDXC[2]"

.PP
Definition at line 96 of file bms_cmdlist\&.c\&.
.SS "uint8_t RFLAG[4]"

.PP
Definition at line 158 of file bms_cmdlist\&.c\&.
.SS "uint8_t RSTATD[4]"

.PP
Definition at line 156 of file bms_cmdlist\&.c\&.
.SS "uint8_t RSTCC"

.PP
Definition at line 162 of file bms_cmdlist\&.h\&.
.SS "uint8_t sADI1[2]"

.PP
Definition at line 152 of file bms_cmdlist\&.c\&.
.SS "uint8_t sADX[2]"

.PP
Definition at line 153 of file bms_cmdlist\&.c\&.
.SS "uint8_t SNAP"

.PP
Definition at line 163 of file bms_cmdlist\&.h\&.
.SS "uint8_t sRDI[4]"

.PP
Definition at line 159 of file bms_cmdlist\&.c\&.
.SS "uint8_t sRDIAV[4]"

.PP
Definition at line 166 of file bms_cmdlist\&.c\&.
.SS "uint8_t sRDVA[4]"

.PP
Definition at line 162 of file bms_cmdlist\&.c\&.
.SS "uint8_t sRDVB[4]"

.PP
Definition at line 163 of file bms_cmdlist\&.c\&.
.SS "uint8_t sRDVBAT[4]"

.PP
Definition at line 167 of file bms_cmdlist\&.c\&.
.SS "uint8_t sRDVC[4]"

.PP
Definition at line 164 of file bms_cmdlist\&.c\&.
.SS "uint8_t sRDVD[4]"

.PP
Definition at line 165 of file bms_cmdlist\&.c\&.
.SS "uint8_t SRST"

.PP
Definition at line 165 of file bms_cmdlist\&.h\&.
.PP
Referenced by bms_stopDischarge()\&.
.SS "uint8_t sRSTATA[4]"

.SS "uint8_t STCOMM"
Control Commands 
.PP
Definition at line 158 of file bms_cmdlist\&.h\&.
.SS "uint8_t TM_48[2]"

.PP
Definition at line 169 of file bms_cmdlist\&.c\&.
.SS "uint8_t UNMUTE[2]"

.PP
Definition at line 248 of file bms_cmdlist\&.c\&.
.SS "uint8_t UNSNAP"

.PP
Definition at line 164 of file bms_cmdlist\&.h\&.
.SS "uint8_t WRCFGA"

.PP
----------------------- BOTH 2950 AND 6830 ------------------------------- /// < configuration registers commands 
.PP
Definition at line 122 of file bms_cmdlist\&.h\&.
.PP
Referenced by bms_writeConfigA()\&.
.SS "uint8_t WRCFGB"

.PP
Definition at line 123 of file bms_cmdlist\&.h\&.
.PP
Referenced by bms_writeConfigB()\&.
.SS "uint8_t WRCOMM"

.PP
Definition at line 155 of file bms_cmdlist\&.h\&.
.SS "uint8_t WRPWM[2]"

.SS "uint8_t WRPWM1[2]"

.PP
Definition at line 224 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_writePwmA()\&.
.SS "uint8_t WRPWM2"

.PP
Definition at line 217 of file bms_cmdlist\&.h\&.
.PP
Referenced by bms_writePwmB()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
