.TH "Core/Src/bms_cmdlist.c" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Src/bms_cmdlist.c
.SH SYNOPSIS
.br
.PP
\fC#include 'bms_cmdlist\&.h'\fP
.br
\fC#include 'stdint\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "uint8_t \fBWRCFGA\fP [2] = { 0x00, 0x01 }"
.br
.RI "----------------------- BOTH 2950 AND 6830 ------------------------------- /// "
.ti -1c
.RI "uint8_t \fBWRCFGB\fP [2] = { 0x00, 0x24 }"
.br
.ti -1c
.RI "uint8_t \fBRDCFGA\fP [2] = { 0x00, 0x02 }"
.br
.ti -1c
.RI "uint8_t \fBRDCFGB\fP [2] = { 0x00, 0x26 }"
.br
.ti -1c
.RI "uint8_t \fBRDSTATA\fP [2] = { 0x00, 0x30 }"
.br
.ti -1c
.RI "uint8_t \fBRDSTATB\fP [2] = { 0x00, 0x31 }"
.br
.ti -1c
.RI "uint8_t \fBRDSTATC\fP [2] = { 0x00, 0x32 }"
.br
.ti -1c
.RI "uint8_t \fBRDSTATCERR\fP [2] = { 0x00, 0x72 }"
.br
.ti -1c
.RI "uint8_t \fBRDSTATD\fP [2] = { 0x00, 0x33 }"
.br
.ti -1c
.RI "uint8_t \fBRDSTATE\fP [2] = { 0x00, 0x34 }"
.br
.ti -1c
.RI "uint8_t \fBRDASALL\fP [2] = { 0x00, 0x35 }"
.br
.ti -1c
.RI "uint8_t \fBRDAUXC\fP [2] = { 0x00, 0x1B }"
.br
.ti -1c
.RI "uint8_t \fBRDAUXD\fP [2] = { 0x00, 0x1F }"
.br
.ti -1c
.RI "uint8_t \fBRDRAXC\fP [2] = { 0x00, 0x1E }"
.br
.ti -1c
.RI "uint8_t \fBRDRAXD\fP [2] = { 0x00, 0x25 }"
.br
.ti -1c
.RI "uint8_t \fBCLRFLAG\fP [2] = { 0x07, 0x17 }"
.br
.ti -1c
.RI "uint8_t \fBPLADC\fP [2] = { 0x07, 0x18 }"
.br
.ti -1c
.RI "uint8_t \fBWRCOMM\fP [2] = { 0x07, 0x21 }"
.br
.ti -1c
.RI "uint8_t \fBRDCOMM\fP [2] = { 0x07, 0x22 }"
.br
.ti -1c
.RI "uint8_t \fBSTCOMM\fP [13] = { 0x07, 0x23, 0xB9, 0xE4 ,0x00 ,0x00 ,0x00 ,0x00 ,0x00 ,0x00 ,0x00 ,0x00 ,0x00}"
.br
.ti -1c
.RI "uint8_t \fBRDSID\fP [2] = { 0x00, 0x2C }"
.br
.ti -1c
.RI "uint8_t \fBRSTCC\fP [2] = { 0x00, 0x2E }"
.br
.ti -1c
.RI "uint8_t \fBSNAP\fP [2] = { 0x00, 0x2D }"
.br
.ti -1c
.RI "uint8_t \fBUNSNAP\fP [2] = { 0x00, 0x2F }"
.br
.ti -1c
.RI "uint8_t \fBSRST\fP [2] = { 0x00, 0x27 }"
.br
.ti -1c
.RI "uint8_t \fBRDI\fP [2] = { 0x00, 0x04 }"
.br
.RI "----------------------- 2950 ONLY ------------------------------- /// "
.ti -1c
.RI "uint8_t \fBRDVB\fP [2] = { 0x00, 0x06 }"
.br
.ti -1c
.RI "uint8_t \fBRDIVB1\fP [2] = { 0x00, 0x08 }"
.br
.ti -1c
.RI "uint8_t \fBRDIACC\fP [2] = { 0x00, 0x44 }"
.br
.ti -1c
.RI "uint8_t \fBRDVBACC\fP [2] = { 0x00, 0x46 }"
.br
.ti -1c
.RI "uint8_t \fBRDIVB1ACC\fP [2] = { 0x00, 0x48 }"
.br
.ti -1c
.RI "uint8_t \fBRDOC\fP [2] = { 0x00, 0x0B }"
.br
.ti -1c
.RI "uint8_t \fBRDV1A\fP [2] = { 0x00, 0x0A }"
.br
.ti -1c
.RI "uint8_t \fBRDV1B\fP [2] = { 0x00, 0x09 }"
.br
.ti -1c
.RI "uint8_t \fBRDV1C\fP [2] = { 0x00, 0x03 }"
.br
.ti -1c
.RI "uint8_t \fBRDV1D\fP [2] = { 0x00, 0x1B }"
.br
.ti -1c
.RI "uint8_t \fBRDV2A\fP [2] = { 0x00, 0x07 }"
.br
.ti -1c
.RI "uint8_t \fBRDV2B\fP [2] = { 0x00, 0x0D }"
.br
.ti -1c
.RI "uint8_t \fBRDV2C\fP [2] = { 0x00, 0x05 }"
.br
.ti -1c
.RI "uint8_t \fBRDV2D\fP [2] = { 0x00, 0x1F }"
.br
.ti -1c
.RI "uint8_t \fBRDV2E\fP [2] = { 0x00, 0x25 }"
.br
.ti -1c
.RI "uint8_t \fBRDSTAT\fP [2] = { 0x00, 0x34 }"
.br
.ti -1c
.RI "uint8_t \fBRDFLAG\fP [2] = { 0x00, 0x32 }"
.br
.ti -1c
.RI "uint8_t \fBRDFLAGERR\fP [2] = { 0x00, 0x72 }"
.br
.ti -1c
.RI "uint8_t \fBRDXA\fP [2] = { 0x00, 0x30 }"
.br
.ti -1c
.RI "uint8_t \fBRDXB\fP [2] = { 0x00, 0x31 }"
.br
.ti -1c
.RI "uint8_t \fBRDXC\fP [2] = { 0x00, 0x33 }"
.br
.ti -1c
.RI "uint8_t \fBRDALLI\fP [2] = { 0x00, 0x0C }"
.br
.ti -1c
.RI "uint8_t \fBRDALLA\fP [2] = { 0x00, 0x4C }"
.br
.ti -1c
.RI "uint8_t \fBRDALLC\fP [2] = { 0x00, 0x10 }"
.br
.ti -1c
.RI "uint8_t \fBRDALLV\fP [2] = { 0x00, 0x35 }"
.br
.ti -1c
.RI "uint8_t \fBRDALLR\fP [2] = { 0x00, 0x11 }"
.br
.ti -1c
.RI "uint8_t \fBRDALLX\fP [2] = { 0x00, 0x51 }"
.br
.ti -1c
.RI "uint8_t \fBWRPWMA\fP [2] = { 0x00, 0x20 }"
.br
.ti -1c
.RI "uint8_t \fBRDPWMA\fP [2] = { 0x00, 0x22 }"
.br
.ti -1c
.RI "uint8_t \fBWRPWMB\fP [2] = { 0x00, 0x21 }"
.br
.ti -1c
.RI "uint8_t \fBRDPWMB\fP [2] = { 0x00, 0x23 }"
.br
.ti -1c
.RI "uint8_t \fBCLRI\fP [2] = { 0x07, 0x11 }"
.br
.ti -1c
.RI "uint8_t \fBCLRA\fP [2] = { 0x07, 0x14 }"
.br
.ti -1c
.RI "uint8_t \fBCLRO\fP [2] = { 0x07, 0x13 }"
.br
.ti -1c
.RI "uint8_t \fBCLRC\fP [2] = { 0x07, 0x16 }"
.br
.ti -1c
.RI "uint8_t \fBCLRVX\fP [2] = { 0x07, 0x12 }"
.br
.ti -1c
.RI "uint8_t \fBPLI1\fP [2] = { 0x07, 0x1C }"
.br
.ti -1c
.RI "uint8_t \fBPLI2\fP [2] = { 0x07, 0x1D }"
.br
.ti -1c
.RI "uint8_t \fBPLV\fP [2] = { 0x07, 0x1E }"
.br
.ti -1c
.RI "uint8_t \fBPLX\fP [2] = { 0x07, 0x1F }"
.br
.ti -1c
.RI "uint8_t \fBsADI1\fP [2] = { 0x02, 0x60 }"
.br
.ti -1c
.RI "uint8_t \fBsADX\fP [2] = { 0x05, 0x30 }"
.br
.ti -1c
.RI "uint8_t \fBRSTATD\fP [4] = {0x00, 0x33, 0x4D, 0x4A}"
.br
.ti -1c
.RI "uint8_t \fBRFLAG\fP [4] = {0x00, 0x32, 0xc6, 0x78}"
.br
.ti -1c
.RI "uint8_t \fBsRDI\fP [4] = {0x00, 0x04, 0x07, 0xC2}"
.br
.ti -1c
.RI "uint8_t \fBsCLRAB\fP [4] = {0x07,0x11,0xC9,0xC0}"
.br
.ti -1c
.RI "uint8_t \fBsRDVA\fP [4] = { 0x00, 0x0A , 0xC3 , 0x04}"
.br
.ti -1c
.RI "uint8_t \fBsRDVB\fP [4] = { 0x00, 0x09 , 0xD5 , 0x60}"
.br
.ti -1c
.RI "uint8_t \fBsRDVC\fP [4] = { 0x00, 0x03 , 0xA0, 0x38}"
.br
.ti -1c
.RI "uint8_t \fBsRDVD\fP [4] = { 0x00, 0x05 , 0x8C, 0xF0}"
.br
.ti -1c
.RI "uint8_t \fBsRDIAV\fP [4] = { 0x00, 0x44 , 0xE0, 0x48}"
.br
.ti -1c
.RI "uint8_t \fBsRDVBAT\fP [4] = { 0x00, 0x06 , 0x9A, 0x94}"
.br
.ti -1c
.RI "uint8_t \fBTM_48\fP [2] = { 0x00, 0x0E }"
.br
.ti -1c
.RI "uint8_t \fBRDCVA\fP [2] = { 0x00, 0x04 }"
.br
.RI "----------------------- 6830 ONLY ------------------------------- /// "
.ti -1c
.RI "uint8_t \fBRDCVB\fP [2] = { 0x00, 0x06 }"
.br
.ti -1c
.RI "uint8_t \fBRDCVC\fP [2] = { 0x00, 0x08 }"
.br
.ti -1c
.RI "uint8_t \fBRDCVD\fP [2] = { 0x00, 0x0A }"
.br
.ti -1c
.RI "uint8_t \fBRDCVE\fP [2] = { 0x00, 0x09 }"
.br
.ti -1c
.RI "uint8_t \fBRDCVF\fP [2] = { 0x00, 0x0B }"
.br
.ti -1c
.RI "uint8_t \fBRDCVALL\fP [2] = { 0x00, 0x0C }"
.br
.ti -1c
.RI "uint8_t \fBRDACA\fP [2] = { 0x00, 0x44 }"
.br
.ti -1c
.RI "uint8_t \fBRDACB\fP [2] = { 0x00, 0x46 }"
.br
.ti -1c
.RI "uint8_t \fBRDACC\fP [2] = { 0x00, 0x48 }"
.br
.ti -1c
.RI "uint8_t \fBRDACD\fP [2] = { 0x00, 0x4A }"
.br
.ti -1c
.RI "uint8_t \fBRDACE\fP [2] = { 0x00, 0x49 }"
.br
.ti -1c
.RI "uint8_t \fBRDACF\fP [2] = { 0x00, 0x4B }"
.br
.ti -1c
.RI "uint8_t \fBRDACALL\fP [2] = { 0x00, 0x4C }"
.br
.ti -1c
.RI "uint8_t \fBRDSVA\fP [2] = { 0x00, 0x03 }"
.br
.ti -1c
.RI "uint8_t \fBRDSVB\fP [2] = { 0x00, 0x05 }"
.br
.ti -1c
.RI "uint8_t \fBRDSVC\fP [2] = { 0x00, 0x07 }"
.br
.ti -1c
.RI "uint8_t \fBRDSVD\fP [2] = { 0x00, 0x0D }"
.br
.ti -1c
.RI "uint8_t \fBRDSVE\fP [2] = { 0x00, 0x0E }"
.br
.ti -1c
.RI "uint8_t \fBRDSVF\fP [2] = { 0x00, 0x0F }"
.br
.ti -1c
.RI "uint8_t \fBRDSALL\fP [2] = { 0x00, 0x10 }"
.br
.ti -1c
.RI "uint8_t \fBRDCSALL\fP [2] = { 0x00, 0x11 }"
.br
.ti -1c
.RI "uint8_t \fBRDACSALL\fP [2] = { 0x00, 0x51 }"
.br
.ti -1c
.RI "uint8_t \fBRDFCA\fP [2] = { 0x00, 0x12 }"
.br
.ti -1c
.RI "uint8_t \fBRDFCB\fP [2] = { 0x00, 0x13 }"
.br
.ti -1c
.RI "uint8_t \fBRDFCC\fP [2] = { 0x00, 0x14 }"
.br
.ti -1c
.RI "uint8_t \fBRDFCD\fP [2] = { 0x00, 0x15 }"
.br
.ti -1c
.RI "uint8_t \fBRDFCE\fP [2] = { 0x00, 0x16 }"
.br
.ti -1c
.RI "uint8_t \fBRDFCF\fP [2] = { 0x00, 0x17 }"
.br
.ti -1c
.RI "uint8_t \fBRDFCALL\fP [2] = { 0x00, 0x18 }"
.br
.ti -1c
.RI "uint8_t \fBRDAUXA\fP [2] = { 0x00, 0x19 }"
.br
.ti -1c
.RI "uint8_t \fBRDAUXB\fP [2] = { 0x00, 0x1A }"
.br
.ti -1c
.RI "uint8_t \fBRDRAXA\fP [2] = { 0x00, 0x1C }"
.br
.ti -1c
.RI "uint8_t \fBRDRAXB\fP [2] = { 0x00, 0x1D }"
.br
.ti -1c
.RI "uint8_t \fBWRPWM1\fP [2] = { 0x00, 0x20 }"
.br
.ti -1c
.RI "uint8_t \fBRDPWM1\fP [2] = { 0x00, 0x22 }"
.br
.ti -1c
.RI "uint8_t \fBWRPWM2\fP [2] = { 0x00, 0x21 }"
.br
.ti -1c
.RI "uint8_t \fBRDPWM2\fP [2] = { 0x00, 0x23 }"
.br
.ti -1c
.RI "uint8_t \fBCLRCELL\fP [2] = { 0x07, 0x11 }"
.br
.ti -1c
.RI "uint8_t \fBCLRAUX\fP [2] = { 0x07, 0x12 }"
.br
.ti -1c
.RI "uint8_t \fBCLRSPIN\fP [2] = { 0x07, 0x16 }"
.br
.ti -1c
.RI "uint8_t \fBCLRFC\fP [2] = { 0x07, 0x14 }"
.br
.ti -1c
.RI "uint8_t \fBCLOVUV\fP [2] = { 0x07, 0x15 }"
.br
.ti -1c
.RI "uint8_t \fBPLAUT\fP [2] = { 0x07, 0x19 }"
.br
.ti -1c
.RI "uint8_t \fBPLCADC\fP [2] = { 0x07, 0x1C }"
.br
.ti -1c
.RI "uint8_t \fBPLSADC\fP [2] = { 0x07, 0x1D }"
.br
.ti -1c
.RI "uint8_t \fBPLAUX1\fP [2] = { 0x07, 0x1E }"
.br
.ti -1c
.RI "uint8_t \fBPLAUX2\fP [2] = { 0x07, 0x1F }"
.br
.ti -1c
.RI "uint8_t \fBDIAGN\fP [2] = {0x07 , 0x15}"
.br
.ti -1c
.RI "uint8_t \fBMUTE\fP [2] = { 0x00, 0x28 }"
.br
.ti -1c
.RI "uint8_t \fBUNMUTE\fP [2] = { 0x00, 0x29 }"
.br
.ti -1c
.RI "const \fBADCV_t\fP \fBADCV_default\fP"
.br
.ti -1c
.RI "\fBADCV_t\fP \fBADCV\fP = \fBADCV_default\fP"
.br
.ti -1c
.RI "const \fBADSV_t\fP \fBADSV_default\fP"
.br
.ti -1c
.RI "\fBADSV_t\fP \fBADSV\fP = \fBADSV_default\fP"
.br
.ti -1c
.RI "const \fBADAX2_t\fP \fBADAX2_default\fP"
.br
.ti -1c
.RI "\fBADAX2_t\fP \fBADAX2\fP = \fBADAX2_default\fP"
.br
.ti -1c
.RI "const \fBADAX_t\fP \fBADAX_default\fP"
.br
.ti -1c
.RI "\fBADAX_t\fP \fBADAX\fP = \fBADAX_default\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBADAX_t\fP ADAX = \fBADAX_default\fP"

.PP
Definition at line 310 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_getAuxMeasurement()\&.
.SS "\fBADAX2_t\fP ADAX2 = \fBADAX2_default\fP"

.PP
Definition at line 295 of file bms_cmdlist\&.c\&.
.SS "const \fBADAX2_t\fP ADAX2_default"
\fBInitial value:\fP
.PP
.nf
=
{
    \&.RES   = 0b000001000000,
    \&.CH    = 0b0000,
}
.fi
.PP
Definition at line 289 of file bms_cmdlist\&.c\&.
.SS "const \fBADAX_t\fP ADAX_default"
\fBInitial value:\fP
.PP
.nf
=
{
    \&.OW   = 0b0,
    \&.RES0 = 0b10,
    \&.X    = 0b00000,

    \&.CH   = 0b0000,
    \&.RES1 = 0b01,
    \&.CH4  = 0b0,
    \&.PUP  = 0b0,
}
.fi
.PP
Definition at line 298 of file bms_cmdlist\&.c\&.
.SS "\fBADCV_t\fP ADCV = \fBADCV_default\fP"

.PP
Definition at line 270 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_startAdcvCont()\&.
.SS "const \fBADCV_t\fP ADCV_default"
\fBInitial value:\fP
.PP
.nf
=
{
    \&.RD   = 0,
    \&.RES2 = 0b01,
    \&.X    = 0b00000,

    \&.OW   = 0,
    \&.RSTF = 0,
    \&.RES0 = 0b0,
    \&.DCP  = 0,
    \&.RES1 = 0b11,
    \&.CONT = 0,
}
.fi
.PP
Definition at line 256 of file bms_cmdlist\&.c\&.
.SS "\fBADSV_t\fP ADSV = \fBADSV_default\fP"

.PP
Definition at line 285 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_balancingMeasureVoltage(), and bms_openWireCheck()\&.
.SS "const \fBADSV_t\fP ADSV_default"
\fBInitial value:\fP
.PP
.nf
=
{
    \&.RES2 = 0b001,
    \&.X    = 0b00000,

    \&.OW   = 0b00,
    \&.RES0 = 0b10,
    \&.DCP  = 0,
    \&.RES1 = 0b11,
    \&.CONT = 0,
}
.fi
.PP
Definition at line 273 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLOVUV[2] = { 0x07, 0x15 }"

.PP
Definition at line 234 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLRA[2] = { 0x07, 0x14 }"

.PP
Definition at line 126 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLRAUX[2] = { 0x07, 0x12 }"

.PP
Definition at line 231 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLRC[2] = { 0x07, 0x16 }"

.PP
Definition at line 128 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLRCELL[2] = { 0x07, 0x11 }"

.PP
Definition at line 230 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLRFC[2] = { 0x07, 0x14 }"

.PP
Definition at line 233 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLRFLAG[2] = { 0x07, 0x17 }"

.PP
Definition at line 36 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLRI[2] = { 0x07, 0x11 }"

.PP
Definition at line 125 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLRO[2] = { 0x07, 0x13 }"

.PP
Definition at line 127 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLRSPIN[2] = { 0x07, 0x16 }"

.PP
Definition at line 232 of file bms_cmdlist\&.c\&.
.SS "uint8_t CLRVX[2] = { 0x07, 0x12 }"

.PP
Definition at line 129 of file bms_cmdlist\&.c\&.
.SS "uint8_t DIAGN[2] = {0x07 , 0x15}"

.PP
Definition at line 244 of file bms_cmdlist\&.c\&.
.SS "uint8_t MUTE[2] = { 0x00, 0x28 }"

.PP
Definition at line 247 of file bms_cmdlist\&.c\&.
.SS "uint8_t PLADC[2] = { 0x07, 0x18 }"
GPIOs Comm commands 
.PP
Definition at line 39 of file bms_cmdlist\&.c\&.
.SS "uint8_t PLAUT[2] = { 0x07, 0x19 }"

.PP
Definition at line 237 of file bms_cmdlist\&.c\&.
.SS "uint8_t PLAUX1[2] = { 0x07, 0x1E }"

.PP
Definition at line 240 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_getAuxMeasurement()\&.
.SS "uint8_t PLAUX2[2] = { 0x07, 0x1F }"

.PP
Definition at line 241 of file bms_cmdlist\&.c\&.
.SS "uint8_t PLCADC[2] = { 0x07, 0x1C }"

.PP
Definition at line 238 of file bms_cmdlist\&.c\&.
.SS "uint8_t PLI1[2] = { 0x07, 0x1C }"

.PP
Definition at line 135 of file bms_cmdlist\&.c\&.
.SS "uint8_t PLI2[2] = { 0x07, 0x1D }"

.PP
Definition at line 136 of file bms_cmdlist\&.c\&.
.SS "uint8_t PLSADC[2] = { 0x07, 0x1D }"

.PP
Definition at line 239 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_balancingMeasureVoltage()\&.
.SS "uint8_t PLV[2] = { 0x07, 0x1E }"

.PP
Definition at line 137 of file bms_cmdlist\&.c\&.
.SS "uint8_t PLX[2] = { 0x07, 0x1F }"

.PP
Definition at line 138 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDACA[2] = { 0x00, 0x44 }"

.PP
Definition at line 185 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readAvgCellVoltage()\&.
.SS "uint8_t RDACALL[2] = { 0x00, 0x4C }"

.PP
Definition at line 191 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDACB[2] = { 0x00, 0x46 }"

.PP
Definition at line 186 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readAvgCellVoltage()\&.
.SS "uint8_t RDACC[2] = { 0x00, 0x48 }"

.PP
Definition at line 187 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readAvgCellVoltage()\&.
.SS "uint8_t RDACD[2] = { 0x00, 0x4A }"

.PP
Definition at line 188 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readAvgCellVoltage()\&.
.SS "uint8_t RDACE[2] = { 0x00, 0x49 }"

.PP
Definition at line 189 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readAvgCellVoltage()\&.
.SS "uint8_t RDACF[2] = { 0x00, 0x4B }"

.PP
Definition at line 190 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readAvgCellVoltage()\&.
.SS "uint8_t RDACSALL[2] = { 0x00, 0x51 }"

.PP
Definition at line 204 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDALLA[2] = { 0x00, 0x4C }"

.PP
Definition at line 103 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDALLC[2] = { 0x00, 0x10 }"

.PP
Definition at line 106 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDALLI[2] = { 0x00, 0x0C }"

.PP
Definition at line 100 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDALLR[2] = { 0x00, 0x11 }"

.PP
Definition at line 112 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDALLV[2] = { 0x00, 0x35 }"

.PP
Definition at line 109 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDALLX[2] = { 0x00, 0x51 }"

.PP
Definition at line 115 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDASALL[2] = { 0x00, 0x35 }"
Reserved Read Commands - 2950 
.PP
Definition at line 23 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDAUXA[2] = { 0x00, 0x19 }"

.PP
Definition at line 216 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_getAuxVoltage()\&.
.SS "uint8_t RDAUXB[2] = { 0x00, 0x1A }"

.PP
Definition at line 217 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_getAuxVoltage()\&.
.SS "uint8_t RDAUXC[2] = { 0x00, 0x1B }"

.PP
Definition at line 27 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_getAuxVoltage()\&.
.SS "uint8_t RDAUXD[2] = { 0x00, 0x1F }"
Reserved Read Commands - 2950 
.PP
Definition at line 28 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_getAuxVoltage()\&.
.SS "uint8_t RDCFGA[2] = { 0x00, 0x02 }"

.PP
Definition at line 11 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readConfigA()\&.
.SS "uint8_t RDCFGB[2] = { 0x00, 0x26 }"
Read status registers 
.PP
Definition at line 12 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readConfigB()\&.
.SS "uint8_t RDCOMM[2] = { 0x07, 0x22 }"
command + dummy data for 72 clock cycles 
.PP
Definition at line 43 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDCSALL[2] = { 0x00, 0x11 }"

.PP
Definition at line 203 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDCVA[2] = { 0x00, 0x04 }"

.PP
----------------------- 6830 ONLY ------------------------------- /// 
.PP
Definition at line 176 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDCVALL[2] = { 0x00, 0x0C }"

.PP
Definition at line 182 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDCVB[2] = { 0x00, 0x06 }"

.PP
Definition at line 177 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDCVC[2] = { 0x00, 0x08 }"

.PP
Definition at line 178 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDCVD[2] = { 0x00, 0x0A }"

.PP
Definition at line 179 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDCVE[2] = { 0x00, 0x09 }"

.PP
Definition at line 180 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDCVF[2] = { 0x00, 0x0B }"

.PP
Definition at line 181 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDFCA[2] = { 0x00, 0x12 }"

.PP
Definition at line 207 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDFCALL[2] = { 0x00, 0x18 }"

.PP
Definition at line 213 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDFCB[2] = { 0x00, 0x13 }"

.PP
Definition at line 208 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDFCC[2] = { 0x00, 0x14 }"

.PP
Definition at line 209 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDFCD[2] = { 0x00, 0x15 }"

.PP
Definition at line 210 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDFCE[2] = { 0x00, 0x16 }"

.PP
Definition at line 211 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDFCF[2] = { 0x00, 0x17 }"

.PP
Definition at line 212 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDFLAG[2] = { 0x00, 0x32 }"

.PP
Definition at line 90 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDFLAGERR[2] = { 0x00, 0x72 }"

.PP
Definition at line 91 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDI[2] = { 0x00, 0x04 }"

.PP
----------------------- 2950 ONLY ------------------------------- /// 
.PP
Definition at line 65 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDIACC[2] = { 0x00, 0x44 }"

.PP
Definition at line 68 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDIVB1[2] = { 0x00, 0x08 }"

.PP
Definition at line 67 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDIVB1ACC[2] = { 0x00, 0x48 }"

.PP
Definition at line 70 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDOC[2] = { 0x00, 0x0B }"

.PP
Definition at line 73 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDPWM1[2] = { 0x00, 0x22 }"

.PP
Definition at line 225 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDPWM2[2] = { 0x00, 0x23 }"

.PP
Definition at line 227 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDPWMA[2] = { 0x00, 0x22 }"

.PP
Definition at line 119 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDPWMB[2] = { 0x00, 0x23 }"

.PP
Definition at line 121 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDRAXA[2] = { 0x00, 0x1C }"

.PP
Definition at line 220 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDRAXB[2] = { 0x00, 0x1D }"

.PP
Definition at line 221 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDRAXC[2] = { 0x00, 0x1E }"

.PP
Definition at line 32 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDRAXD[2] = { 0x00, 0x25 }"

.PP
Definition at line 33 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDSALL[2] = { 0x00, 0x10 }"

.PP
Definition at line 200 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDSID[2] = { 0x00, 0x2C }"

.PP
Definition at line 48 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readSid()\&.
.SS "uint8_t RDSTAT[2] = { 0x00, 0x34 }"

.PP
Definition at line 87 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDSTATA[2] = { 0x00, 0x30 }"

.PP
Definition at line 15 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_getAuxVoltage()\&.
.SS "uint8_t RDSTATB[2] = { 0x00, 0x31 }"

.PP
Definition at line 16 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDSTATC[2] = { 0x00, 0x32 }"

.PP
Definition at line 17 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDSTATCERR[2] = { 0x00, 0x72 }"

.PP
Definition at line 18 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDSTATD[2] = { 0x00, 0x33 }"

.PP
Definition at line 19 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDSTATE[2] = { 0x00, 0x34 }"

.PP
Definition at line 20 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDSVA[2] = { 0x00, 0x03 }"

.PP
Definition at line 194 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readSVoltage()\&.
.SS "uint8_t RDSVB[2] = { 0x00, 0x05 }"

.PP
Definition at line 195 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readSVoltage()\&.
.SS "uint8_t RDSVC[2] = { 0x00, 0x07 }"

.PP
Definition at line 196 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readSVoltage()\&.
.SS "uint8_t RDSVD[2] = { 0x00, 0x0D }"

.PP
Definition at line 197 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readSVoltage()\&.
.SS "uint8_t RDSVE[2] = { 0x00, 0x0E }"

.PP
Definition at line 198 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readSVoltage()\&.
.SS "uint8_t RDSVF[2] = { 0x00, 0x0F }"

.PP
Definition at line 199 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readSVoltage()\&.
.SS "uint8_t RDV1A[2] = { 0x00, 0x0A }"

.PP
Definition at line 76 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDV1B[2] = { 0x00, 0x09 }"

.PP
Definition at line 77 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDV1C[2] = { 0x00, 0x03 }"

.PP
Definition at line 78 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDV1D[2] = { 0x00, 0x1B }"

.PP
Definition at line 79 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDV2A[2] = { 0x00, 0x07 }"

.PP
Definition at line 80 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDV2B[2] = { 0x00, 0x0D }"

.PP
Definition at line 81 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDV2C[2] = { 0x00, 0x05 }"

.PP
Definition at line 82 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDV2D[2] = { 0x00, 0x1F }"

.PP
Definition at line 83 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDV2E[2] = { 0x00, 0x25 }"

.PP
Definition at line 84 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDVB[2] = { 0x00, 0x06 }"

.PP
Definition at line 66 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_readVB()\&.
.SS "uint8_t RDVBACC[2] = { 0x00, 0x46 }"

.PP
Definition at line 69 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDXA[2] = { 0x00, 0x30 }"

.PP
Definition at line 94 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDXB[2] = { 0x00, 0x31 }"

.PP
Definition at line 95 of file bms_cmdlist\&.c\&.
.SS "uint8_t RDXC[2] = { 0x00, 0x33 }"

.PP
Definition at line 96 of file bms_cmdlist\&.c\&.
.SS "uint8_t RFLAG[4] = {0x00, 0x32, 0xc6, 0x78}"

.PP
Definition at line 158 of file bms_cmdlist\&.c\&.
.SS "uint8_t RSTATD[4] = {0x00, 0x33, 0x4D, 0x4A}"

.PP
Definition at line 156 of file bms_cmdlist\&.c\&.
.SS "uint8_t RSTCC[2] = { 0x00, 0x2E }"

.PP
Definition at line 49 of file bms_cmdlist\&.c\&.
.SS "uint8_t sADI1[2] = { 0x02, 0x60 }"

.PP
Definition at line 152 of file bms_cmdlist\&.c\&.
.SS "uint8_t sADX[2] = { 0x05, 0x30 }"

.PP
Definition at line 153 of file bms_cmdlist\&.c\&.
.SS "uint8_t sCLRAB[4] = {0x07,0x11,0xC9,0xC0}"

.PP
Definition at line 160 of file bms_cmdlist\&.c\&.
.SS "uint8_t SNAP[2] = { 0x00, 0x2D }"

.PP
Definition at line 50 of file bms_cmdlist\&.c\&.
.SS "uint8_t sRDI[4] = {0x00, 0x04, 0x07, 0xC2}"

.PP
Definition at line 159 of file bms_cmdlist\&.c\&.
.SS "uint8_t sRDIAV[4] = { 0x00, 0x44 , 0xE0, 0x48}"

.PP
Definition at line 166 of file bms_cmdlist\&.c\&.
.SS "uint8_t sRDVA[4] = { 0x00, 0x0A , 0xC3 , 0x04}"

.PP
Definition at line 162 of file bms_cmdlist\&.c\&.
.SS "uint8_t sRDVB[4] = { 0x00, 0x09 , 0xD5 , 0x60}"

.PP
Definition at line 163 of file bms_cmdlist\&.c\&.
.SS "uint8_t sRDVBAT[4] = { 0x00, 0x06 , 0x9A, 0x94}"

.PP
Definition at line 167 of file bms_cmdlist\&.c\&.
.SS "uint8_t sRDVC[4] = { 0x00, 0x03 , 0xA0, 0x38}"

.PP
Definition at line 164 of file bms_cmdlist\&.c\&.
.SS "uint8_t sRDVD[4] = { 0x00, 0x05 , 0x8C, 0xF0}"

.PP
Definition at line 165 of file bms_cmdlist\&.c\&.
.SS "uint8_t SRST[2] = { 0x00, 0x27 }"

.PP
Definition at line 52 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_stopDischarge()\&.
.SS "uint8_t STCOMM[13] = { 0x07, 0x23, 0xB9, 0xE4 ,0x00 ,0x00 ,0x00 ,0x00 ,0x00 ,0x00 ,0x00 ,0x00 ,0x00}"
Control Commands 
.PP
Definition at line 45 of file bms_cmdlist\&.c\&.
.SS "uint8_t TM_48[2] = { 0x00, 0x0E }"

.PP
Definition at line 169 of file bms_cmdlist\&.c\&.
.SS "uint8_t UNMUTE[2] = { 0x00, 0x29 }"

.PP
Definition at line 248 of file bms_cmdlist\&.c\&.
.SS "uint8_t UNSNAP[2] = { 0x00, 0x2F }"

.PP
Definition at line 51 of file bms_cmdlist\&.c\&.
.SS "uint8_t WRCFGA[2] = { 0x00, 0x01 }"

.PP
----------------------- BOTH 2950 AND 6830 ------------------------------- /// < configuration registers commands 
.PP
Definition at line 9 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_writeConfigA()\&.
.SS "uint8_t WRCFGB[2] = { 0x00, 0x24 }"

.PP
Definition at line 10 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_writeConfigB()\&.
.SS "uint8_t WRCOMM[2] = { 0x07, 0x21 }"

.PP
Definition at line 42 of file bms_cmdlist\&.c\&.
.SS "uint8_t WRPWM1[2] = { 0x00, 0x20 }"

.PP
Definition at line 224 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_writePwmA()\&.
.SS "uint8_t WRPWM2[2] = { 0x00, 0x21 }"

.PP
Definition at line 226 of file bms_cmdlist\&.c\&.
.PP
Referenced by bms_writePwmB()\&.
.SS "uint8_t WRPWMA[2] = { 0x00, 0x20 }"

.PP
Definition at line 118 of file bms_cmdlist\&.c\&.
.SS "uint8_t WRPWMB[2] = { 0x00, 0x21 }"

.PP
Definition at line 120 of file bms_cmdlist\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
