.TH "Core/Inc/brain.h" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Inc/brain.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBErrorStatus_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBBmsStates\fP { \fBBALANCING\fP, \fBCHARGING\fP, \fBIDLE\fP, \fBONMISSION\fP, \fBSTARTUP\fP, \fBINACTIVE\fP }"
.br
.ti -1c
.RI "enum \fBErrorCode_t\fP { \fBERROR_NONE\fP = 0x00, \fBERROR_SDC_TRIGGERED\fP = 0x01, \fBERROR_IMD_TRIGGERED\fP = 0x02, \fBERROR_CONTACTORS_MISMATCH\fP = 0x04, \fBERROR_TIMER_FAILURE\fP = 0x08, \fBERROR_CAN_FAILED\fP = 0x10, \fBERROR_OVERVOLTAGE\fP = 0x20, \fBERROR_OVERCURRENT\fP = 0x30, \fBERROR_BMS_OW\fP = 0x40, \fBERROR_BMS_FAIL\fP = 0x50 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbrain_start\fP (void)"
.br
.ti -1c
.RI "void \fBbrain_loop\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBgetRuntimeMs\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBgetRuntimeMsDiff\fP (uint32_t startTime)"
.br
.ti -1c
.RI "void \fBHAL_TIM_PeriodElapsedCallback\fP (TIM_HandleTypeDef *\fBhtim\fP)"
.br
.RI "Timer interrupt callback\&. "
.ti -1c
.RI "void \fBHAL_SYSTICK_Callback\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_GPIO_EXTI_Callback\fP (uint16_t GPIO_Pin)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "volatile \fBBmsStates\fP \fBbmsState\fP"
.br
.ti -1c
.RI "volatile \fBBmsStates\fP \fBbmsCurrState\fP"
.br
.ti -1c
.RI "volatile \fBBmsStates\fP \fBbmsPrevState\fP"
.br
.ti -1c
.RI "\fBErrorStatus_t\fP \fBerrorStatus\fP"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBBmsStates\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIBALANCING \fP\fP
.TP
\fB\fICHARGING \fP\fP
.TP
\fB\fIIDLE \fP\fP
.TP
\fB\fIONMISSION \fP\fP
.TP
\fB\fISTARTUP \fP\fP
.TP
\fB\fIINACTIVE \fP\fP
.PP
Definition at line 16 of file brain\&.h\&.
.SS "enum \fBErrorCode_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIERROR_NONE \fP\fP
.TP
\fB\fIERROR_SDC_TRIGGERED \fP\fP
.TP
\fB\fIERROR_IMD_TRIGGERED \fP\fP
.TP
\fB\fIERROR_CONTACTORS_MISMATCH \fP\fP
.TP
\fB\fIERROR_TIMER_FAILURE \fP\fP
.TP
\fB\fIERROR_CAN_FAILED \fP\fP
.TP
\fB\fIERROR_OVERVOLTAGE \fP\fP
.TP
\fB\fIERROR_OVERCURRENT \fP\fP
.TP
\fB\fIERROR_BMS_OW \fP\fP
.TP
\fB\fIERROR_BMS_FAIL \fP\fP
.PP
Definition at line 30 of file brain\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void brain_loop (void)"

.PP
Definition at line 146 of file brain\&.c\&.
.PP
References BALANCING, bms_calculateBalancing(), bms_delayMsActive(), bms_getAuxMeasurement(), bms_readAvgCellVoltage(), bms_startAdcvCont(), bms_wakeupChain(), bmsCurrState, bmsPrevState, bmsState, CAN_Send_AD68_All(), CanTx_ProcessQueue(), deltaThreshold, END, faultCheck, getRuntimeMs(), getRuntimeMsDiff(), hcan1, IDLE, INACTIVE, Precharge_GetState(), Precharge_Init(), Precharge_Update(), printConsole(), read_mcu_temp(), RX_CAN, send_ad68_ui(), START, STARTUP, timeCmmd, timeDiff, timeStart, and updateUI\&.
.PP
Referenced by main()\&.
.SS "void brain_start (void)"

.PP
Definition at line 66 of file brain\&.c\&.
.PP
References bms_delayMsActive(), bms_getAuxMeasurement(), bms_init(), BMS_MSTR_GPIO_Port, BMS_MSTR_Pin, bms_readAvgCellVoltage(), bms_readSid(), bms_readSVoltage(), bms_startAdcvCont(), bms_stopDischarge(), bms_wakeupChain(), bmsCurrState, bmsPrevState, bmsState, hcan1, htim10, htim11, htim8, IDLE, INACTIVE, IVT_CAN_Config(), IVT_CAN_Setup_AllMessages(), IVT_SET_BITRATE(), OpenAllContactors(), Precharge_CAN_Init(), printConsole(), printfDmaBT(), and startUI()\&.
.PP
Referenced by main()\&.
.SS "uint32_t getRuntimeMs (void)"

.PP
Definition at line 332 of file brain\&.c\&.
.PP
Referenced by brain_loop()\&.
.SS "uint32_t getRuntimeMsDiff (uint32_t startTime)"

.PP
Definition at line 336 of file brain\&.c\&.
.PP
Referenced by brain_loop()\&.
.SS "void HAL_GPIO_EXTI_Callback (uint16_t GPIO_Pin)"

.PP
Definition at line 340 of file brain\&.c\&.
.PP
References B1_Pin, bmsState, IDLE, and ONMISSION\&.
.SS "void HAL_SYSTICK_Callback (void)"

.PP
Definition at line 313 of file brain\&.c\&.
.PP
References LED_RED_GPIO_Port, and LED_RED_Pin\&.
.SS "void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef * htim)"

.PP
Timer interrupt callback\&. 
.PP
Definition at line 294 of file brain\&.c\&.
.PP
References faultCheck, htim, htim10, runtime_sec, and updateUI\&.
.SH "Variable Documentation"
.PP 
.SS "volatile \fBBmsStates\fP bmsCurrState"

.PP
Definition at line 53 of file brain\&.c\&.
.PP
Referenced by brain_loop(), and brain_start()\&.
.SS "volatile \fBBmsStates\fP bmsPrevState"

.PP
Definition at line 54 of file brain\&.c\&.
.PP
Referenced by brain_loop(), and brain_start()\&.
.SS "volatile \fBBmsStates\fP bmsState"

.PP
Definition at line 52 of file brain\&.c\&.
.PP
Referenced by brain_loop(), brain_start(), and HAL_GPIO_EXTI_Callback()\&.
.SS "\fBErrorStatus_t\fP errorStatus"

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
