.TH "Core/Src/brain.c" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Src/brain.c
.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br
\fC#include 'brain\&.h'\fP
.br
\fC#include 'math\&.h'\fP
.br
\fC#include 'stdio\&.h'\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include 'bms_cmdlist\&.h'\fP
.br
\fC#include 'bms_datatypes\&.h'\fP
.br
\fC#include 'bms_utility\&.h'\fP
.br
\fC#include 'bms_mcuWrapper\&.h'\fP
.br
\fC#include 'bms_libWrapper\&.h'\fP
.br
\fC#include 'eeprom_utils\&.h'\fP
.br
\fC#include 'isa_ivt\-s\&.h'\fP
.br
\fC#include 'time_rtc\&.h'\fP
.br
\fC#include 'contactors\&.h'\fP
.br
\fC#include 'uartDMA\&.h'\fP
.br
\fC#include 'version\&.h'\fP
.br
\fC#include 'temperatures\&.h'\fP
.br
\fC#include 'precharge\&.h'\fP
.br
\fC#include 'ams\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBYPASS_CAN_ISA\fP"
.br
.ti -1c
.RI "#define \fBSTEERING_MAX\fP   0xA1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbrain_start\fP (void)"
.br
.ti -1c
.RI "void \fBbrain_loop\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_TIM_PeriodElapsedCallback\fP (TIM_HandleTypeDef *\fBhtim\fP)"
.br
.RI "Timer interrupt callback\&. "
.ti -1c
.RI "void \fBHAL_SYSTICK_Callback\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBgetRuntimeMs\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBgetRuntimeMsDiff\fP (uint32_t startTime)"
.br
.ti -1c
.RI "void \fBHAL_GPIO_EXTI_Callback\fP (uint16_t GPIO_Pin)"
.br
.ti -1c
.RI "void \fBRaiseError\fP (\fBErrorCode_t\fP errorcode)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const float \fBdeltaThreshold\fP = 0\&.010f"
.br
.ti -1c
.RI "\fBbms_ow_status_t\fP \fBow_status\fP [\fBTOTAL_AD68\fP][\fBTOTAL_CELL\fP]"
.br
.ti -1c
.RI "volatile \fBBmsStates\fP \fBbmsState\fP = \fBIDLE\fP"
.br
.ti -1c
.RI "volatile \fBBmsStates\fP \fBbmsCurrState\fP = \fBIDLE\fP"
.br
.ti -1c
.RI "volatile \fBBmsStates\fP \fBbmsPrevState\fP = \fBIDLE\fP"
.br
.ti -1c
.RI "static volatile uint32_t \fBruntime_sec\fP = 0"
.br
.ti -1c
.RI "static volatile bool \fBfaultCheck\fP = false"
.br
.ti -1c
.RI "static volatile bool \fBupdateUI\fP = false"
.br
.ti -1c
.RI "static uint32_t \fBtimeDiff\fP = 0"
.br
.ti -1c
.RI "static uint32_t \fBtimeStart\fP = 0"
.br
.ti -1c
.RI "static uint32_t \fBtimeCmmd\fP = 0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BYPASS_CAN_ISA"

.PP
Definition at line 39 of file brain\&.c\&.
.SS "#define STEERING_MAX   0xA1"

.PP
Definition at line 43 of file brain\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void brain_loop (void)"

.PP
Definition at line 146 of file brain\&.c\&.
.PP
References BALANCING, bms_calculateBalancing(), bms_delayMsActive(), bms_getAuxMeasurement(), bms_readAvgCellVoltage(), bms_startAdcvCont(), bms_wakeupChain(), bmsCurrState, bmsPrevState, bmsState, CAN_Send_AD68_All(), CanTx_ProcessQueue(), deltaThreshold, END, faultCheck, getRuntimeMs(), getRuntimeMsDiff(), hcan1, IDLE, INACTIVE, Precharge_GetState(), Precharge_Init(), Precharge_Update(), printConsole(), read_mcu_temp(), RX_CAN, send_ad68_ui(), START, STARTUP, timeCmmd, timeDiff, timeStart, and updateUI\&.
.PP
Referenced by main()\&.
.SS "void brain_start (void)"

.PP
Definition at line 66 of file brain\&.c\&.
.PP
References bms_delayMsActive(), bms_getAuxMeasurement(), bms_init(), BMS_MSTR_GPIO_Port, BMS_MSTR_Pin, bms_readAvgCellVoltage(), bms_readSid(), bms_readSVoltage(), bms_startAdcvCont(), bms_stopDischarge(), bms_wakeupChain(), bmsCurrState, bmsPrevState, bmsState, hcan1, htim10, htim11, htim8, IDLE, INACTIVE, IVT_CAN_Config(), IVT_CAN_Setup_AllMessages(), IVT_SET_BITRATE(), OpenAllContactors(), Precharge_CAN_Init(), printConsole(), printfDmaBT(), and startUI()\&.
.PP
Referenced by main()\&.
.SS "uint32_t getRuntimeMs (void)"

.PP
Definition at line 332 of file brain\&.c\&.
.PP
Referenced by brain_loop()\&.
.SS "uint32_t getRuntimeMsDiff (uint32_t startTime)"

.PP
Definition at line 336 of file brain\&.c\&.
.PP
Referenced by brain_loop()\&.
.SS "void HAL_GPIO_EXTI_Callback (uint16_t GPIO_Pin)"

.PP
Definition at line 340 of file brain\&.c\&.
.PP
References B1_Pin, bmsState, IDLE, and ONMISSION\&.
.SS "void HAL_SYSTICK_Callback (void)"

.PP
Definition at line 313 of file brain\&.c\&.
.PP
References LED_RED_GPIO_Port, and LED_RED_Pin\&.
.SS "void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef * htim)"

.PP
Timer interrupt callback\&. 
.PP
Definition at line 294 of file brain\&.c\&.
.PP
References faultCheck, htim, htim10, runtime_sec, and updateUI\&.
.SS "void RaiseError (\fBErrorCode_t\fP errorcode)"

.PP
Definition at line 350 of file brain\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "volatile \fBBmsStates\fP bmsCurrState = \fBIDLE\fP"

.PP
Definition at line 53 of file brain\&.c\&.
.PP
Referenced by brain_loop(), and brain_start()\&.
.SS "volatile \fBBmsStates\fP bmsPrevState = \fBIDLE\fP"

.PP
Definition at line 54 of file brain\&.c\&.
.PP
Referenced by brain_loop(), and brain_start()\&.
.SS "volatile \fBBmsStates\fP bmsState = \fBIDLE\fP"

.PP
Definition at line 52 of file brain\&.c\&.
.PP
Referenced by brain_loop(), brain_start(), and HAL_GPIO_EXTI_Callback()\&.
.SS "const float deltaThreshold = 0\&.010f"

.PP
Definition at line 44 of file brain\&.c\&.
.PP
Referenced by bms_startBalancing(), and brain_loop()\&.
.SS "volatile bool faultCheck = false\fC [static]\fP"

.PP
Definition at line 58 of file brain\&.c\&.
.PP
Referenced by brain_loop(), and HAL_TIM_PeriodElapsedCallback()\&.
.SS "\fBbms_ow_status_t\fP ow_status[\fBTOTAL_AD68\fP][\fBTOTAL_CELL\fP]"

.PP
Definition at line 47 of file brain\&.c\&.
.SS "volatile uint32_t runtime_sec = 0\fC [static]\fP"

.PP
Definition at line 57 of file brain\&.c\&.
.PP
Referenced by HAL_TIM_PeriodElapsedCallback()\&.
.SS "uint32_t timeCmmd = 0\fC [static]\fP"

.PP
Definition at line 64 of file brain\&.c\&.
.PP
Referenced by brain_loop()\&.
.SS "uint32_t timeDiff = 0\fC [static]\fP"

.PP
Definition at line 62 of file brain\&.c\&.
.PP
Referenced by brain_loop()\&.
.SS "uint32_t timeStart = 0\fC [static]\fP"

.PP
Definition at line 63 of file brain\&.c\&.
.PP
Referenced by brain_loop()\&.
.SS "volatile bool updateUI = false\fC [static]\fP"

.PP
Definition at line 59 of file brain\&.c\&.
.PP
Referenced by brain_loop(), and HAL_TIM_PeriodElapsedCallback()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
