.TH "Core/Inc Directory Reference" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Inc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBdbc\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbms_cmdlist\&.h\fP"
.br
.ti -1c
.RI "file \fBbms_datatypes\&.h\fP"
.br
.ti -1c
.RI "file \fBbms_libWrapper\&.h\fP"
.br
.ti -1c
.RI "file \fBbms_mcuWrapper\&.h\fP"
.br
.ti -1c
.RI "file \fBbms_utility\&.h\fP"
.br
.ti -1c
.RI "file \fBbrain\&.h\fP"
.br
.ti -1c
.RI "file \fBcan\&.h\fP"
.br
.ti -1c
.RI "file \fBcontactors\&.h\fP"
.br
.ti -1c
.RI "file \fBee24\&.h\fP"
.br
.ti -1c
.RI "file \fBeeprom_utils\&.h\fP"
.br
.ti -1c
.RI "file \fBfan_management\&.h\fP"
.br
.ti -1c
.RI "file \fBisa_ivt\-s\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.h\fP"
.br
.RI ": Header for \fBmain\&.c\fP file\&. This file contains the common defines of the application\&. "
.ti -1c
.RI "file \fBprecharge\&.h\fP"
.br
.ti -1c
.RI "file \fBstm32f4xx_hal_conf\&.h\fP"
.br
.ti -1c
.RI "file \fBstm32f4xx_it\&.h\fP"
.br
.RI "This file contains the headers of the interrupt handlers\&. "
.ti -1c
.RI "file \fBtemperatures\&.h\fP"
.br
.ti -1c
.RI "file \fBtime_rtc\&.h\fP"
.br
.ti -1c
.RI "file \fBuartDMA\&.h\fP"
.br
.ti -1c
.RI "file \fBversion\&.h\fP"
.br
.in -1c
