.TH "Core/Src/can.c" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Src/can.c
.SH SYNOPSIS
.br
.PP
\fC#include 'can\&.h'\fP
.br
\fC#include 'brain\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBCanTxItem_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_CAN_RX_CALLBACKS\fP   4"
.br
.ti -1c
.RI "#define \fBCAN_TX_QUEUE_SIZE\fP   256"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "HAL_StatusTypeDef \fBCAN_RegisterRxCallback\fP (\fBCanRxCallback_t\fP cb)"
.br
.ti -1c
.RI "void \fBHAL_CAN_RxFifo0MsgPendingCallback\fP (CAN_HandleTypeDef *hcan)"
.br
.ti -1c
.RI "uint8_t \fBCanTx_IsEmpty\fP (void)"
.br
.ti -1c
.RI "uint8_t \fBCanTx_IsFull\fP (void)"
.br
.ti -1c
.RI "void \fBCanTx_ProcessQueue\fP (void)"
.br
.ti -1c
.RI "HAL_StatusTypeDef \fBCAN_TX_Add_To_Queue\fP (CAN_HandleTypeDef *hcan, uint32_t canID, uint8_t dlc, const uint8_t *data)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static \fBCanRxCallback_t\fP \fBs_rxCallbacks\fP [\fBMAX_CAN_RX_CALLBACKS\fP]"
.br
.ti -1c
.RI "static uint8_t \fBs_numCallbacks\fP = 0"
.br
.ti -1c
.RI "uint16_t \fBcanTxHead\fP = 0"
.br
.ti -1c
.RI "uint16_t \fBcanTxTail\fP = 0"
.br
.ti -1c
.RI "\fBCanTxItem_t\fP \fBcanTxQueue\fP [\fBCAN_TX_QUEUE_SIZE\fP]"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CAN_TX_QUEUE_SIZE   256"

.PP
Definition at line 47 of file can\&.c\&.
.SS "#define MAX_CAN_RX_CALLBACKS   4"

.PP
Definition at line 12 of file can\&.c\&.
.SH "Function Documentation"
.PP 
.SS "HAL_StatusTypeDef CAN_RegisterRxCallback (\fBCanRxCallback_t\fP cb)"
Register a callback that will be called on every received CAN message on FIFO0\&. Returns HAL_OK on success, HAL_ERROR if the callback list is full\&. 
.PP
Definition at line 18 of file can\&.c\&.
.PP
References MAX_CAN_RX_CALLBACKS, s_numCallbacks, and s_rxCallbacks\&.
.PP
Referenced by IVT_CAN_Setup(), and Precharge_CAN_Init()\&.
.SS "HAL_StatusTypeDef CAN_TX_Add_To_Queue (CAN_HandleTypeDef * hcan, uint32_t canID, uint8_t dlc, const uint8_t * data)"

.PP
Definition at line 107 of file can\&.c\&.
.PP
References CAN_TX_QUEUE_SIZE, CanTx_IsFull(), canTxHead, canTxQueue, CanTxItem_t::data, CanTxItem_t::dlc, CanTxItem_t::hcan, and CanTxItem_t::id\&.
.PP
Referenced by Slaves_CAN_SendMessage()\&.
.SS "uint8_t CanTx_IsEmpty (void)"

.PP
Definition at line 61 of file can\&.c\&.
.PP
References canTxHead, and canTxTail\&.
.PP
Referenced by CanTx_ProcessQueue()\&.
.SS "uint8_t CanTx_IsFull (void)"

.PP
Definition at line 66 of file can\&.c\&.
.PP
References CAN_TX_QUEUE_SIZE, canTxHead, and canTxTail\&.
.PP
Referenced by CAN_TX_Add_To_Queue()\&.
.SS "void CanTx_ProcessQueue (void)"

.PP
Definition at line 72 of file can\&.c\&.
.PP
References CAN_TX_QUEUE_SIZE, CanTx_IsEmpty(), canTxQueue, canTxTail, CanTxItem_t::data, CanTxItem_t::dlc, CanTxItem_t::hcan, and CanTxItem_t::id\&.
.PP
Referenced by brain_loop()\&.
.SS "void HAL_CAN_RxFifo0MsgPendingCallback (CAN_HandleTypeDef * hcan)"

.PP
Definition at line 27 of file can\&.c\&.
.PP
References rxData, s_numCallbacks, and s_rxCallbacks\&.
.SH "Variable Documentation"
.PP 
.SS "uint16_t canTxHead = 0"

.PP
Definition at line 56 of file can\&.c\&.
.PP
Referenced by CAN_TX_Add_To_Queue(), CanTx_IsEmpty(), and CanTx_IsFull()\&.
.SS "\fBCanTxItem_t\fP canTxQueue[\fBCAN_TX_QUEUE_SIZE\fP]"

.PP
Definition at line 58 of file can\&.c\&.
.PP
Referenced by CAN_TX_Add_To_Queue(), and CanTx_ProcessQueue()\&.
.SS "uint16_t canTxTail = 0"

.PP
Definition at line 57 of file can\&.c\&.
.PP
Referenced by CanTx_IsEmpty(), CanTx_IsFull(), and CanTx_ProcessQueue()\&.
.SS "uint8_t s_numCallbacks = 0\fC [static]\fP"

.PP
Definition at line 16 of file can\&.c\&.
.PP
Referenced by CAN_RegisterRxCallback(), and HAL_CAN_RxFifo0MsgPendingCallback()\&.
.SS "\fBCanRxCallback_t\fP s_rxCallbacks[\fBMAX_CAN_RX_CALLBACKS\fP]\fC [static]\fP"

.PP
Definition at line 15 of file can\&.c\&.
.PP
Referenced by CAN_RegisterRxCallback(), and HAL_CAN_RxFifo0MsgPendingCallback()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
