.TH "Core/Inc/can.h" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Inc/can.h
.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBCanRxCallback_t\fP) (const CAN_RxHeaderTypeDef *hdr, const uint8_t *data)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "HAL_StatusTypeDef \fBCAN_RegisterRxCallback\fP (\fBCanRxCallback_t\fP cb)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void(* CanRxCallback_t) (const CAN_RxHeaderTypeDef *hdr, const uint8_t *data)"

.PP
Definition at line 13 of file can\&.h\&.
.SH "Function Documentation"
.PP 
.SS "HAL_StatusTypeDef CAN_RegisterRxCallback (\fBCanRxCallback_t\fP cb)"
Register a callback that will be called on every received CAN message on FIFO0\&. Returns HAL_OK on success, HAL_ERROR if the callback list is full\&. 
.PP
Definition at line 18 of file can\&.c\&.
.PP
References MAX_CAN_RX_CALLBACKS, s_numCallbacks, and s_rxCallbacks\&.
.PP
Referenced by IVT_CAN_Setup(), and Precharge_CAN_Init()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
