.TH "Core/Src/contactors.c" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Src/contactors.c
.SH SYNOPSIS
.br
.PP
\fC#include 'contactors\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBOpenAllContactors\fP (void)"
.br
.ti -1c
.RI "void \fBOpenPreCarga\fP (void)"
.br
.ti -1c
.RI "void \fBOpenAIR_negativo\fP (void)"
.br
.ti -1c
.RI "void \fBOpenAIR_positivo\fP (void)"
.br
.ti -1c
.RI "void \fBOpenDescarga\fP (void)"
.br
.ti -1c
.RI "void \fBClosePreCarga\fP (void)"
.br
.ti -1c
.RI "void \fBCloseAIR_negativo\fP (void)"
.br
.ti -1c
.RI "void \fBCloseAIR_positivo\fP (void)"
.br
.ti -1c
.RI "void \fBCloseDescarga\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void CloseAIR_negativo (void)"

.PP
Definition at line 45 of file contactors\&.c\&.
.PP
References CONTACT_AIR_negativo_GPIO_Port, and CONTACT_AIR_negativo_Pin\&.
.PP
Referenced by Precharge_Update()\&.
.SS "void CloseAIR_positivo (void)"

.PP
Definition at line 51 of file contactors\&.c\&.
.PP
References CONTACT_AIR_positivo_GPIO_Port, and CONTACT_AIR_positivo_Pin\&.
.PP
Referenced by Precharge_Update()\&.
.SS "void CloseDescarga (void)"

.PP
Definition at line 56 of file contactors\&.c\&.
.PP
References CONTACT_DSCH_GPIO_Port, and CONTACT_DSCH_Pin\&.
.SS "void ClosePreCarga (void)"

.PP
Definition at line 39 of file contactors\&.c\&.
.PP
References CONTACT_PRE_GPIO_Port, and CONTACT_PRE_Pin\&.
.PP
Referenced by Precharge_Update()\&.
.SS "void OpenAIR_negativo (void)"

.PP
Definition at line 23 of file contactors\&.c\&.
.PP
References CONTACT_AIR_negativo_GPIO_Port, and CONTACT_AIR_negativo_Pin\&.
.PP
Referenced by OpenAllContactors()\&.
.SS "void OpenAIR_positivo (void)"

.PP
Definition at line 29 of file contactors\&.c\&.
.PP
References CONTACT_AIR_positivo_GPIO_Port, and CONTACT_AIR_positivo_Pin\&.
.PP
Referenced by OpenAllContactors()\&.
.SS "void OpenAllContactors (void)"

.PP
Definition at line 9 of file contactors\&.c\&.
.PP
References OpenAIR_negativo(), OpenAIR_positivo(), OpenDescarga(), and OpenPreCarga()\&.
.PP
Referenced by brain_start(), and Precharge_Update()\&.
.SS "void OpenDescarga (void)"

.PP
Definition at line 34 of file contactors\&.c\&.
.PP
References CONTACT_DSCH_GPIO_Port, and CONTACT_DSCH_Pin\&.
.PP
Referenced by OpenAllContactors()\&.
.SS "void OpenPreCarga (void)"

.PP
Definition at line 17 of file contactors\&.c\&.
.PP
References CONTACT_PRE_GPIO_Port, and CONTACT_PRE_Pin\&.
.PP
Referenced by OpenAllContactors(), and Precharge_Update()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
