.TH "Core/Inc/ee24.h" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Inc/ee24.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br
\fC#include 'main\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBEE24_HandleTypeDef\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEE24_ADDRESS_DEFAULT\fP   0xA0"
.br
.ti -1c
.RI "#define \fBEE24_1KBIT\fP   1"
.br
.ti -1c
.RI "#define \fBEE24_2KBIT\fP   2"
.br
.ti -1c
.RI "#define \fBEE24_4KBIT\fP   4"
.br
.ti -1c
.RI "#define \fBEE24_8KBIT\fP   8"
.br
.ti -1c
.RI "#define \fBEE24_16KBIT\fP   16"
.br
.ti -1c
.RI "#define \fBEE24_32KBIT\fP   32"
.br
.ti -1c
.RI "#define \fBEE24_64KBIT\fP   64"
.br
.ti -1c
.RI "#define \fBEE24_128KBIT\fP   128"
.br
.ti -1c
.RI "#define \fBEE24_256KBIT\fP   256"
.br
.ti -1c
.RI "#define \fBEE24_512KBIT\fP   512"
.br
.ti -1c
.RI "#define \fBEE24_RTOS_DISABLE\fP   0"
.br
.ti -1c
.RI "#define \fBEE24_RTOS_CMSIS_V1\fP   1"
.br
.ti -1c
.RI "#define \fBEE24_RTOS_CMSIS_V2\fP   2"
.br
.ti -1c
.RI "#define \fBEE24_RTOS_THREADX\fP   3"
.br
.ti -1c
.RI "#define \fBEE24_SIZE\fP   \fBEE24_8KBIT\fP"
.br
.ti -1c
.RI "#define \fBEE24_RTOS\fP   \fBEE24_RTOS_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBEE24_USE_WP_PIN\fP   false"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBEE24_Init\fP (\fBEE24_HandleTypeDef\fP *Handle, I2C_HandleTypeDef *HI2c, uint8_t I2CAddress)"
.br
.RI "Initialize EEPROM handle\&. "
.ti -1c
.RI "bool \fBEE24_Read\fP (\fBEE24_HandleTypeDef\fP *Handle, uint32_t Address, uint8_t *Data, size_t Len, uint32_t Timeout)"
.br
.RI "Read from Memory\&. "
.ti -1c
.RI "bool \fBEE24_Write\fP (\fBEE24_HandleTypeDef\fP *Handle, uint32_t Address, uint8_t *Data, size_t Len, uint32_t Timeout)"
.br
.RI "Write to Memory\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define EE24_128KBIT   128"

.PP
Definition at line 53 of file ee24\&.h\&.
.SS "#define EE24_16KBIT   16"

.PP
Definition at line 50 of file ee24\&.h\&.
.SS "#define EE24_1KBIT   1"

.PP
Definition at line 46 of file ee24\&.h\&.
.SS "#define EE24_256KBIT   256"

.PP
Definition at line 54 of file ee24\&.h\&.
.SS "#define EE24_2KBIT   2"

.PP
Definition at line 47 of file ee24\&.h\&.
.SS "#define EE24_32KBIT   32"

.PP
Definition at line 51 of file ee24\&.h\&.
.SS "#define EE24_4KBIT   4"

.PP
Definition at line 48 of file ee24\&.h\&.
.SS "#define EE24_512KBIT   512"

.PP
Definition at line 55 of file ee24\&.h\&.
.SS "#define EE24_64KBIT   64"

.PP
Definition at line 52 of file ee24\&.h\&.
.SS "#define EE24_8KBIT   8"

.PP
Definition at line 49 of file ee24\&.h\&.
.SS "#define EE24_ADDRESS_DEFAULT   0xA0"

.PP
Definition at line 44 of file ee24\&.h\&.
.SS "#define EE24_RTOS   \fBEE24_RTOS_DISABLE\fP"

.PP
Definition at line 67 of file ee24\&.h\&.
.SS "#define EE24_RTOS_CMSIS_V1   1"

.PP
Definition at line 58 of file ee24\&.h\&.
.SS "#define EE24_RTOS_CMSIS_V2   2"

.PP
Definition at line 59 of file ee24\&.h\&.
.SS "#define EE24_RTOS_DISABLE   0"

.PP
Definition at line 57 of file ee24\&.h\&.
.SS "#define EE24_RTOS_THREADX   3"

.PP
Definition at line 60 of file ee24\&.h\&.
.SS "#define EE24_SIZE   \fBEE24_8KBIT\fP"

.PP
Definition at line 64 of file ee24\&.h\&.
.SS "#define EE24_USE_WP_PIN   false"

.PP
Definition at line 70 of file ee24\&.h\&.
.SH "Function Documentation"
.PP 
.SS "bool EE24_Init (\fBEE24_HandleTypeDef\fP * Handle, I2C_HandleTypeDef * HI2c, uint8_t I2CAddress)"

.PP
Initialize EEPROM handle\&. 
.PP
\fBNote\fP
.RS 4
Initialize EEPROM handle and set EEPROM address
.RE
.PP
\fBParameters\fP
.RS 4
\fI*Handle\fP Pointer to \fBEE24_HandleTypeDef\fP structure 
.br
\fI*HI2c\fP Pointer to I2C_HandleTypeDef structure 
.br
\fII2CAddress\fP I2C Memory address
.RE
.PP
\fBReturn values\fP
.RS 4
\fIbool\fP true or false 
.RE
.PP

.PP
Definition at line 86 of file ee24\&.c\&.
.PP
Referenced by Read_EEPROM(), and Write_EEPROM()\&.
.SS "bool EE24_Read (\fBEE24_HandleTypeDef\fP * Handle, uint32_t Address, uint8_t * Data, size_t Len, uint32_t Timeout)"

.PP
Read from Memory\&. 
.PP
\fBNote\fP
.RS 4
Read data from memory and copy to an array
.RE
.PP
\fBParameters\fP
.RS 4
\fI*Handle\fP Pointer to \fBEE24_HandleTypeDef\fP structure 
.br
\fIAddress\fP Start address for read 
.br
\fI*Data\fP Pointer to copy data from EEPROM 
.br
\fILen\fP Data length to read 
.br
\fITimeout\fP Timeout of this operation in ms
.RE
.PP
\fBReturn values\fP
.RS 4
\fIbool\fP true or false 
.RE
.PP

.PP
Definition at line 158 of file ee24\&.c\&.
.PP
Referenced by Read_EEPROM(), and Write_EEPROM()\&.
.SS "bool EE24_Write (\fBEE24_HandleTypeDef\fP * Handle, uint32_t Address, uint8_t * Data, size_t Len, uint32_t Timeout)"

.PP
Write to Memory\&. 
.PP
\fBNote\fP
.RS 4
Write an array to memory
.RE
.PP
\fBParameters\fP
.RS 4
\fI*Handle\fP Pointer to \fBEE24_HandleTypeDef\fP structure 
.br
\fIAddress\fP Start address for write 
.br
\fI*Data\fP Pointer to copy data to EEPEOM 
.br
\fILen\fP Data length to write 
.br
\fITimeout\fP Timeout of this operation in ms
.RE
.PP
\fBReturn values\fP
.RS 4
\fIbool\fP true or false 
.RE
.PP

.PP
Definition at line 199 of file ee24\&.c\&.
.PP
Referenced by Write_EEPROM()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
