.TH "EEPROM_Comms" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEPROM_Comms
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <eeprom_utils\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "I2C_HandleTypeDef * \fBhi2c\fP"
.br
.ti -1c
.RI "UART_HandleTypeDef * \fBhuart\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file eeprom_utils\&.h\&.
.SH "Field Documentation"
.PP 
.SS "I2C_HandleTypeDef* EEPROM_Comms::hi2c"

.PP
Definition at line 19 of file eeprom_utils\&.h\&.
.PP
Referenced by Read_EEPROM(), and Write_EEPROM()\&.
.SS "UART_HandleTypeDef* EEPROM_Comms::huart"

.PP
Definition at line 20 of file eeprom_utils\&.h\&.
.PP
Referenced by Read_EEPROM(), and Write_EEPROM()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
