.TH "ErrorStatus_t" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ErrorStatus_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <brain\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBerrorCounter\fP"
.br
.ti -1c
.RI "bool \fBerrorSDC\fP"
.br
.ti -1c
.RI "bool \fBerrorIMD\fP"
.br
.ti -1c
.RI "bool \fBerrorContactorsMismatch\fP"
.br
.ti -1c
.RI "bool \fBerrorTimer\fP"
.br
.ti -1c
.RI "bool \fBerrorCAN\fP"
.br
.ti -1c
.RI "bool \fBerrorOvervoltage\fP"
.br
.ti -1c
.RI "bool \fBerrorOvercurrent\fP"
.br
.ti -1c
.RI "bool \fBerrorOW\fP"
.br
.ti -1c
.RI "bool \fBerrorBMS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file brain\&.h\&.
.SH "Field Documentation"
.PP 
.SS "bool ErrorStatus_t::errorBMS"

.PP
Definition at line 54 of file brain\&.h\&.
.SS "bool ErrorStatus_t::errorCAN"

.PP
Definition at line 50 of file brain\&.h\&.
.SS "bool ErrorStatus_t::errorContactorsMismatch"

.PP
Definition at line 48 of file brain\&.h\&.
.SS "int ErrorStatus_t::errorCounter"

.PP
Definition at line 45 of file brain\&.h\&.
.SS "bool ErrorStatus_t::errorIMD"

.PP
Definition at line 47 of file brain\&.h\&.
.SS "bool ErrorStatus_t::errorOvercurrent"

.PP
Definition at line 52 of file brain\&.h\&.
.SS "bool ErrorStatus_t::errorOvervoltage"

.PP
Definition at line 51 of file brain\&.h\&.
.SS "bool ErrorStatus_t::errorOW"

.PP
Definition at line 53 of file brain\&.h\&.
.SS "bool ErrorStatus_t::errorSDC"

.PP
Definition at line 46 of file brain\&.h\&.
.SS "bool ErrorStatus_t::errorTimer"

.PP
Definition at line 49 of file brain\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
