.TH "Core/Inc/fan_management.h" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Inc/fan_management.h
.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBpid_ctrl_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBtemp_ctrl_method_t\fP { \fBTEMP_CTRL_MEAN_OF_TOP_N\fP = 0, \fBTEMP_CTRL_MEDIAN_OF_ALL\fP = 1, \fBTEMP_CTRL_MAX_OF_ALL\fP = 2 }"
.br
.ti -1c
.RI "enum \fBzn_style_t\fP { \fBZN_PID_CLASSIC\fP = 0, \fBZN_PI\fP, \fBZN_P\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPID_Init\fP (\fBpid_ctrl_t\fP *pid, float Kp, float Ki, float Kd, float Ts_sec, float out_min, float out_max)"
.br
.ti -1c
.RI "void \fBPID_SetTunings\fP (\fBpid_ctrl_t\fP *pid, float Kp, float Ki, float Kd)"
.br
.ti -1c
.RI "void \fBPID_FromZieglerNichols\fP (\fBpid_ctrl_t\fP *pid, float Ku, float Tu, \fBzn_style_t\fP style)"
.br
.ti -1c
.RI "float \fBPID_Update\fP (\fBpid_ctrl_t\fP *pid, float measurement)"
.br
.ti -1c
.RI "float \fBFanMgr_ComputeControlTemp\fP (const float *temps, size_t num_temps, \fBtemp_ctrl_method_t\fP method, size_t top_n)"
.br
.ti -1c
.RI "uint8_t \fBFanMgr_UpdatePWM\fP (\fBpid_ctrl_t\fP *pid, const float *temps, size_t num_temps, \fBtemp_ctrl_method_t\fP method, size_t top_n)"
.br
.ti -1c
.RI "static uint8_t \fBFanMgr_ClampPWM\fP (float u)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBtemp_ctrl_method_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITEMP_CTRL_MEAN_OF_TOP_N \fP\fP
.TP
\fB\fITEMP_CTRL_MEDIAN_OF_ALL \fP\fP
.TP
\fB\fITEMP_CTRL_MAX_OF_ALL \fP\fP
.PP
Definition at line 20 of file fan_management\&.h\&.
.SS "enum \fBzn_style_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIZN_PID_CLASSIC \fP\fP
.TP
\fB\fIZN_PI \fP\fP
.TP
\fB\fIZN_P \fP\fP
.PP
Definition at line 27 of file fan_management\&.h\&.
.SH "Function Documentation"
.PP 
.SS "static uint8_t FanMgr_ClampPWM (float u)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 71 of file fan_management\&.h\&.
.PP
Referenced by FanMgr_UpdatePWM()\&.
.SS "float FanMgr_ComputeControlTemp (const float * temps, size_t num_temps, \fBtemp_ctrl_method_t\fP method, size_t top_n)"

.PP
Definition at line 155 of file fan_management\&.c\&.
.PP
References cmp_asc(), cmp_desc(), TEMP_CTRL_MAX_OF_ALL, TEMP_CTRL_MEAN_OF_TOP_N, and TEMP_CTRL_MEDIAN_OF_ALL\&.
.PP
Referenced by FanMgr_UpdatePWM()\&.
.SS "uint8_t FanMgr_UpdatePWM (\fBpid_ctrl_t\fP * pid, const float * temps, size_t num_temps, \fBtemp_ctrl_method_t\fP method, size_t top_n)"

.PP
Definition at line 213 of file fan_management\&.c\&.
.PP
References FanMgr_ClampPWM(), FanMgr_ComputeControlTemp(), and PID_Update()\&.
.SS "void PID_FromZieglerNichols (\fBpid_ctrl_t\fP * pid, float Ku, float Tu, \fBzn_style_t\fP style)"

.PP
Definition at line 74 of file fan_management\&.c\&.
.PP
References PID_SetTunings(), ZN_P, ZN_PI, and ZN_PID_CLASSIC\&.
.SS "void PID_Init (\fBpid_ctrl_t\fP * pid, float Kp, float Ki, float Kd, float Ts_sec, float out_min, float out_max)"

.PP
Definition at line 45 of file fan_management\&.c\&.
.PP
References pid_ctrl_t::integrator, pid_ctrl_t::Kd, pid_ctrl_t::Ki, pid_ctrl_t::Kp, pid_ctrl_t::out_max, pid_ctrl_t::out_min, pid_ctrl_t::prev_error, pid_ctrl_t::prev_measurement, pid_ctrl_t::setpoint, and pid_ctrl_t::Ts\&.
.SS "void PID_SetTunings (\fBpid_ctrl_t\fP * pid, float Kp, float Ki, float Kd)"

.PP
Definition at line 65 of file fan_management\&.c\&.
.PP
References pid_ctrl_t::Kd, pid_ctrl_t::Ki, and pid_ctrl_t::Kp\&.
.PP
Referenced by PID_FromZieglerNichols()\&.
.SS "float PID_Update (\fBpid_ctrl_t\fP * pid, float measurement)"

.PP
Definition at line 111 of file fan_management\&.c\&.
.PP
References pid_ctrl_t::integrator, pid_ctrl_t::Kd, pid_ctrl_t::Ki, pid_ctrl_t::Kp, pid_ctrl_t::out_max, pid_ctrl_t::out_min, pid_ctrl_t::prev_error, pid_ctrl_t::prev_measurement, pid_ctrl_t::setpoint, and pid_ctrl_t::Ts\&.
.PP
Referenced by FanMgr_UpdatePWM()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
