.TH "Core/Inc/main.h" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Inc/main.h \- : Header for \fBmain\&.c\fP file\&. This file contains the common defines of the application\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f4xx_hal\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTOTAL_IC\fP   1"
.br
.ti -1c
.RI "#define \fBTOTAL_CELL\fP   12"
.br
.ti -1c
.RI "#define \fBTOTAL_AD68\fP   1"
.br
.ti -1c
.RI "#define \fBRTH_PER_MODULE\fP   6"
.br
.ti -1c
.RI "#define \fBOW_RATIO_MIN\fP   0\&.85f"
.br
.ti -1c
.RI "#define \fBOW_RATIO_MAX\fP   0\&.95f"
.br
.ti -1c
.RI "#define \fBOW_UV_IGNORE_THRESH\fP   0\&.10f"
.br
.ti -1c
.RI "#define \fBOW_OPEN_EDGE\fP   0\&.80f"
.br
.ti -1c
.RI "#define \fBB1_Pin\fP   GPIO_PIN_13"
.br
.ti -1c
.RI "#define \fBB1_GPIO_Port\fP   GPIOC"
.br
.ti -1c
.RI "#define \fBB1_EXTI_IRQn\fP   EXTI15_10_IRQn"
.br
.ti -1c
.RI "#define \fBBT_USART2_TX_Pin\fP   GPIO_PIN_2"
.br
.ti -1c
.RI "#define \fBBT_USART2_TX_GPIO_Port\fP   GPIOA"
.br
.ti -1c
.RI "#define \fBBT_USART2_RX_Pin\fP   GPIO_PIN_3"
.br
.ti -1c
.RI "#define \fBBT_USART2_RX_GPIO_Port\fP   GPIOA"
.br
.ti -1c
.RI "#define \fBBMS_CS_Pin\fP   GPIO_PIN_4"
.br
.ti -1c
.RI "#define \fBBMS_CS_GPIO_Port\fP   GPIOA"
.br
.ti -1c
.RI "#define \fBCONTACT_DSCH_Pin\fP   GPIO_PIN_4"
.br
.ti -1c
.RI "#define \fBCONTACT_DSCH_GPIO_Port\fP   GPIOC"
.br
.ti -1c
.RI "#define \fBCONTACT_PRE_Pin\fP   GPIO_PIN_5"
.br
.ti -1c
.RI "#define \fBCONTACT_PRE_GPIO_Port\fP   GPIOC"
.br
.ti -1c
.RI "#define \fBCONTACT_AIR_positivo_Pin\fP   GPIO_PIN_0"
.br
.ti -1c
.RI "#define \fBCONTACT_AIR_positivo_GPIO_Port\fP   GPIOB"
.br
.ti -1c
.RI "#define \fBCONTACT_AIR_negativo_Pin\fP   GPIO_PIN_1"
.br
.ti -1c
.RI "#define \fBCONTACT_AIR_negativo_GPIO_Port\fP   GPIOB"
.br
.ti -1c
.RI "#define \fBLED_BLUE_Pin\fP   GPIO_PIN_2"
.br
.ti -1c
.RI "#define \fBLED_BLUE_GPIO_Port\fP   GPIOB"
.br
.ti -1c
.RI "#define \fBLED_RED_Pin\fP   GPIO_PIN_10"
.br
.ti -1c
.RI "#define \fBLED_RED_GPIO_Port\fP   GPIOB"
.br
.ti -1c
.RI "#define \fBCHARGER_CAN_RX_Pin\fP   GPIO_PIN_12"
.br
.ti -1c
.RI "#define \fBCHARGER_CAN_RX_GPIO_Port\fP   GPIOB"
.br
.ti -1c
.RI "#define \fBCHARGER_CAN_TX_Pin\fP   GPIO_PIN_13"
.br
.ti -1c
.RI "#define \fBCHARGER_CAN_TX_GPIO_Port\fP   GPIOB"
.br
.ti -1c
.RI "#define \fBAUX_SENS_SDA_Pin\fP   GPIO_PIN_9"
.br
.ti -1c
.RI "#define \fBAUX_SENS_SDA_GPIO_Port\fP   GPIOC"
.br
.ti -1c
.RI "#define \fBAUX_SENS_SCL_Pin\fP   GPIO_PIN_8"
.br
.ti -1c
.RI "#define \fBAUX_SENS_SCL_GPIO_Port\fP   GPIOA"
.br
.ti -1c
.RI "#define \fBBMS_CAN_RX_Pin\fP   GPIO_PIN_11"
.br
.ti -1c
.RI "#define \fBBMS_CAN_RX_GPIO_Port\fP   GPIOA"
.br
.ti -1c
.RI "#define \fBBMS_CAN_TX_Pin\fP   GPIO_PIN_12"
.br
.ti -1c
.RI "#define \fBBMS_CAN_TX_GPIO_Port\fP   GPIOA"
.br
.ti -1c
.RI "#define \fBBMS_INT_Pin\fP   GPIO_PIN_5"
.br
.ti -1c
.RI "#define \fBBMS_INT_GPIO_Port\fP   GPIOB"
.br
.ti -1c
.RI "#define \fBBMS_WAKE_Pin\fP   GPIO_PIN_6"
.br
.ti -1c
.RI "#define \fBBMS_WAKE_GPIO_Port\fP   GPIOB"
.br
.ti -1c
.RI "#define \fBBMS_MSTR_Pin\fP   GPIO_PIN_7"
.br
.ti -1c
.RI "#define \fBBMS_MSTR_GPIO_Port\fP   GPIOB"
.br
.ti -1c
.RI "#define \fBEEPROM_SCL_Pin\fP   GPIO_PIN_8"
.br
.ti -1c
.RI "#define \fBEEPROM_SCL_GPIO_Port\fP   GPIOB"
.br
.ti -1c
.RI "#define \fBEEPROM_SDA_Pin\fP   GPIO_PIN_9"
.br
.ti -1c
.RI "#define \fBEEPROM_SDA_GPIO_Port\fP   GPIOB"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBError_Handler\fP (void)"
.br
.RI "This function is executed in case of error occurrence\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "SPI_HandleTypeDef \fBhspi1\fP"
.br
.ti -1c
.RI "I2C_HandleTypeDef \fBhi2c1\fP"
.br
.ti -1c
.RI "I2C_HandleTypeDef \fBhi2c3\fP"
.br
.ti -1c
.RI "UART_HandleTypeDef \fBhuart1\fP"
.br
.ti -1c
.RI "UART_HandleTypeDef \fBhuart2\fP"
.br
.ti -1c
.RI "TIM_HandleTypeDef \fBhtim2\fP"
.br
.ti -1c
.RI "TIM_HandleTypeDef \fBhtim5\fP"
.br
.ti -1c
.RI "TIM_HandleTypeDef \fBhtim8\fP"
.br
.ti -1c
.RI "TIM_HandleTypeDef \fBhtim10\fP"
.br
.ti -1c
.RI "TIM_HandleTypeDef \fBhtim11\fP"
.br
.ti -1c
.RI "RTC_HandleTypeDef \fBhrtc\fP"
.br
.ti -1c
.RI "ADC_HandleTypeDef \fBhadc1\fP"
.br
.ti -1c
.RI "CAN_HandleTypeDef \fBhcan1\fP"
.br
.ti -1c
.RI "CAN_HandleTypeDef \fBhcan2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
: Header for \fBmain\&.c\fP file\&. This file contains the common defines of the application\&. 


.PP
\fBAttention\fP
.RS 4

.RE
.PP
Copyright (c) 2025 STMicroelectronics\&. All rights reserved\&.
.PP
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component\&. If no LICENSE file comes with this software, it is provided AS-IS\&. 
.PP
Definition in file \fBmain\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define AUX_SENS_SCL_GPIO_Port   GPIOA"

.PP
Definition at line 114 of file main\&.h\&.
.SS "#define AUX_SENS_SCL_Pin   GPIO_PIN_8"

.PP
Definition at line 113 of file main\&.h\&.
.SS "#define AUX_SENS_SDA_GPIO_Port   GPIOC"

.PP
Definition at line 112 of file main\&.h\&.
.SS "#define AUX_SENS_SDA_Pin   GPIO_PIN_9"

.PP
Definition at line 111 of file main\&.h\&.
.SS "#define B1_EXTI_IRQn   EXTI15_10_IRQn"

.PP
Definition at line 88 of file main\&.h\&.
.SS "#define B1_GPIO_Port   GPIOC"

.PP
Definition at line 87 of file main\&.h\&.
.SS "#define B1_Pin   GPIO_PIN_13"

.PP
Definition at line 86 of file main\&.h\&.
.SS "#define BMS_CAN_RX_GPIO_Port   GPIOA"

.PP
Definition at line 116 of file main\&.h\&.
.SS "#define BMS_CAN_RX_Pin   GPIO_PIN_11"

.PP
Definition at line 115 of file main\&.h\&.
.SS "#define BMS_CAN_TX_GPIO_Port   GPIOA"

.PP
Definition at line 118 of file main\&.h\&.
.SS "#define BMS_CAN_TX_Pin   GPIO_PIN_12"

.PP
Definition at line 117 of file main\&.h\&.
.SS "#define BMS_CS_GPIO_Port   GPIOA"

.PP
Definition at line 94 of file main\&.h\&.
.SS "#define BMS_CS_Pin   GPIO_PIN_4"

.PP
Definition at line 93 of file main\&.h\&.
.SS "#define BMS_INT_GPIO_Port   GPIOB"

.PP
Definition at line 120 of file main\&.h\&.
.SS "#define BMS_INT_Pin   GPIO_PIN_5"

.PP
Definition at line 119 of file main\&.h\&.
.SS "#define BMS_MSTR_GPIO_Port   GPIOB"

.PP
Definition at line 124 of file main\&.h\&.
.SS "#define BMS_MSTR_Pin   GPIO_PIN_7"

.PP
Definition at line 123 of file main\&.h\&.
.SS "#define BMS_WAKE_GPIO_Port   GPIOB"

.PP
Definition at line 122 of file main\&.h\&.
.SS "#define BMS_WAKE_Pin   GPIO_PIN_6"

.PP
Definition at line 121 of file main\&.h\&.
.SS "#define BT_USART2_RX_GPIO_Port   GPIOA"

.PP
Definition at line 92 of file main\&.h\&.
.SS "#define BT_USART2_RX_Pin   GPIO_PIN_3"

.PP
Definition at line 91 of file main\&.h\&.
.SS "#define BT_USART2_TX_GPIO_Port   GPIOA"

.PP
Definition at line 90 of file main\&.h\&.
.SS "#define BT_USART2_TX_Pin   GPIO_PIN_2"

.PP
Definition at line 89 of file main\&.h\&.
.SS "#define CHARGER_CAN_RX_GPIO_Port   GPIOB"

.PP
Definition at line 108 of file main\&.h\&.
.SS "#define CHARGER_CAN_RX_Pin   GPIO_PIN_12"

.PP
Definition at line 107 of file main\&.h\&.
.SS "#define CHARGER_CAN_TX_GPIO_Port   GPIOB"

.PP
Definition at line 110 of file main\&.h\&.
.SS "#define CHARGER_CAN_TX_Pin   GPIO_PIN_13"

.PP
Definition at line 109 of file main\&.h\&.
.SS "#define CONTACT_AIR_negativo_GPIO_Port   GPIOB"

.PP
Definition at line 102 of file main\&.h\&.
.SS "#define CONTACT_AIR_negativo_Pin   GPIO_PIN_1"

.PP
Definition at line 101 of file main\&.h\&.
.SS "#define CONTACT_AIR_positivo_GPIO_Port   GPIOB"

.PP
Definition at line 100 of file main\&.h\&.
.SS "#define CONTACT_AIR_positivo_Pin   GPIO_PIN_0"

.PP
Definition at line 99 of file main\&.h\&.
.SS "#define CONTACT_DSCH_GPIO_Port   GPIOC"

.PP
Definition at line 96 of file main\&.h\&.
.SS "#define CONTACT_DSCH_Pin   GPIO_PIN_4"

.PP
Definition at line 95 of file main\&.h\&.
.SS "#define CONTACT_PRE_GPIO_Port   GPIOC"

.PP
Definition at line 98 of file main\&.h\&.
.SS "#define CONTACT_PRE_Pin   GPIO_PIN_5"

.PP
Definition at line 97 of file main\&.h\&.
.SS "#define EEPROM_SCL_GPIO_Port   GPIOB"

.PP
Definition at line 126 of file main\&.h\&.
.SS "#define EEPROM_SCL_Pin   GPIO_PIN_8"

.PP
Definition at line 125 of file main\&.h\&.
.SS "#define EEPROM_SDA_GPIO_Port   GPIOB"

.PP
Definition at line 128 of file main\&.h\&.
.SS "#define EEPROM_SDA_Pin   GPIO_PIN_9"

.PP
Definition at line 127 of file main\&.h\&.
.SS "#define LED_BLUE_GPIO_Port   GPIOB"

.PP
Definition at line 104 of file main\&.h\&.
.SS "#define LED_BLUE_Pin   GPIO_PIN_2"

.PP
Definition at line 103 of file main\&.h\&.
.SS "#define LED_RED_GPIO_Port   GPIOB"

.PP
Definition at line 106 of file main\&.h\&.
.SS "#define LED_RED_Pin   GPIO_PIN_10"

.PP
Definition at line 105 of file main\&.h\&.
.SS "#define OW_OPEN_EDGE   0\&.80f"

.PP
Definition at line 74 of file main\&.h\&.
.SS "#define OW_RATIO_MAX   0\&.95f"

.PP
Definition at line 72 of file main\&.h\&.
.SS "#define OW_RATIO_MIN   0\&.85f"

.PP
Definition at line 71 of file main\&.h\&.
.SS "#define OW_UV_IGNORE_THRESH   0\&.10f"

.PP
Definition at line 73 of file main\&.h\&.
.SS "#define RTH_PER_MODULE   6"

.PP
Definition at line 69 of file main\&.h\&.
.SS "#define TOTAL_AD68   1"

.PP
Definition at line 67 of file main\&.h\&.
.SS "#define TOTAL_CELL   12"

.PP
Definition at line 65 of file main\&.h\&.
.SS "#define TOTAL_IC   1"

.PP
Definition at line 64 of file main\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void Error_Handler (void)"

.PP
This function is executed in case of error occurrence\&. 
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 878 of file main\&.c\&.
.PP
Referenced by HAL_ADC_MspInit(), HAL_RTC_MspInit(), HAL_UART_MspInit(), MX_ADC1_Init(), MX_CAN1_Init(), MX_CAN2_Init(), MX_I2C1_Init(), MX_I2C3_Init(), MX_RTC_Init(), MX_SPI1_Init(), MX_TIM10_Init(), MX_TIM11_Init(), MX_TIM2_Init(), MX_TIM5_Init(), MX_TIM8_Init(), MX_USART1_UART_Init(), MX_USART2_UART_Init(), printfDma(), printfDmaBT(), and SystemClock_Config()\&.
.SH "Variable Documentation"
.PP 
.SS "ADC_HandleTypeDef hadc1"

.PP
Definition at line 45 of file main\&.c\&.
.SS "CAN_HandleTypeDef hcan1"

.PP
Definition at line 48 of file main\&.c\&.
.PP
Referenced by brain_loop(), and brain_start()\&.
.SS "CAN_HandleTypeDef hcan2"

.PP
Definition at line 49 of file main\&.c\&.
.PP
Referenced by MX_CAN2_Init()\&.
.SS "I2C_HandleTypeDef hi2c1"

.PP
Definition at line 51 of file main\&.c\&.
.PP
Referenced by MX_I2C1_Init()\&.
.SS "I2C_HandleTypeDef hi2c3"

.PP
Definition at line 52 of file main\&.c\&.
.PP
Referenced by MX_I2C3_Init()\&.
.SS "RTC_HandleTypeDef hrtc"

.PP
Definition at line 54 of file main\&.c\&.
.PP
Referenced by HAL_RTC_MspDeInit(), HAL_RTC_MspInit(), and MX_RTC_Init()\&.
.SS "SPI_HandleTypeDef hspi1"

.PP
Definition at line 56 of file main\&.c\&.
.PP
Referenced by MX_SPI1_Init()\&.
.SS "TIM_HandleTypeDef htim10"

.PP
Definition at line 61 of file main\&.c\&.
.PP
Referenced by brain_start(), and HAL_TIM_PeriodElapsedCallback()\&.
.SS "TIM_HandleTypeDef htim11"

.PP
Definition at line 62 of file main\&.c\&.
.PP
Referenced by brain_start()\&.
.SS "TIM_HandleTypeDef htim2"

.PP
Definition at line 58 of file main\&.c\&.
.PP
Referenced by MX_TIM2_Init()\&.
.SS "TIM_HandleTypeDef htim5"

.PP
Definition at line 59 of file main\&.c\&.
.PP
Referenced by MX_TIM5_Init()\&.
.SS "TIM_HandleTypeDef htim8"

.PP
Definition at line 60 of file main\&.c\&.
.PP
Referenced by brain_start()\&.
.SS "UART_HandleTypeDef huart1"

.PP
Definition at line 64 of file main\&.c\&.
.SS "UART_HandleTypeDef huart2"

.PP
Definition at line 65 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
