.TH "Core/Src/main.c" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Src/main.c \- : Main program body  

.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br
\fC#include 'brain\&.h'\fP
.br
\fC#include 'isa_ivt\-s\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPUTCHAR_PROTOTYPE\fP   int \fB__io_putchar\fP(int \fBch\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSystemClock_Config\fP (void)"
.br
.RI "System Clock Configuration\&. "
.ti -1c
.RI "static void \fBMX_GPIO_Init\fP (void)"
.br
.RI "GPIO Initialization Function\&. "
.ti -1c
.RI "static void \fBMX_DMA_Init\fP (void)"
.br
.ti -1c
.RI "static void \fBMX_USART1_UART_Init\fP (void)"
.br
.RI "USART1 Initialization Function\&. "
.ti -1c
.RI "static void \fBMX_SPI1_Init\fP (void)"
.br
.RI "SPI1 Initialization Function\&. "
.ti -1c
.RI "static void \fBMX_TIM2_Init\fP (void)"
.br
.RI "TIM2 Initialization Function\&. "
.ti -1c
.RI "static void \fBMX_TIM5_Init\fP (void)"
.br
.RI "TIM5 Initialization Function\&. "
.ti -1c
.RI "static void \fBMX_TIM8_Init\fP (void)"
.br
.RI "TIM8 Initialization Function\&. "
.ti -1c
.RI "static void \fBMX_TIM10_Init\fP (void)"
.br
.RI "TIM10 Initialization Function\&. "
.ti -1c
.RI "static void \fBMX_TIM11_Init\fP (void)"
.br
.RI "TIM11 Initialization Function\&. "
.ti -1c
.RI "static void \fBMX_I2C1_Init\fP (void)"
.br
.RI "I2C1 Initialization Function\&. "
.ti -1c
.RI "static void \fBMX_ADC1_Init\fP (void)"
.br
.RI "ADC1 Initialization Function\&. "
.ti -1c
.RI "static void \fBMX_CAN2_Init\fP (void)"
.br
.RI "CAN2 Initialization Function\&. "
.ti -1c
.RI "static void \fBMX_CAN1_Init\fP (void)"
.br
.RI "CAN1 Initialization Function\&. "
.ti -1c
.RI "static void \fBMX_RTC_Init\fP (void)"
.br
.RI "RTC Initialization Function\&. "
.ti -1c
.RI "static void \fBMX_USART2_UART_Init\fP (void)"
.br
.RI "USART2 Initialization Function\&. "
.ti -1c
.RI "static void \fBMX_I2C3_Init\fP (void)"
.br
.RI "I2C3 Initialization Function\&. "
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.RI "The application entry point\&. "
.ti -1c
.RI "void \fBError_Handler\fP (void)"
.br
.RI "This function is executed in case of error occurrence\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "ADC_HandleTypeDef \fBhadc1\fP"
.br
.ti -1c
.RI "DMA_HandleTypeDef \fBhdma_adc1\fP"
.br
.ti -1c
.RI "CAN_HandleTypeDef \fBhcan1\fP"
.br
.ti -1c
.RI "CAN_HandleTypeDef \fBhcan2\fP"
.br
.ti -1c
.RI "I2C_HandleTypeDef \fBhi2c1\fP"
.br
.ti -1c
.RI "I2C_HandleTypeDef \fBhi2c3\fP"
.br
.ti -1c
.RI "RTC_HandleTypeDef \fBhrtc\fP"
.br
.ti -1c
.RI "SPI_HandleTypeDef \fBhspi1\fP"
.br
.ti -1c
.RI "TIM_HandleTypeDef \fBhtim2\fP"
.br
.ti -1c
.RI "TIM_HandleTypeDef \fBhtim5\fP"
.br
.ti -1c
.RI "TIM_HandleTypeDef \fBhtim8\fP"
.br
.ti -1c
.RI "TIM_HandleTypeDef \fBhtim10\fP"
.br
.ti -1c
.RI "TIM_HandleTypeDef \fBhtim11\fP"
.br
.ti -1c
.RI "UART_HandleTypeDef \fBhuart1\fP"
.br
.ti -1c
.RI "UART_HandleTypeDef \fBhuart2\fP"
.br
.ti -1c
.RI "DMA_HandleTypeDef \fBhdma_usart1_tx\fP"
.br
.ti -1c
.RI "DMA_HandleTypeDef \fBhdma_usart2_tx\fP"
.br
.ti -1c
.RI "\fBPUTCHAR_PROTOTYPE\fP"
.br
.ti -1c
.RI "return \fBch\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
: Main program body 


.PP
\fBAttention\fP
.RS 4

.RE
.PP
Copyright (c) 2025 STMicroelectronics\&. All rights reserved\&.
.PP
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component\&. If no LICENSE file comes with this software, it is provided AS-IS\&. 
.PP
Definition in file \fBmain\&.c\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define PUTCHAR_PROTOTYPE   int \fB__io_putchar\fP(int \fBch\fP)"

.PP
Definition at line 92 of file main\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void Error_Handler (void)"

.PP
This function is executed in case of error occurrence\&. 
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 878 of file main\&.c\&.
.PP
Referenced by HAL_ADC_MspInit(), HAL_RTC_MspInit(), HAL_UART_MspInit(), MX_ADC1_Init(), MX_CAN1_Init(), MX_CAN2_Init(), MX_I2C1_Init(), MX_I2C3_Init(), MX_RTC_Init(), MX_SPI1_Init(), MX_TIM10_Init(), MX_TIM11_Init(), MX_TIM2_Init(), MX_TIM5_Init(), MX_TIM8_Init(), MX_USART1_UART_Init(), MX_USART2_UART_Init(), printfDma(), printfDmaBT(), and SystemClock_Config()\&.
.SS "int main (void)"

.PP
The application entry point\&. 
.PP
\fBReturn values\fP
.RS 4
\fIint\fP 
.RE
.PP

.PP
Definition at line 105 of file main\&.c\&.
.PP
References brain_loop(), brain_start(), MX_ADC1_Init(), MX_CAN1_Init(), MX_CAN2_Init(), MX_DMA_Init(), MX_GPIO_Init(), MX_I2C1_Init(), MX_I2C3_Init(), MX_RTC_Init(), MX_SPI1_Init(), MX_TIM10_Init(), MX_TIM11_Init(), MX_TIM2_Init(), MX_TIM5_Init(), MX_TIM8_Init(), MX_USART1_UART_Init(), MX_USART2_UART_Init(), and SystemClock_Config()\&.
.SS "static void MX_ADC1_Init (void)\fC [static]\fP"

.PP
ADC1 Initialization Function\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP
Configure the global features of the ADC (Clock, Resolution, Data Alignment and number of conversion)
.PP
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time\&.
.PP
Definition at line 219 of file main\&.c\&.
.PP
References Error_Handler(), and hadc1\&.
.PP
Referenced by main()\&.
.SS "static void MX_CAN1_Init (void)\fC [static]\fP"

.PP
CAN1 Initialization Function\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 271 of file main\&.c\&.
.PP
References Error_Handler(), hcan1, and IVT_CAN_Setup()\&.
.PP
Referenced by main()\&.
.SS "static void MX_CAN2_Init (void)\fC [static]\fP"

.PP
CAN2 Initialization Function\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 324 of file main\&.c\&.
.PP
References Error_Handler(), and hcan2\&.
.PP
Referenced by main()\&.
.SS "static void MX_DMA_Init (void)\fC [static]\fP"
Enable DMA controller clock 
.PP
Definition at line 764 of file main\&.c\&.
.PP
Referenced by main()\&.
.SS "static void MX_GPIO_Init (void)\fC [static]\fP"

.PP
GPIO Initialization Function\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 789 of file main\&.c\&.
.PP
References B1_GPIO_Port, B1_Pin, BMS_CS_GPIO_Port, BMS_CS_Pin, BMS_INT_Pin, BMS_MSTR_Pin, BMS_WAKE_Pin, CONTACT_AIR_negativo_Pin, CONTACT_AIR_positivo_Pin, CONTACT_DSCH_Pin, CONTACT_PRE_Pin, LED_BLUE_Pin, and LED_RED_Pin\&.
.PP
Referenced by main()\&.
.SS "static void MX_I2C1_Init (void)\fC [static]\fP"

.PP
I2C1 Initialization Function\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 361 of file main\&.c\&.
.PP
References Error_Handler(), and hi2c1\&.
.PP
Referenced by main()\&.
.SS "static void MX_I2C3_Init (void)\fC [static]\fP"

.PP
I2C3 Initialization Function\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 395 of file main\&.c\&.
.PP
References Error_Handler(), and hi2c3\&.
.PP
Referenced by main()\&.
.SS "static void MX_RTC_Init (void)\fC [static]\fP"

.PP
RTC Initialization Function\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP
Initialize RTC Only
.PP
Definition at line 429 of file main\&.c\&.
.PP
References Error_Handler(), and hrtc\&.
.PP
Referenced by main()\&.
.SS "static void MX_SPI1_Init (void)\fC [static]\fP"

.PP
SPI1 Initialization Function\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 464 of file main\&.c\&.
.PP
References Error_Handler(), and hspi1\&.
.PP
Referenced by main()\&.
.SS "static void MX_TIM10_Init (void)\fC [static]\fP"

.PP
TIM10 Initialization Function\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 638 of file main\&.c\&.
.PP
References Error_Handler(), and htim10\&.
.PP
Referenced by main()\&.
.SS "static void MX_TIM11_Init (void)\fC [static]\fP"

.PP
TIM11 Initialization Function\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 669 of file main\&.c\&.
.PP
References Error_Handler(), and htim11\&.
.PP
Referenced by main()\&.
.SS "static void MX_TIM2_Init (void)\fC [static]\fP"

.PP
TIM2 Initialization Function\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 502 of file main\&.c\&.
.PP
References Error_Handler(), and htim2\&.
.PP
Referenced by main()\&.
.SS "static void MX_TIM5_Init (void)\fC [static]\fP"

.PP
TIM5 Initialization Function\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 547 of file main\&.c\&.
.PP
References Error_Handler(), and htim5\&.
.PP
Referenced by main()\&.
.SS "static void MX_TIM8_Init (void)\fC [static]\fP"

.PP
TIM8 Initialization Function\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 592 of file main\&.c\&.
.PP
References Error_Handler(), and htim8\&.
.PP
Referenced by main()\&.
.SS "static void MX_USART1_UART_Init (void)\fC [static]\fP"

.PP
USART1 Initialization Function\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 700 of file main\&.c\&.
.PP
References Error_Handler(), and huart1\&.
.PP
Referenced by main()\&.
.SS "static void MX_USART2_UART_Init (void)\fC [static]\fP"

.PP
USART2 Initialization Function\&. 
.PP
\fBParameters\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 733 of file main\&.c\&.
.PP
References Error_Handler(), and huart2\&.
.PP
Referenced by main()\&.
.SS "void SystemClock_Config (void)"

.PP
System Clock Configuration\&. 
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP
Configure the main internal regulator output voltage
.PP
Initializes the RCC Oscillators according to the specified parameters in the RCC_OscInitTypeDef structure\&.
.PP
Initializes the CPU, AHB and APB buses clocks
.PP
Definition at line 170 of file main\&.c\&.
.PP
References Error_Handler()\&.
.PP
Referenced by main()\&.
.SH "Variable Documentation"
.PP 
.SS "return ch"

.PP
Definition at line 869 of file main\&.c\&.
.SS "ADC_HandleTypeDef hadc1"

.PP
Definition at line 45 of file main\&.c\&.
.PP
Referenced by MX_ADC1_Init(), and read_mcu_temp()\&.
.SS "CAN_HandleTypeDef hcan1"

.PP
Definition at line 48 of file main\&.c\&.
.PP
Referenced by brain_loop(), brain_start(), CAN1_RX0_IRQHandler(), IVT_CAN_Config(), IVT_CAN_Setup_AllMessages(), IVT_FAULT_CHECK(), IVT_PROCESS_SYSERRORS(), IVT_SET_BITRATE(), and MX_CAN1_Init()\&.
.SS "CAN_HandleTypeDef hcan2"

.PP
Definition at line 49 of file main\&.c\&.
.PP
Referenced by MX_CAN2_Init()\&.
.SS "DMA_HandleTypeDef hdma_adc1"

.PP
Definition at line 46 of file main\&.c\&.
.PP
Referenced by DMA2_Stream0_IRQHandler(), and HAL_ADC_MspInit()\&.
.SS "DMA_HandleTypeDef hdma_usart1_tx"

.PP
Definition at line 66 of file main\&.c\&.
.PP
Referenced by DMA2_Stream7_IRQHandler(), and HAL_UART_MspInit()\&.
.SS "DMA_HandleTypeDef hdma_usart2_tx"

.PP
Definition at line 67 of file main\&.c\&.
.PP
Referenced by DMA1_Stream6_IRQHandler(), and HAL_UART_MspInit()\&.
.SS "I2C_HandleTypeDef hi2c1"

.PP
Definition at line 51 of file main\&.c\&.
.PP
Referenced by MX_I2C1_Init()\&.
.SS "I2C_HandleTypeDef hi2c3"

.PP
Definition at line 52 of file main\&.c\&.
.PP
Referenced by MX_I2C3_Init()\&.
.SS "RTC_HandleTypeDef hrtc"

.PP
Definition at line 54 of file main\&.c\&.
.PP
Referenced by HAL_RTC_MspDeInit(), HAL_RTC_MspInit(), and MX_RTC_Init()\&.
.SS "SPI_HandleTypeDef hspi1"

.PP
Definition at line 56 of file main\&.c\&.
.PP
Referenced by MX_SPI1_Init()\&.
.SS "TIM_HandleTypeDef htim10"

.PP
Definition at line 61 of file main\&.c\&.
.PP
Referenced by brain_start(), HAL_TIM_PeriodElapsedCallback(), MX_TIM10_Init(), and TIM1_UP_TIM10_IRQHandler()\&.
.SS "TIM_HandleTypeDef htim11"

.PP
Definition at line 62 of file main\&.c\&.
.PP
Referenced by brain_start(), MX_TIM11_Init(), and TIM1_TRG_COM_TIM11_IRQHandler()\&.
.SS "TIM_HandleTypeDef htim2"

.PP
Definition at line 58 of file main\&.c\&.
.PP
Referenced by MX_TIM2_Init()\&.
.SS "TIM_HandleTypeDef htim5"

.PP
Definition at line 59 of file main\&.c\&.
.PP
Referenced by MX_TIM5_Init()\&.
.SS "TIM_HandleTypeDef htim8"

.PP
Definition at line 60 of file main\&.c\&.
.PP
Referenced by brain_start(), MX_TIM8_Init(), and TIM8_UP_TIM13_IRQHandler()\&.
.SS "UART_HandleTypeDef huart1"

.PP
Definition at line 64 of file main\&.c\&.
.PP
Referenced by MX_USART1_UART_Init(), and USART1_IRQHandler()\&.
.SS "UART_HandleTypeDef huart2"

.PP
Definition at line 65 of file main\&.c\&.
.PP
Referenced by MX_USART2_UART_Init(), and USART2_IRQHandler()\&.
.SS "PUTCHAR_PROTOTYPE"
\fBInitial value:\fP
.PP
.nf
{
    if (ch == '\n') {
        uint8_t cr = '\r';
        HAL_UART_Transmit(&huart1, &cr, 1, HAL_MAX_DELAY);
    }
    HAL_UART_Transmit(&huart1, (uint8_t*) &ch, 1, HAL_MAX_DELAY)
.fi
.PP
Definition at line 863 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
