.TH "Core/Inc/precharge.h" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Inc/precharge.h
.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPrechargeState_t\fP { \fBRX_CAN\fP, \fBSTART\fP = 0, \fBOPEN_ALL\fP, \fBSWITCH_HVNEG\fP, \fBDELAY1\fP, \fBVERIFY1\fP, \fBSWITCH_PRECHARGE\fP, \fBDELAY2\fP, \fBVERIFY2\fP, \fBVERIFY_CURRENT\fP, \fBVERIFY_BUS_VOLT\fP, \fBSWITCH_HVPOS\fP, \fBDELAY3\fP, \fBVERIFY3\fP, \fBTURN_OFF_PRECHARGE\fP, \fBVERIFY4\fP, \fBEND\fP, \fBWRONG\fP, \fBKILL\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPrecharge_Init\fP (void)"
.br
.ti -1c
.RI "void \fBPrecharge_CAN_Init\fP (void)"
.br
.ti -1c
.RI "\fBPrechargeState_t\fP \fBPrecharge_GetState\fP (void)"
.br
.ti -1c
.RI "void \fBPrecharge_Update\fP (void)"
.br
.ti -1c
.RI "void \fBPreCharge_CAN_Rx\fP (const CAN_RxHeaderTypeDef *hdr, const uint8_t *data)"
.br
.ti -1c
.RI "bool \fBVerifyHVNEG_HVPOS_States\fP (void)"
.br
.ti -1c
.RI "bool \fBIsBusVoltageOK\fP (void)"
.br
.ti -1c
.RI "bool \fBIsCurrentOK\fP (void)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBPrechargeState_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRX_CAN \fP\fP
.TP
\fB\fISTART \fP\fP
.TP
\fB\fIOPEN_ALL \fP\fP
.TP
\fB\fISWITCH_HVNEG \fP\fP
.TP
\fB\fIDELAY1 \fP\fP
.TP
\fB\fIVERIFY1 \fP\fP
.TP
\fB\fISWITCH_PRECHARGE \fP\fP
.TP
\fB\fIDELAY2 \fP\fP
.TP
\fB\fIVERIFY2 \fP\fP
.TP
\fB\fIVERIFY_CURRENT \fP\fP
.TP
\fB\fIVERIFY_BUS_VOLT \fP\fP
.TP
\fB\fISWITCH_HVPOS \fP\fP
.TP
\fB\fIDELAY3 \fP\fP
.TP
\fB\fIVERIFY3 \fP\fP
.TP
\fB\fITURN_OFF_PRECHARGE \fP\fP
.TP
\fB\fIVERIFY4 \fP\fP
.TP
\fB\fIEND \fP\fP
.TP
\fB\fIWRONG \fP\fP
.TP
\fB\fIKILL \fP\fP
.PP
Definition at line 14 of file precharge\&.h\&.
.SH "Function Documentation"
.PP 
.SS "bool IsBusVoltageOK (void)"

.PP
Definition at line 159 of file precharge\&.c\&.
.PP
Referenced by Precharge_Update()\&.
.SS "bool IsCurrentOK (void)"

.PP
Definition at line 163 of file precharge\&.c\&.
.PP
Referenced by Precharge_Update()\&.
.SS "void Precharge_CAN_Init (void)"

.PP
Definition at line 35 of file precharge\&.c\&.
.PP
References CAN_RegisterRxCallback(), and PreCharge_CAN_Rx()\&.
.PP
Referenced by brain_start()\&.
.SS "void PreCharge_CAN_Rx (const CAN_RxHeaderTypeDef * hdr, const uint8_t * data)"

.PP
Definition at line 167 of file precharge\&.c\&.
.PP
References AMS_START_PRE_CHARGE_FRAME_ID, ams_start_pre_charge_unpack(), KILL, ams_start_pre_charge_t::precharge_request, Precharge_Update(), RX_CAN, and state\&.
.PP
Referenced by Precharge_CAN_Init()\&.
.SS "\fBPrechargeState_t\fP Precharge_GetState (void)"

.PP
Definition at line 40 of file precharge\&.c\&.
.PP
References state\&.
.PP
Referenced by brain_loop()\&.
.SS "void Precharge_Init (void)"

.PP
Definition at line 30 of file precharge\&.c\&.
.PP
References delayStart, START, and state\&.
.PP
Referenced by brain_loop(), and Precharge_Update()\&.
.SS "void Precharge_Update (void)"

.PP
Definition at line 44 of file precharge\&.c\&.
.PP
References bypassChecks, CloseAIR_negativo(), CloseAIR_positivo(), ClosePreCarga(), DELAY1, DELAY2, DELAY3, delayStart, END, IsBusVoltageOK(), IsCurrentOK(), KILL, OPEN_ALL, OpenAllContactors(), OpenPreCarga(), PRECHARGE_DELAY_MS, Precharge_Init(), START, state, SWITCH_HVNEG, SWITCH_HVPOS, SWITCH_PRECHARGE, TURN_OFF_PRECHARGE, VERIFY1, VERIFY2, VERIFY3, VERIFY4, VERIFY_BUS_VOLT, VERIFY_CURRENT, VerifyHVNEG_HVPOS_States(), and WRONG\&.
.PP
Referenced by brain_loop(), and PreCharge_CAN_Rx()\&.
.SS "bool VerifyHVNEG_HVPOS_States (void)"

.PP
Definition at line 155 of file precharge\&.c\&.
.PP
Referenced by Precharge_Update()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
