.TH "Core/Src/temperatures.c" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Src/temperatures.c
.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br
\fC#include 'brain\&.h'\fP
.br
\fC#include 'temperatures\&.h'\fP
.br
\fC#include 'math\&.h'\fP
.br
\fC#include 'uartDMA\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTS_CAL1_ADDR\fP   ((uint16_t*)0x1FFF7A2C)"
.br
.ti -1c
.RI "#define \fBTS_CAL2_ADDR\fP   ((uint16_t*)0x1FFF7A2E)"
.br
.ti -1c
.RI "#define \fBTEMP_CAL1_TEMPC\fP   30\&.0f"
.br
.ti -1c
.RI "#define \fBTEMP_CAL2_TEMPC\fP   110\&.0f"
.br
.ti -1c
.RI "#define \fBTEMP_V25\fP   0\&.76f"
.br
.ti -1c
.RI "#define \fBTEMP_AVG_SLOPE\fP   0\&.0025f"
.br
.ti -1c
.RI "#define \fBVDDA_ASSUMED\fP   3\&.3f"
.br
.ti -1c
.RI "#define \fBADC_MAX_12BIT\fP   1023\&.0f"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBread_mcu_temp\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "ADC_HandleTypeDef \fBhadc1\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ADC_MAX_12BIT   1023\&.0f"

.PP
Definition at line 26 of file temperatures\&.c\&.
.SS "#define TEMP_AVG_SLOPE   0\&.0025f"

.PP
Definition at line 24 of file temperatures\&.c\&.
.SS "#define TEMP_CAL1_TEMPC   30\&.0f"

.PP
Definition at line 20 of file temperatures\&.c\&.
.SS "#define TEMP_CAL2_TEMPC   110\&.0f"

.PP
Definition at line 21 of file temperatures\&.c\&.
.SS "#define TEMP_V25   0\&.76f"

.PP
Definition at line 23 of file temperatures\&.c\&.
.SS "#define TS_CAL1_ADDR   ((uint16_t*)0x1FFF7A2C)"

.PP
Definition at line 17 of file temperatures\&.c\&.
.SS "#define TS_CAL2_ADDR   ((uint16_t*)0x1FFF7A2E)"

.PP
Definition at line 18 of file temperatures\&.c\&.
.SS "#define VDDA_ASSUMED   3\&.3f"

.PP
Definition at line 25 of file temperatures\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void read_mcu_temp (void)"

.PP
Definition at line 28 of file temperatures\&.c\&.
.PP
References ADC_MAX_12BIT, hadc1, TEMP_AVG_SLOPE, TEMP_V25, and VDDA_ASSUMED\&.
.PP
Referenced by brain_loop()\&.
.SH "Variable Documentation"
.PP 
.SS "ADC_HandleTypeDef hadc1"

.PP
Definition at line 45 of file main\&.c\&.
.PP
Referenced by MX_ADC1_Init(), and read_mcu_temp()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
