.TH "Core/Inc/temperatures.h" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Inc/temperatures.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBread_mcu_temp\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void read_mcu_temp (void)"

.PP
Definition at line 28 of file temperatures\&.c\&.
.PP
References ADC_MAX_12BIT, hadc1, TEMP_AVG_SLOPE, TEMP_V25, and VDDA_ASSUMED\&.
.PP
Referenced by brain_loop()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
