.TH "Core/Src/time_rtc.c" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Src/time_rtc.c
.SH SYNOPSIS
.br
.PP
\fC#include 'time_rtc\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBRTC_Time_Get\fP (char *buf, size_t buf_len)"
.br
.ti -1c
.RI "void \fBRTC_Time_GetRaw\fP (RTC_TimeTypeDef *t, RTC_DateTypeDef *d)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static RTC_HandleTypeDef * \fBrtc\fP = &\fBhrtc\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void RTC_Time_Get (char * buf, size_t buf_len)"

.PP
Definition at line 14 of file time_rtc\&.c\&.
.PP
References rtc\&.
.SS "void RTC_Time_GetRaw (RTC_TimeTypeDef * t, RTC_DateTypeDef * d)"

.PP
Definition at line 29 of file time_rtc\&.c\&.
.PP
References rtc\&.
.SH "Variable Documentation"
.PP 
.SS "RTC_HandleTypeDef* rtc = &\fBhrtc\fP\fC [static]\fP"

.PP
Definition at line 12 of file time_rtc\&.c\&.
.PP
Referenced by RTC_Time_Get(), and RTC_Time_GetRaw()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
