.TH "Core/Src/uartDMA.c" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Src/uartDMA.c
.SH SYNOPSIS
.br
.PP
\fC#include 'uartDMA\&.h'\fP
.br
\fC#include 'stdio\&.h'\fP
.br
\fC#include 'stdarg\&.h'\fP
.br
\fC#include 'stdbool\&.h'\fP
.br
\fC#include 'stdint\&.h'\fP
.br
\fC#include 'string\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'brain\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBuartHandle\fP   \fBhuart1\fP"
.br
.ti -1c
.RI "#define \fBuart2Handle\fP   \fBhuart2\fP"
.br
.ti -1c
.RI "#define \fBBUFFER_SIZE\fP   10000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBjsonSendEscaped\fP (const char *s)"
.br
.ti -1c
.RI "int \fBgetDataLen\fP (void)"
.br
.ti -1c
.RI "int \fBgetDataLen2\fP (void)"
.br
.ti -1c
.RI "void \fBstartUartDmaTx\fP (void)"
.br
.ti -1c
.RI "void \fBstartUart2DmaTx\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_UART_TxCpltCallback\fP (UART_HandleTypeDef *huart)"
.br
.ti -1c
.RI "int \fBprintfDma\fP (const char *format,\&.\&.\&.)"
.br
.ti -1c
.RI "int \fBprintfDmaBT\fP (const char *format,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBprintConsole\fP (const char *format,\&.\&.\&.)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBbuffer\fP [\fBBUFFER_SIZE\fP] = { 0 }"
.br
.ti -1c
.RI "volatile int \fBhead\fP = 0"
.br
.ti -1c
.RI "volatile int \fBtail\fP = 0"
.br
.ti -1c
.RI "char \fBbuffer2\fP [\fBBUFFER_SIZE\fP] = { 0 }"
.br
.ti -1c
.RI "volatile int \fBhead2\fP = 0"
.br
.ti -1c
.RI "volatile int \fBtail2\fP = 0"
.br
.ti -1c
.RI "bool \fBisFull\fP = false"
.br
.ti -1c
.RI "bool \fBisWrapped\fP = false"
.br
.ti -1c
.RI "bool \fBisFull2\fP = false"
.br
.ti -1c
.RI "bool \fBisWrapped2\fP = false"
.br
.ti -1c
.RI "int \fBtailDma\fP = 0"
.br
.ti -1c
.RI "int \fBtailDma2\fP = 0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUFFER_SIZE   10000"

.PP
Definition at line 12 of file uartDMA\&.c\&.
.SS "#define uart2Handle   \fBhuart2\fP"

.PP
Definition at line 11 of file uartDMA\&.c\&.
.SS "#define uartHandle   \fBhuart1\fP"

.PP
Definition at line 10 of file uartDMA\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int getDataLen (void)"

.PP
Definition at line 33 of file uartDMA\&.c\&.
.PP
References BUFFER_SIZE, head, and tail\&.
.PP
Referenced by printfDma()\&.
.SS "int getDataLen2 (void)"

.PP
Definition at line 43 of file uartDMA\&.c\&.
.PP
References BUFFER_SIZE, head2, and tail2\&.
.PP
Referenced by printfDmaBT()\&.
.SS "void HAL_UART_TxCpltCallback (UART_HandleTypeDef * huart)"

.PP
Definition at line 83 of file uartDMA\&.c\&.
.PP
References BUFFER_SIZE, head, head2, isWrapped, isWrapped2, startUart2DmaTx(), startUartDmaTx(), tail, tail2, tailDma, tailDma2, uart2Handle, and uartHandle\&.
.SS "static void jsonSendEscaped (const char * s)\fC [static]\fP"

.PP
Definition at line 243 of file uartDMA\&.c\&.
.PP
References printfDma()\&.
.PP
Referenced by printConsole()\&.
.SS "void printConsole (const char * format,  \&.\&.\&.)"

.PP
Definition at line 215 of file uartDMA\&.c\&.
.PP
References jsonSendEscaped(), and printfDma()\&.
.PP
Referenced by bms_checkRxFault(), bms_openWireCheck(), bms_printRawData(), bms_readSid(), brain_loop(), brain_start(), IVT_CAN_Config(), IVT_CAN_Setup(), IVT_CAN_Setup_AllMessages(), IVT_FAULT_CHECK(), IVT_PROCESS_MEASURERRORS(), IVT_PROCESS_SYSERRORS(), and IVT_SET_BITRATE()\&.
.SS "int printfDma (const char * format,  \&.\&.\&.)"

.PP
Definition at line 116 of file uartDMA\&.c\&.
.PP
References buffer, BUFFER_SIZE, Error_Handler(), getDataLen(), head, isWrapped, LED_BLUE_GPIO_Port, LED_BLUE_Pin, startUartDmaTx(), tail, and uartHandle\&.
.PP
Referenced by bms_printRthTempsJson(), bms_printTemps(), bms_printVoltage(), bms_readVB(), bms_startDischarge(), bms_stopDischarge(), jsonSendEscaped(), printConsole(), Read_EEPROM(), send_ad68_ui(), send_ivt_ui(), startUI(), and Write_EEPROM()\&.
.SS "int printfDmaBT (const char * format,  \&.\&.\&.)"
HAL_GPIO_TogglePin(LED_BLUE_GPIO_Port, LED_BLUE_Pin);
.PP
Definition at line 163 of file uartDMA\&.c\&.
.PP
References buffer2, BUFFER_SIZE, Error_Handler(), getDataLen2(), head2, isWrapped2, startUart2DmaTx(), tail2, and uart2Handle\&.
.PP
Referenced by ad68_dump_csv_bt(), bms_printVoltage(), and brain_start()\&.
.SS "void startUart2DmaTx (void)"

.PP
Definition at line 68 of file uartDMA\&.c\&.
.PP
References buffer2, BUFFER_SIZE, head2, isWrapped2, tail2, tailDma2, and uart2Handle\&.
.PP
Referenced by HAL_UART_TxCpltCallback(), and printfDmaBT()\&.
.SS "void startUartDmaTx (void)"

.PP
Definition at line 53 of file uartDMA\&.c\&.
.PP
References buffer, BUFFER_SIZE, head, isWrapped, LED_BLUE_GPIO_Port, LED_BLUE_Pin, tail, tailDma, and uartHandle\&.
.PP
Referenced by HAL_UART_TxCpltCallback(), and printfDma()\&.
.SH "Variable Documentation"
.PP 
.SS "char buffer[\fBBUFFER_SIZE\fP] = { 0 }"

.PP
Definition at line 16 of file uartDMA\&.c\&.
.PP
Referenced by printfDma(), and startUartDmaTx()\&.
.SS "char buffer2[\fBBUFFER_SIZE\fP] = { 0 }"

.PP
Definition at line 20 of file uartDMA\&.c\&.
.PP
Referenced by printfDmaBT(), and startUart2DmaTx()\&.
.SS "volatile int head = 0"

.PP
Definition at line 17 of file uartDMA\&.c\&.
.PP
Referenced by getDataLen(), HAL_UART_TxCpltCallback(), printfDma(), and startUartDmaTx()\&.
.SS "volatile int head2 = 0"

.PP
Definition at line 21 of file uartDMA\&.c\&.
.PP
Referenced by getDataLen2(), HAL_UART_TxCpltCallback(), printfDmaBT(), and startUart2DmaTx()\&.
.SS "bool isFull = false"

.PP
Definition at line 24 of file uartDMA\&.c\&.
.SS "bool isFull2 = false"

.PP
Definition at line 27 of file uartDMA\&.c\&.
.SS "bool isWrapped = false"

.PP
Definition at line 25 of file uartDMA\&.c\&.
.PP
Referenced by HAL_UART_TxCpltCallback(), printfDma(), and startUartDmaTx()\&.
.SS "bool isWrapped2 = false"

.PP
Definition at line 28 of file uartDMA\&.c\&.
.PP
Referenced by HAL_UART_TxCpltCallback(), printfDmaBT(), and startUart2DmaTx()\&.
.SS "volatile int tail = 0"

.PP
Definition at line 18 of file uartDMA\&.c\&.
.PP
Referenced by getDataLen(), HAL_UART_TxCpltCallback(), printfDma(), and startUartDmaTx()\&.
.SS "volatile int tail2 = 0"

.PP
Definition at line 22 of file uartDMA\&.c\&.
.PP
Referenced by getDataLen2(), HAL_UART_TxCpltCallback(), printfDmaBT(), and startUart2DmaTx()\&.
.SS "int tailDma = 0"

.PP
Definition at line 30 of file uartDMA\&.c\&.
.PP
Referenced by HAL_UART_TxCpltCallback(), and startUartDmaTx()\&.
.SS "int tailDma2 = 0"

.PP
Definition at line 31 of file uartDMA\&.c\&.
.PP
Referenced by HAL_UART_TxCpltCallback(), and startUart2DmaTx()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
