.TH "Core/Inc/version.h" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Inc/version.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBstartUI\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void startUI (void)"

.PP
Definition at line 17 of file version\&.c\&.
.PP
References HARDWARE_CODENAME, HARDWARE_VERSION, printfDma(), PROJECT_LINK, SOFTWARE_CODENAME, SOFTWARE_VERSION, and STR\&.
.PP
Referenced by brain_start()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
