.TH "Core/Src/version.c" 3 "Sat Dec 20 2025" "lart_bms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Src/version.c
.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br
\fC#include 'brain\&.h'\fP
.br
\fC#include 'uartDMA\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSOFTWARE_CODENAME\fP   bms_lart"
.br
.ti -1c
.RI "#define \fBSOFTWARE_VERSION\fP   alpha\-v2"
.br
.ti -1c
.RI "#define \fBHARDWARE_VERSION\fP   '????'"
.br
.ti -1c
.RI "#define \fBHARDWARE_CODENAME\fP   chicote"
.br
.ti -1c
.RI "#define \fBPROJECT_LINK\fP   'github\&.com/EsTaNG9/lart_bms'"
.br
.ti -1c
.RI "#define \fBSTR_HELPER\fP(x)   #x"
.br
.ti -1c
.RI "#define \fBSTR\fP(x)   \fBSTR_HELPER\fP(x)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBstartUI\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HARDWARE_CODENAME   chicote"

.PP
Definition at line 9 of file version\&.c\&.
.SS "#define HARDWARE_VERSION   '????'"

.PP
Definition at line 8 of file version\&.c\&.
.SS "#define PROJECT_LINK   'github\&.com/EsTaNG9/lart_bms'"

.PP
Definition at line 11 of file version\&.c\&.
.SS "#define SOFTWARE_CODENAME   bms_lart"

.PP
Definition at line 5 of file version\&.c\&.
.SS "#define SOFTWARE_VERSION   alpha\-v2"

.PP
Definition at line 6 of file version\&.c\&.
.SS "#define STR(x)   \fBSTR_HELPER\fP(x)"

.PP
Definition at line 15 of file version\&.c\&.
.SS "#define STR_HELPER(x)   #x"

.PP
Definition at line 14 of file version\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void startUI (void)"

.PP
Definition at line 17 of file version\&.c\&.
.PP
References HARDWARE_CODENAME, HARDWARE_VERSION, printfDma(), PROJECT_LINK, SOFTWARE_CODENAME, SOFTWARE_VERSION, and STR\&.
.PP
Referenced by brain_start()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for lart_bms from the source code\&.
